package com.heytap.accessory.connectivity.constant;

import java.security.SecureRandom;
import java.util.Random;

/* JADX INFO: loaded from: classes14.dex */
public class ConnectConstant {
    public static final String ACTION_ACCESSORY_CONNECT = "android.accessory.device.action.CONNECT";
    public static final String ACTION_ACCESSORY_DISCONNECT = "android.accessory.device.action.DISCONNECT";
    public static final String ACTION_TRANSPORT_ADDRESS = "EXTRA_TRANSPORT_ADDRESS";
    public static final String ACTION_TRANSPORT_TYPE = "EXTRA_TRANSPORT_TYPE";
    public static final String CHANNEL_NAME_CONTROL = "control";
    public static final String CHANNEL_NAME_DEFAULT = "default";
    public static final String CHANNEL_NAME_FILETRANSFER = "filetransfer";
    public static final String CHANNEL_NAME_STREAMING = "streaming";
    public static final int CHANNEL_TYPE_CONTROL = 3;
    public static final int CHANNEL_TYPE_DEFAULT = 1;
    public static final int CHANNEL_TYPE_FILE_TRANSFER = 0;
    public static final int CHANNEL_TYPE_STREAMING = 2;
    public static final String DEFAULT_WIFI_LOCAL_ADDRESS = "02:00:00:00:00:00";
    public static final int DEVICE_ACCEPTED = 119;
    public static final int DEVICE_ACCESSORY_FOUND = 105;
    public static final int DEVICE_ACCESSORY_LOST = 106;
    public static final int DEVICE_ATTACHED = 114;
    public static final int DEVICE_BOND_STATE_NONE = 130;
    public static final int DEVICE_CONNECTION_FAILED = 113;
    public static final int DEVICE_CONNECTION_TIMEOUT = 112;
    public static final int DEVICE_DETACHED = 115;
    public static final int DEVICE_ERROR = 111;
    public static final int DEVICE_HANDLE_RECONNECT_INTENT = 123;
    public static final int DEVICE_INTERNAL_CONNECT = 122;
    public static final int DEVICE_PEER_DESCRIPTION_FAILED = 104;
    public static final int DEVICE_RECONNECT = 121;
    public static final int DEVICE_REQUESTED = 120;
    public static final int DEVICE_STATE_CHANGED = 109;
    public static final int ERROR_AUTOCONNECT_CONNECTIVITY_NOT_SUPPORTED = -1010;
    public static final int ERROR_AUTOCONNECT_CONNECT_FAILED = -1011;
    public static final int ERROR_AUTOCONNECT_INVALID_MODE = -1012;
    public static final int ERROR_BT_ALREADY_CONNECTED = 1;
    public static final int ERROR_CHANNEL_AUTH_DISCONNECTED_UNEXPECTED = -2107;
    public static final int ERROR_CHANNEL_AUTH_INVALID_STATE = -2109;
    public static final int ERROR_CHANNEL_AUTH_REACH_MAX_TRY = -2106;
    public static final int ERROR_CHANNEL_AUTH_RESPONSE_INVALID = -2110;
    public static final int ERROR_CHANNEL_AUTH_TIMEOUT = -2108;
    public static final int ERROR_DISCOVERY_ACCESSORY_FRAMEWORK_INCOMPATIBLE = -1128;
    public static final int ERROR_DISCOVERY_ALREADY_ONGOING_CONNECTION = -1101;
    public static final int ERROR_DISCOVERY_AUTHENTICATION_KSC_ERROR = -2104;
    public static final int ERROR_DISCOVERY_AUTHENTICATION_PENDING_ERROR = -2105;
    public static final int ERROR_DISCOVERY_AUTHENTICATION_REMOTE_CREDENTIALS_FAILED = -1102;
    public static final int ERROR_DISCOVERY_AUTHENTICATION_SELF_CREDENTIALS_FAILED = -1103;
    public static final int ERROR_DISCOVERY_AUTHENTICATION_UNKNOWN_REASON = -1100;
    public static final int ERROR_DISCOVERY_BLE_ADAPTER_FAILED = -1104;
    public static final int ERROR_DISCOVERY_BLE_CREATE_STREAM_FAILED = -1105;
    public static final int ERROR_DISCOVERY_BLE_SOCKET_CONNECT_FAILED = -1106;
    public static final int ERROR_DISCOVERY_BLE_UNSUBSCRIBE = -1129;
    public static final int ERROR_DISCOVERY_BT_ADAPTER_FAILED = -1107;
    public static final int ERROR_DISCOVERY_BT_CLOSE_STREAM_FAILED = -1108;
    public static final int ERROR_DISCOVERY_BT_CREATE_STREAM_FAILED = -1109;
    public static final int ERROR_DISCOVERY_BT_SOCKET_CLOSE_FAILED = -1110;
    public static final int ERROR_DISCOVERY_BT_SOCKET_CONNECT_FAILED = -1111;
    public static final int ERROR_DISCOVERY_BT_SOCKET_CONNECT_TIMEOUT = -1112;
    public static final int ERROR_DISCOVERY_BT_SOCKET_CREATION_FAILED = -1113;
    public static final int ERROR_DISCOVERY_BT_SOCKET_LISTEN_FAILED = -1114;
    public static final int ERROR_DISCOVERY_BT_SOCKET_READ_FAILED = -1115;
    public static final int ERROR_DISCOVERY_BT_SOCKET_READ_WRITE_FAILED = -1116;
    public static final int ERROR_DISCOVERY_BT_SOCKET_WRITE_FAILED = -1117;
    public static final int ERROR_DISCOVERY_CATEGORY_NOT_ALLOWED = -1118;
    public static final int ERROR_DISCOVERY_DEVICE_ALREADY_CONNECTED = -1119;
    public static final int ERROR_DISCOVERY_DEVICE_ALREADY_DISCONNECTED = -1120;
    public static final int ERROR_DISCOVERY_DEVICE_CONNECTION_IN_PROGRESS = -1121;
    public static final int ERROR_DISCOVERY_DEVICE_DISCONNECTION_IN_PROGRESS = -1122;
    public static final int ERROR_DISCOVERY_DEVICE_NOT_PAIRED = -1123;
    public static final int ERROR_DISCOVERY_EXCEED_MAX_CONNECTIONS = -1124;
    public static final int ERROR_DISCOVERY_INVALID_INPUT_INVALID_DEVICE = -1125;
    public static final int ERROR_DISCOVERY_SELF_PEER_DESCRIPTION_FAILED = -1126;
    public static final int ERROR_DISCOVERY_VERSION_INCOMPATIBLE = -1127;
    public static final int LINK_ACTIVE = 2;
    public static final int LINK_DORMANT = 1;
    public static final int LINK_LOSS = 0;
    public static final String THREAD_CONNECTION_ACTION_MESSAGE_HANDLER = "MESSAGE_HANDLER";
    public static final String THREAD_CONNECTION_ACTION_READ = "READ";
    public static final String THREAD_CONNECTION_ACTION_WRITE = "WRITE";
    public static final String THREAD_CONNECTION_ROLE_CLIENT = "C";
    public static final String THREAD_CONNECTION_ROLE_SERVER = "S";
    public static final int TRANSPORT_ALL = 255;
    public static final int TRANSPORT_BLE = 4;
    public static final int TRANSPORT_BT = 2;
    public static final int TRANSPORT_NONE = 0;
    public static final int TRANSPORT_USB = 8;
    public static final int TRANSPORT_WIFI = 1;
    public static final int VALUE_DEVICE_STATE_OFF = 1;
    public static final int VALUE_DEVICE_STATE_ON = 2;
    public static final Random a = new SecureRandom();

    public static int a() {
        return a.nextInt() & 65535;
    }
}
