package com.support.appcompat;

import android.R;

/* JADX INFO: loaded from: classes10.dex */
public final class R$styleable {
    public static final int COUIButtonLayout_couiLimitMaxWidth = 0;
    public static final int COUIButtonLayout_horizontalLayoutPadding = 1;
    public static final int COUIButtonLayout_verticalLayoutPadding = 2;
    public static final int COUIButton_android_textColor = 0;
    public static final int COUIButton_animEnable = 1;
    public static final int COUIButton_animType = 2;
    public static final int COUIButton_brightness = 3;
    public static final int COUIButton_circleButton = 4;
    public static final int COUIButton_closeLimitTextSize = 5;
    public static final int COUIButton_couiRoundType = 6;
    public static final int COUIButton_descText = 7;
    public static final int COUIButton_disabledColor = 8;
    public static final int COUIButton_drawableColor = 9;
    public static final int COUIButton_drawableRadius = 10;
    public static final int COUIButton_expandOffset = 11;
    public static final int COUIButton_isDescType = 12;
    public static final int COUIButton_isShowLoadingText = 13;
    public static final int COUIButton_loadingText = 14;
    public static final int COUIButton_needVibrate = 15;
    public static final int COUIButton_pressAlpha = 16;
    public static final int COUIButton_pressColor = 17;
    public static final int COUIButton_scaleEnable = 18;
    public static final int COUIButton_strokeColor = 19;
    public static final int COUIButton_strokeWidth = 20;
    public static final int COUICheckBox_couiAsyncLoad = 0;
    public static final int COUICheckBox_couiButton = 1;
    public static final int COUICheckBox_couiCheckBoxState = 2;
    public static final int COUIEditText_android_hint = 1;
    public static final int COUIEditText_android_textColorHint = 0;
    public static final int COUIEditText_collapsedTextColor = 2;
    public static final int COUIEditText_collapsedTextSize = 3;
    public static final int COUIEditText_cornerRadius = 4;
    public static final int COUIEditText_couiBackgroundMode = 5;
    public static final int COUIEditText_couiDefaultStrokeColor = 6;
    public static final int COUIEditText_couiDisabledStrokeColor = 7;
    public static final int COUIEditText_couiEditTextDeleteIconNormal = 8;
    public static final int COUIEditText_couiEditTextDeleteIconPressed = 9;
    public static final int COUIEditText_couiEditTextErrorColor = 10;
    public static final int COUIEditText_couiEditTextHintLines = 11;
    public static final int COUIEditText_couiEditTextIsEllipsis = 12;
    public static final int COUIEditText_couiEditTextNoEllipsisText = 13;
    public static final int COUIEditText_couiFocusStrokeWidth = 14;
    public static final int COUIEditText_couiHintAnimationEnabled = 15;
    public static final int COUIEditText_couiHintEnabled = 16;
    public static final int COUIEditText_couiStrokeColor = 17;
    public static final int COUIEditText_couiStrokeWidth = 18;
    public static final int COUIEditText_quickDelete = 19;
    public static final int COUIEditText_rectModePaddingTop = 20;
    public static final int COUILinearLayout_couiMaxHeight = 0;
    public static final int COUILinearLayout_couiMaxWidth = 1;
    public static final int COUIRoundImageView_couiBorderRadius = 0;
    public static final int COUIRoundImageView_couiHasBorder = 1;
    public static final int COUIRoundImageView_couiHasDefaultPic = 2;
    public static final int COUIRoundImageView_couiRoundImageViewOutCircleColor = 3;
    public static final int COUIRoundImageView_couiType = 4;
    public static final int COUIRoundImageView_isImageView = 5;
    public static final int COUIRoundImageView_sizeType = 6;
    public static final int COUISwitch_barCheckedDisabledColor = 0;
    public static final int COUISwitch_barHeight = 1;
    public static final int COUISwitch_barUncheckedDisabledColor = 2;
    public static final int COUISwitch_circlePadding = 3;
    public static final int COUISwitch_innerCircleCheckedDisabledColor = 4;
    public static final int COUISwitch_innerCircleColor = 5;
    public static final int COUISwitch_innerCircleUncheckedDisabledColor = 6;
    public static final int COUISwitch_innerCircleWidth = 7;
    public static final int COUISwitch_loadingDrawable = 8;
    public static final int COUISwitch_outerCircleCheckedDisabledColor = 9;
    public static final int COUISwitch_outerCircleColor = 10;
    public static final int COUISwitch_outerCircleStrokeWidth = 11;
    public static final int COUISwitch_outerCircleUncheckedDisabledColor = 12;
    public static final int COUISwitch_outerCircleWidth = 13;
    public static final int COUISwitch_outerUnCheckedCircleColor = 14;
    public static final int COUISwitch_themedCheckedDrawable = 15;
    public static final int COUISwitch_themedLoadingCheckedBackground = 16;
    public static final int COUISwitch_themedLoadingDrawable = 17;
    public static final int COUISwitch_themedLoadingUncheckedBackground = 18;
    public static final int COUISwitch_themedUncheckedDrawable = 19;
    public static final int COUITextAppearance_android_lineSpacingMultiplier = 0;
    public static final int COUITextAppearance_lineSpacingMultiplier = 1;
    public static final int COUITextView_android_lineSpacingMultiplier = 1;
    public static final int COUITextView_android_textAppearance = 0;
    public static final int COUITheme_couiEmptyHint = 0;
    public static final int COUITheme_couiIsSplitHideWithActionBar = 1;
    public static final int COUITheme_isCOUIDarkTheme = 2;
    public static final int COUITheme_isCOUITheme = 3;
    public static final int COUITheme_startingWindowTitle = 4;
    public static final int COUITheme_windowPreviewType = 5;
    public static final int COUITheme_windowSnapshotPreviewToken = 6;
    public static final int[] COUIButton = {R.attr.textColor, com.heytap.health.R.attr.animEnable, com.heytap.health.R.attr.animType, com.heytap.health.R.attr.brightness, com.heytap.health.R.attr.circleButton, com.heytap.health.R.attr.closeLimitTextSize, com.heytap.health.R.attr.couiRoundType, com.heytap.health.R.attr.descText, com.heytap.health.R.attr.disabledColor, com.heytap.health.R.attr.drawableColor, com.heytap.health.R.attr.drawableRadius, com.heytap.health.R.attr.expandOffset, com.heytap.health.R.attr.isDescType, com.heytap.health.R.attr.isShowLoadingText, com.heytap.health.R.attr.loadingText, com.heytap.health.R.attr.needVibrate, com.heytap.health.R.attr.pressAlpha, com.heytap.health.R.attr.pressColor, com.heytap.health.R.attr.scaleEnable, com.heytap.health.R.attr.strokeColor, com.heytap.health.R.attr.strokeWidth};
    public static final int[] COUIButtonLayout = {com.heytap.health.R.attr.couiLimitMaxWidth, com.heytap.health.R.attr.horizontalLayoutPadding, com.heytap.health.R.attr.verticalLayoutPadding};
    public static final int[] COUICheckBox = {com.heytap.health.R.attr.couiAsyncLoad, com.heytap.health.R.attr.couiButton, com.heytap.health.R.attr.couiCheckBoxState};
    public static final int[] COUIEditText = {R.attr.textColorHint, R.attr.hint, com.heytap.health.R.attr.collapsedTextColor, com.heytap.health.R.attr.collapsedTextSize, com.heytap.health.R.attr.cornerRadius, com.heytap.health.R.attr.couiBackgroundMode, com.heytap.health.R.attr.couiDefaultStrokeColor, com.heytap.health.R.attr.couiDisabledStrokeColor, com.heytap.health.R.attr.couiEditTextDeleteIconNormal, com.heytap.health.R.attr.couiEditTextDeleteIconPressed, com.heytap.health.R.attr.couiEditTextErrorColor, com.heytap.health.R.attr.couiEditTextHintLines, com.heytap.health.R.attr.couiEditTextIsEllipsis, com.heytap.health.R.attr.couiEditTextNoEllipsisText, com.heytap.health.R.attr.couiFocusStrokeWidth, com.heytap.health.R.attr.couiHintAnimationEnabled, com.heytap.health.R.attr.couiHintEnabled, com.heytap.health.R.attr.couiStrokeColor, com.heytap.health.R.attr.couiStrokeWidth, com.heytap.health.R.attr.quickDelete, com.heytap.health.R.attr.rectModePaddingTop};
    public static final int[] COUILinearLayout = {com.heytap.health.R.attr.couiMaxHeight, com.heytap.health.R.attr.couiMaxWidth};
    public static final int[] COUIRoundImageView = {com.heytap.health.R.attr.couiBorderRadius, com.heytap.health.R.attr.couiHasBorder, com.heytap.health.R.attr.couiHasDefaultPic, com.heytap.health.R.attr.couiRoundImageViewOutCircleColor, com.heytap.health.R.attr.couiType, com.heytap.health.R.attr.isImageView, com.heytap.health.R.attr.sizeType};
    public static final int[] COUISwitch = {com.heytap.health.R.attr.barCheckedDisabledColor, com.heytap.health.R.attr.barHeight, com.heytap.health.R.attr.barUncheckedDisabledColor, com.heytap.health.R.attr.circlePadding, com.heytap.health.R.attr.innerCircleCheckedDisabledColor, com.heytap.health.R.attr.innerCircleColor, com.heytap.health.R.attr.innerCircleUncheckedDisabledColor, com.heytap.health.R.attr.innerCircleWidth, com.heytap.health.R.attr.loadingDrawable, com.heytap.health.R.attr.outerCircleCheckedDisabledColor, com.heytap.health.R.attr.outerCircleColor, com.heytap.health.R.attr.outerCircleStrokeWidth, com.heytap.health.R.attr.outerCircleUncheckedDisabledColor, com.heytap.health.R.attr.outerCircleWidth, com.heytap.health.R.attr.outerUnCheckedCircleColor, com.heytap.health.R.attr.themedCheckedDrawable, com.heytap.health.R.attr.themedLoadingCheckedBackground, com.heytap.health.R.attr.themedLoadingDrawable, com.heytap.health.R.attr.themedLoadingUncheckedBackground, com.heytap.health.R.attr.themedUncheckedDrawable};
    public static final int[] COUITextAppearance = {R.attr.lineSpacingMultiplier, com.heytap.health.R.attr.lineSpacingMultiplier};
    public static final int[] COUITextView = {R.attr.textAppearance, R.attr.lineSpacingMultiplier};
    public static final int[] COUITheme = {com.heytap.health.R.attr.couiEmptyHint, com.heytap.health.R.attr.couiIsSplitHideWithActionBar, com.heytap.health.R.attr.isCOUIDarkTheme, com.heytap.health.R.attr.isCOUITheme, com.heytap.health.R.attr.startingWindowTitle, com.heytap.health.R.attr.windowPreviewType, com.heytap.health.R.attr.windowSnapshotPreviewToken};

    private R$styleable() {
    }
}
