package com.example.opponotificationrelay;
import android.app.*;import android.os.*;import android.database.sqlite.SQLiteDatabase;import java.time.*;import java.util.*;import org.json.*;
public final class CalendarHistoryInstrumentation extends Instrumentation {
 int checks;void check(boolean v,String why){checks++;if(!v)throw new AssertionError(why);}
 public void onCreate(Bundle b){super.onCreate(b);start();}
 long t(String date,ZoneId zone){return LocalDate.parse(date).atStartOfDay(zone).toInstant().toEpochMilli();}
 Set<String> set(JSONArray rows)throws Exception{Set<String> result=new TreeSet<>();for(int i=0;i<rows.length();i++)result.add(rows.getString(i));return result;}
 public void onStart(){Bundle result=new Bundle();int code=Activity.RESULT_CANCELED;SQLiteDatabase db=SQLiteDatabase.create(null);
 try{
  ZoneId zone=ZoneId.of("Asia/Singapore");long start=t("2019-01-01",zone),end=t("2026-10-05",zone);
  db.execSQL("CREATE TABLE DBBloodOxygenSaturation(ssoid TEXT,device_unique_id TEXT,display INTEGER,blood_oxygen_saturation_value INTEGER,data_created_timestamp INTEGER)");
  String[] days={"2026-01-04","2026-07-15","2026-09-01","2026-09-20","2026-10-03"};for(String day:days){long stamp=t(day,zone)+3600000;db.execSQL("INSERT INTO DBBloodOxygenSaturation VALUES('account','DEVICE',1,97,?)",new Object[]{stamp});db.execSQL("INSERT INTO DBBloodOxygenSaturation VALUES('account','DEVICE',1,98,?)",new Object[]{stamp+1000});}
  for(String sql:new String[]{"'other','DEVICE',1,97","'account','OTHER',1,97","'account','DEVICE',0,97","'account','DEVICE',1,0","'account','DEVICE',1,101"})db.execSQL("INSERT INTO DBBloodOxygenSaturation VALUES("+sql+",?)",new Object[]{t("2026-08-10",zone)});
  Set<String> dates=set(RootHealthCalendarReader.dates(db,"account","DEVICE","oxygen",start,end,zone));check(dates.size()==5,"all historical days independent of two-day snapshot");for(String day:days)check(dates.contains(day),"historical date "+day);check(!dates.contains("2026-08-10"),"wrong account/device, hidden and invalid excluded");
  check(RootHealthCalendarReader.dates(db,"account","NONE","oxygen",start,end,zone).length()==0,"other device empty");check(RootHealthCalendarReader.dates(db,"account","DEVICE","oxygen",t("2026-09-01",zone),t("2026-09-02",zone),zone).length()==1,"bounded range");
  db.execSQL("DELETE FROM DBBloodOxygenSaturation");ZoneId ny=ZoneId.of("America/New_York");String[] instants={"2024-03-10T04:59:59Z","2024-03-10T05:00:00Z","2024-03-11T03:59:59Z","2024-03-11T04:00:00Z","2024-11-03T03:59:59Z","2024-11-03T04:00:00Z","2024-11-04T04:59:59Z","2024-11-04T05:00:00Z"};Set<String> expected=new TreeSet<>();for(String instant:instants){Instant time=Instant.parse(instant);expected.add(time.atZone(ny).toLocalDate().toString());db.execSQL("INSERT INTO DBBloodOxygenSaturation VALUES('account','DEVICE',1,98,?)",new Object[]{time.toEpochMilli()});}
  check(set(RootHealthCalendarReader.dates(db,"account","DEVICE","oxygen",t("2024-01-01",ny),t("2025-01-01",ny),ny)).equals(expected),"DST day grouping before and after both transitions");
  db.execSQL("CREATE TABLE DBSleepDataStatTable(ssoid TEXT,date INTEGER,total_sleep_time INTEGER)");db.execSQL("INSERT INTO DBSleepDataStatTable VALUES('account',20260104,400),('account',20260715,350),('account',20260801,0),('other',20260920,400)");check(RootHealthCalendarReader.dates(db,"account","DEVICE","sleep",start,end,zone).length()==2,"sleep dates filter empty and other account");
  try{RootHealthCalendarReader.dates(db,"account","DEVICE","injected",start,end,zone);throw new AssertionError("unsupported metric accepted");}catch(java.io.IOException expectedFailure){check(true,"metric whitelist");}
  HealthDataManager manager=HealthDataManager.get(getTargetContext());java.lang.reflect.Field workerField=HealthDataManager.class.getDeclaredField("worker");workerField.setAccessible(true);java.util.concurrent.ExecutorService worker=(java.util.concurrent.ExecutorService)workerField.get(manager);java.util.concurrent.CountDownLatch hold=new java.util.concurrent.CountDownLatch(1),entered=new java.util.concurrent.CountDownLatch(1),drained=new java.util.concurrent.CountDownLatch(1);worker.execute(()->{entered.countDown();try{hold.await(10,java.util.concurrent.TimeUnit.SECONDS);}catch(InterruptedException ignored){}});check(entered.await(2,java.util.concurrent.TimeUnit.SECONDS),"import worker held for request ordering test");
  HealthDataManager.Listener observer=(data,message,busy)->{};try{runOnMainSync(()->{manager.add(observer);manager.request(new HealthMetricsData.Period(LocalDate.of(2026,9,1),0),LocalDate.of(2026,9,1),false);});java.lang.reflect.Field demand=HealthDataManager.class.getDeclaredField("requestedWindow");demand.setAccessible(true);String summary=(String)demand.get(manager);runOnMainSync(()->manager.requestOxygenDay(LocalDate.of(2026,9,1)));check(!summary.equals((String)demand.get(manager)),"oxygen raw-first request differs from other metric summary demand");check(manager.hasPendingRequests(),"queued current-day import reports loading before worker starts");}finally{runOnMainSync(()->manager.remove(observer));hold.countDown();worker.execute(drained::countDown);}check(drained.await(5,java.util.concurrent.TimeUnit.SECONDS),"obsolete queued imports retire");check(!manager.hasPendingRequests(),"no pending import after observer leaves");
  JSONObject official=new OfficialSettingsClient(getTargetContext()).calendar(RelayConfig.getTargetMac(getTargetContext()),"oxygen",ZoneId.systemDefault().getId());Set<String> real=set(official.getJSONArray("calendar"));check(real.contains("2026-09-01")&&real.contains("2026-09-20"),"real old oxygen dates found");result.putInt("officialOxygenDates",real.size());
  result.putInt("checks",checks);result.putString("status","CALENDAR_HISTORY_PASS");code=Activity.RESULT_OK;
 }catch(Throwable error){result.putString("status","FAILED");result.putString("error",error.toString());}finally{db.close();finish(code,result);}
 }
}
