package com.example.opponotificationrelay;
import android.app.*;import android.os.*;import android.content.*;import java.time.*;import java.util.*;import java.io.*;
import com.heytap.health.sleep.formula.formula.*;import com.heytap.health.sleep.formula.formula.result.OsaResultBean;
public final class OsaRiskInstrumentation extends Instrumentation {
 boolean refresh;int checks;void check(boolean b,String s){checks++;if(!b)throw new AssertionError(s);}public void onCreate(Bundle b){super.onCreate(b);refresh=b!=null&&b.getString("refresh","false").equals("true");start();}
 public void onStart(){Bundle out=new Bundle();int code=Activity.RESULT_CANCELED;
  try{int start=1791000000;TreeMap<Integer,Integer> sleep=new TreeMap<>(),sensor=new TreeMap<>(),oxygen=new TreeMap<>();for(int i=0;i<240;i++){sleep.put(start+i*60,1);sensor.put(start+i*60,0);oxygen.put(start+i*60,((97-69)<<3)|4);}OsaAnalysisInput input=OsaAnalysisInput.build(sleep,sensor,oxygen);check(input.sleep.sleepMinBuff[0]==2,"raw light maps to algorithm 2");check(input.sleep.sleepDataLen==240&&input.sensor.sensorOsaBuffLen==240,"minute length");check(input.oxygen.spo2BuffLen==239*60+1&&input.oxygen.spo2Buffs[1]==0,"sparse oxygen holes stay zero");check(OsaAnalysisInput.stage(2)==1&&OsaAnalysisInput.stage(3)==3&&OsaAnalysisInput.stage(4)==0,"stage conversion");
   for(int type=0;type<4;type++)for(int raw=0;raw<256;raw++){int percent=(raw>>>3)==0?0:(raw>>>3)+69,reliability=(raw>>>1)&3;int expected=type==0&&percent>69?((percent-69)<<3)|4|reliability:0;check(OsaAnalysisInput.packedSpo2(type,raw)==expected,"official V2 oxygen packing");}
   check(input.oxygen.spo2Buffs[0]==228,"native expects packed oxygen not percent");
   OsaUserBean user=OsaAnalysisInput.emptyUser();check(user.age==0&&user.height==0&&user.weight==0&&user.sex==0,"official blank user defaults");
   try{OsaAnalysisInput.build(new TreeMap<>(),sensor,oxygen);throw new AssertionError("empty accepted");}catch(IOException expected){check(expected.getMessage().equals("OSA_SLEEP_INCOMPLETE"),"empty rejected");}
   TreeMap<Integer,Integer> sparse=new TreeMap<>();sparse.put(start,1);try{OsaAnalysisInput.build(sleep,sparse,oxygen);throw new AssertionError("sensor short accepted");}catch(IOException expected){check(true,"short sensor rejected");}
   OsaResultBean bad=new OsaResultBean();bad.osaLevel=-2;check(!OsaRiskAdapter.valid(bad),"fatal invalid");bad.osaLevel=-1;check(!OsaRiskAdapter.valid(bad),"insufficient invalid");bad.osaLevel=0;bad.osaAhi=Float.NaN;check(!OsaRiskAdapter.valid(bad),"nan invalid");bad.osaAhi=0;bad.noPersonInBedFlag=1;check(!OsaRiskAdapter.valid(bad),"no person invalid");
   for(int i=0;i<2;i++){OsaResultBean result=OsaRiskAdapter.watch("OWW251",input,null);out.putInt("syntheticLevel"+i,result.osaLevel);check(result!=null,"native returns without filled profile");}
   try{if(refresh){Context c=getTargetContext();runOnMainSync(()->{c.startActivity(new Intent(c,SnoreMonitoringActivity.class).addFlags(Intent.FLAG_ACTIVITY_NEW_TASK));BackgroundStart.restore(c,"OSA input verification");HealthSyncManager.get(c).interactive(true);});Thread.sleep(1500);OsaAnalysisRepository.refresh(c,RelayConfig.getTargetMac(c),LocalDate.now(),()->false);}OsaAnalysisInput real=OsaAnalysisRepository.load(getTargetContext(),RelayConfig.getTargetMac(getTargetContext()),LocalDate.now());out.putInt("realSleepMinutes",real.sleepMinutes);out.putInt("realSensorMinutes",real.sensorMinutes);out.putInt("realOxygenSamples",real.oxygenSeconds);OsaResultBean result=OsaRiskAdapter.watch("OWW251",real,null);out.putInt("realLevel",result.osaLevel);out.putFloat("realAhi",result.osaAhi);out.putBoolean("realValid",OsaRiskAdapter.valid(result));out.putInt("realNoPerson",result.noPersonInBedFlag);out.putInt("realInvalidSpo2",result.invalidSpo2Ratio);}catch(IOException absent){out.putString("realInputStatus",absent.getMessage());}
   out.putInt("checks",checks);out.putString("status","OSA_RISK_PASS");code=Activity.RESULT_OK;
  }catch(Throwable e){out.putString("status","OSA_RISK_FAILED");out.putString("error",e.toString());}finally{finish(code,out);}
 }
}
