package com.example.opponotificationrelay;
import java.io.*;import java.util.*;import java.util.concurrent.atomic.*;
public final class OsaWatchProtocolTest {
 static int checks;static final int START=1790910000,END=START+3600;
 interface Action{void run()throws Exception;}
 static void check(boolean b,String label){checks++;if(!b)throw new AssertionError(label);}
 static void reject(Action a)throws Exception{try{a.run();throw new AssertionError("invalid accepted");}catch(IOException expected){checks++;}}
 static byte[] activation(int type,int value,int error){return HealthProto.numbers(1,type,2,value,3,error).encode();}
 static byte[] frame(int cid,byte[] body){return OafCrypto.concat(new byte[]{0,(byte)cid},body);}
 static final class Fixture {
  long now=100;final ByteArrayOutputStream output=new ByteArrayOutputStream();final OafHealthChannel channel;
  Fixture()throws Exception {channel=new OafHealthChannel(new OafWire(new ByteArrayInputStream(new byte[0]),output),new OafHealthChannel.Events(){public long now(){return Fixture.this.now;}public void changed(){}public void status(String s){}});channel.refresh();channel.peer(17,OafHealthChannel.PROFILE);channel.start();int sid=channel.reserved();channel.control(HealthSettingsTest.control(2,17,OafCrypto.concat(new byte[]{0},OafWire.be16(1),OafWire.be16(sid))),HealthSettingsTest.end());channel.pump();channel.receive(frame(197,HealthSettingsTest.fixture()));}
 }
 public static void main(String[] args)throws Exception {
  List<HealthProto.Node> fullNight=new ArrayList<>();for(int i=0;i<1440;i++)fullNight.add(HealthProto.numbers(1,i,2,1));byte[] night=HealthProto.numbers(2,START,3,START+86400).withMessages(4,fullNight).encode();check(HealthProto.parse(night).messages(4).size()==1440,"full night is not truncated at 512 rows");byte[] over=new byte[4097*2];for(int i=0;i<4097;i++){over[i*2]=8;over[i*2+1]=1;}reject(()->HealthProto.parse(over));
  OsaWatchProtocol.Request a=OsaWatchProtocol.queryActivation();check(a.cid==202&&HealthProto.parse(a.bytes()).number(1,0)==1,"read activation command");byte[] copy=a.bytes();copy[0]=0;check(a.bytes()[0]!=0,"request immutable");
  check(OsaWatchProtocol.activation(activation(1,1,0)),"active");check(!OsaWatchProtocol.activation(activation(1,0,0)),"inactive");reject(()->OsaWatchProtocol.activation(activation(2,1,0)));reject(()->OsaWatchProtocol.activation(activation(1,2,0)));reject(()->OsaWatchProtocol.activation(activation(1,1,1)));reject(()->OsaWatchProtocol.activation(new byte[0]));
  OsaWatchProtocol.Request sensor=OsaWatchProtocol.sensor(START,END);check(sensor.cid==101,"sensor command");reject(()->OsaWatchProtocol.sensor(END,START));reject(()->OsaWatchProtocol.sensor(START,START+172801));
  HealthProto.Node row=HealthProto.numbers(1,2,2,3);byte[] data=HealthProto.numbers(2,START,3,END).withMessages(4,Arrays.asList(row)).encode();OsaWatchProtocol.Samples samples=OsaWatchProtocol.sensor(sensor,data);check(samples.timestamps[0]==START+120&&samples.values[0]==3,"minute offsets");check(OsaWatchProtocol.sensor(sensor,new byte[0]).timestamps.length==0,"empty sensor");
  reject(()->OsaWatchProtocol.sensor(sensor,HealthProto.numbers(2,START,3,END).withMessages(4,Arrays.asList(row,row)).encode()));reject(()->OsaWatchProtocol.sensor(sensor,HealthProto.numbers(1,2,2,START,3,END).encode()));
  OsaWatchProtocol.Request index=OsaWatchProtocol.hrvIndex(START,END);check(index.cid==57,"index command");OsaWatchProtocol.Index parsed=OsaWatchProtocol.packetIndex(index,HealthProto.numbers(1,1,2,START).withBytes(4,new byte[]{97}).encode());check(parsed.count==1&&parsed.session.equals("a"),"session preserved");reject(()->OsaWatchProtocol.packetIndex(index,HealthProto.numbers(1,129).encode()));reject(()->OsaWatchProtocol.packetIndex(index,HealthProto.empty().withBytes(4,new byte[]{(byte)255}).encode()));
  OsaWatchProtocol.Request packet=OsaWatchProtocol.hrvPacket(1,START,END,"a");check(packet.cid==58,"packet command");byte[] packed=HealthProto.numbers(1,1,2,START).withBytes(3,new byte[]{10,20,30}).encode();samples=OsaWatchProtocol.hrv(packet,packed);check(Arrays.equals(samples.values,new int[]{10,20,30})&&samples.end==START+120,"packed samples");
  byte[] negative={(byte)255,(byte)255,(byte)255,(byte)255,(byte)255,(byte)255,(byte)255,(byte)255,(byte)255,1};check(HealthProto.parse(HealthProto.empty().withBytes(3,negative).encode()).repeatedInt32(3,1)[0]==-1,"negative int32");reject(()->HealthProto.parse(HealthProto.empty().withBytes(3,new byte[]{1,2}).encode()).repeatedInt32(3,1));reject(()->OsaWatchProtocol.hrv(packet,HealthProto.numbers(1,2,2,START).encode()));reject(()->OsaWatchProtocol.hrv(packet,HealthProto.numbers(1,1,2,START-120).encode()));
  Fixture f=new Fixture();AtomicInteger ok=new AtomicInteger(),failed=new AtomicInteger();check(f.channel.osa(a,(accepted,body,message)->{if(accepted)ok.incrementAndGet();else failed.incrementAndGet();}),"queued");check(!f.channel.osa(a,(x,y,z)->{}),"no concurrent request");f.channel.pump();f.channel.receive(frame(101,data));check(ok.get()==0&&f.channel.snapshot().busy,"wrong cid ignored");f.channel.receive(frame(202,activation(1,1,0)));check(ok.get()==1&&failed.get()==0&&!f.channel.snapshot().connected,"valid retires endpoint");f.channel.receive(frame(202,activation(1,1,0)));f.channel.close();check(ok.get()==1&&failed.get()==0,"one callback only");
  Fixture timeout=new Fixture();check(timeout.channel.osa(a,(x,y,z)->{if(!x)failed.incrementAndGet();}),"timeout queued");timeout.channel.pump();int sent=timeout.output.size();timeout.now=20000;timeout.channel.pump();timeout.channel.pump();check(failed.get()==1&&timeout.output.size()==sent&&!timeout.channel.snapshot().busy,"timeout no replay");
  Fixture invalid=new Fixture();invalid.channel.osa(a,(x,y,z)->{if(!x)failed.incrementAndGet();});invalid.channel.pump();invalid.channel.receive(frame(202,activation(2,1,0)));invalid.channel.close();check(failed.get()==2,"invalid response fails once");
  Fixture close=new Fixture();close.channel.osa(a,(x,y,z)->{if(!x)failed.incrementAndGet();});close.channel.close();close.channel.pump();check(failed.get()==3,"queued close cancelled");
  System.out.println("OsaWatchProtocolTest: "+checks+" checks passed");
 }
}
