package com.oplus.aiunit.vision;

import com.garmin.fit.Profile$Type;
import com.heytap.log.formatter.LogFieldKey;
import com.heytap.sports.record.details.bean.SportSummaryBean;

/* JADX INFO: loaded from: classes13.dex */
public class e2m extends bxb {
    public static final int CustomTargetValueHighFieldNum = 6;
    public static final int CustomTargetValueLowFieldNum = 5;
    public static final int DurationTypeFieldNum = 1;
    public static final int DurationValueFieldNum = 2;
    public static final int EquipmentFieldNum = 9;
    public static final int ExerciseCategoryFieldNum = 10;
    public static final int ExerciseNameFieldNum = 11;
    public static final int ExerciseWeightFieldNum = 12;
    public static final int IntensityFieldNum = 7;
    public static final int MessageIndexFieldNum = 254;
    public static final int NotesFieldNum = 8;
    public static final int SecondaryCustomTargetValueHighFieldNum = 22;
    public static final int SecondaryCustomTargetValueLowFieldNum = 21;
    public static final int SecondaryTargetTypeFieldNum = 19;
    public static final int SecondaryTargetValueFieldNum = 20;
    public static final int TargetTypeFieldNum = 3;
    public static final int TargetValueFieldNum = 4;
    public static final int WeightDisplayUnitFieldNum = 13;
    public static final int WktStepNameFieldNum = 0;
    public static final bxb h;

    static {
        bxb bxbVar = new bxb("workout_step", 27);
        h = bxbVar;
        bxbVar.e(new w97("message_index", 254, 132, 1.0d, 0.0d, "", false, Profile$Type.MESSAGE_INDEX));
        Profile$Type profile$Type = Profile$Type.STRING;
        bxbVar.e(new w97("wkt_step_name", 0, 7, 1.0d, 0.0d, "", false, profile$Type));
        bxbVar.e(new w97("duration_type", 1, 0, 1.0d, 0.0d, "", false, Profile$Type.WKT_STEP_DURATION));
        Profile$Type profile$Type2 = Profile$Type.UINT32;
        bxbVar.e(new w97("duration_value", 2, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(3).k.add(new p2j("duration_time", 134, 1000.0d, 0.0d, "s"));
        bxbVar.d.get(3).k.get(0).b(1, 0L);
        bxbVar.d.get(3).k.get(0).b(1, 28L);
        bxbVar.d.get(3).k.add(new p2j("duration_distance", 134, 100.0d, 0.0d, LogFieldKey.MESSAGE_KEY));
        bxbVar.d.get(3).k.get(1).b(1, 1L);
        bxbVar.d.get(3).k.add(new p2j("duration_hr", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(3).k.get(2).b(1, 2L);
        bxbVar.d.get(3).k.get(2).b(1, 3L);
        bxbVar.d.get(3).k.add(new p2j("duration_calories", 134, 1.0d, 0.0d, SportSummaryBean.CALORIES));
        bxbVar.d.get(3).k.get(3).b(1, 4L);
        bxbVar.d.get(3).k.add(new p2j("duration_step", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(3).k.get(4).b(1, 6L);
        bxbVar.d.get(3).k.get(4).b(1, 7L);
        bxbVar.d.get(3).k.get(4).b(1, 8L);
        bxbVar.d.get(3).k.get(4).b(1, 9L);
        bxbVar.d.get(3).k.get(4).b(1, 10L);
        bxbVar.d.get(3).k.get(4).b(1, 11L);
        bxbVar.d.get(3).k.get(4).b(1, 12L);
        bxbVar.d.get(3).k.get(4).b(1, 13L);
        bxbVar.d.get(3).k.add(new p2j("duration_power", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(3).k.get(5).b(1, 14L);
        bxbVar.d.get(3).k.get(5).b(1, 15L);
        bxbVar.d.get(3).k.add(new p2j("duration_reps", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(3).k.get(6).b(1, 29L);
        Profile$Type profile$Type3 = Profile$Type.WKT_STEP_TARGET;
        bxbVar.e(new w97("target_type", 3, 0, 1.0d, 0.0d, "", false, profile$Type3));
        bxbVar.e(new w97("target_value", 4, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(5).k.add(new p2j("target_speed_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(0).b(3, 0L);
        bxbVar.d.get(5).k.add(new p2j("target_hr_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(1).b(3, 1L);
        bxbVar.d.get(5).k.add(new p2j("target_cadence_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(2).b(3, 3L);
        bxbVar.d.get(5).k.add(new p2j("target_power_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(3).b(3, 4L);
        bxbVar.d.get(5).k.add(new p2j("repeat_steps", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(4).b(1, 6L);
        bxbVar.d.get(5).k.add(new p2j("repeat_time", 134, 1000.0d, 0.0d, "s"));
        bxbVar.d.get(5).k.get(5).b(1, 7L);
        bxbVar.d.get(5).k.add(new p2j("repeat_distance", 134, 100.0d, 0.0d, LogFieldKey.MESSAGE_KEY));
        bxbVar.d.get(5).k.get(6).b(1, 8L);
        bxbVar.d.get(5).k.add(new p2j("repeat_calories", 134, 1.0d, 0.0d, SportSummaryBean.CALORIES));
        bxbVar.d.get(5).k.get(7).b(1, 9L);
        bxbVar.d.get(5).k.add(new p2j("repeat_hr", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(5).k.get(8).b(1, 10L);
        bxbVar.d.get(5).k.get(8).b(1, 11L);
        bxbVar.d.get(5).k.add(new p2j("repeat_power", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(5).k.get(9).b(1, 12L);
        bxbVar.d.get(5).k.get(9).b(1, 13L);
        bxbVar.d.get(5).k.add(new p2j("target_stroke_type", 0, 1.0d, 0.0d, ""));
        bxbVar.d.get(5).k.get(10).b(3, 11L);
        bxbVar.e(new w97("custom_target_value_low", 5, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(6).k.add(new p2j("custom_target_speed_low", 134, 1000.0d, 0.0d, "m/s"));
        bxbVar.d.get(6).k.get(0).b(3, 0L);
        bxbVar.d.get(6).k.add(new p2j("custom_target_heart_rate_low", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(6).k.get(1).b(3, 1L);
        bxbVar.d.get(6).k.add(new p2j("custom_target_cadence_low", 134, 1.0d, 0.0d, "rpm"));
        bxbVar.d.get(6).k.get(2).b(3, 3L);
        bxbVar.d.get(6).k.add(new p2j("custom_target_power_low", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(6).k.get(3).b(3, 4L);
        bxbVar.e(new w97("custom_target_value_high", 6, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(7).k.add(new p2j("custom_target_speed_high", 134, 1000.0d, 0.0d, "m/s"));
        bxbVar.d.get(7).k.get(0).b(3, 0L);
        bxbVar.d.get(7).k.add(new p2j("custom_target_heart_rate_high", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(7).k.get(1).b(3, 1L);
        bxbVar.d.get(7).k.add(new p2j("custom_target_cadence_high", 134, 1.0d, 0.0d, "rpm"));
        bxbVar.d.get(7).k.get(2).b(3, 3L);
        bxbVar.d.get(7).k.add(new p2j("custom_target_power_high", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(7).k.get(3).b(3, 4L);
        bxbVar.e(new w97("intensity", 7, 0, 1.0d, 0.0d, "", false, Profile$Type.INTENSITY));
        bxbVar.e(new w97("notes", 8, 7, 1.0d, 0.0d, "", false, profile$Type));
        bxbVar.e(new w97("equipment", 9, 0, 1.0d, 0.0d, "", false, Profile$Type.WORKOUT_EQUIPMENT));
        bxbVar.e(new w97("exercise_category", 10, 132, 1.0d, 0.0d, "", false, Profile$Type.EXERCISE_CATEGORY));
        Profile$Type profile$Type4 = Profile$Type.UINT16;
        bxbVar.e(new w97("exercise_name", 11, 132, 1.0d, 0.0d, "", false, profile$Type4));
        bxbVar.e(new w97("exercise_weight", 12, 132, 100.0d, 0.0d, "kg", false, profile$Type4));
        bxbVar.e(new w97("weight_display_unit", 13, 132, 1.0d, 0.0d, "", false, Profile$Type.FIT_BASE_UNIT));
        bxbVar.e(new w97("secondary_target_type", 19, 0, 1.0d, 0.0d, "", false, profile$Type3));
        bxbVar.e(new w97("secondary_target_value", 20, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(16).k.add(new p2j("secondary_target_speed_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(16).k.get(0).b(19, 0L);
        bxbVar.d.get(16).k.add(new p2j("secondary_target_hr_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(16).k.get(1).b(19, 1L);
        bxbVar.d.get(16).k.add(new p2j("secondary_target_cadence_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(16).k.get(2).b(19, 3L);
        bxbVar.d.get(16).k.add(new p2j("secondary_target_power_zone", 134, 1.0d, 0.0d, ""));
        bxbVar.d.get(16).k.get(3).b(19, 4L);
        bxbVar.d.get(16).k.add(new p2j("secondary_target_stroke_type", 0, 1.0d, 0.0d, ""));
        bxbVar.d.get(16).k.get(4).b(19, 11L);
        bxbVar.e(new w97("secondary_custom_target_value_low", 21, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(17).k.add(new p2j("secondary_custom_target_speed_low", 134, 1000.0d, 0.0d, "m/s"));
        bxbVar.d.get(17).k.get(0).b(19, 0L);
        bxbVar.d.get(17).k.add(new p2j("secondary_custom_target_heart_rate_low", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(17).k.get(1).b(19, 1L);
        bxbVar.d.get(17).k.add(new p2j("secondary_custom_target_cadence_low", 134, 1.0d, 0.0d, "rpm"));
        bxbVar.d.get(17).k.get(2).b(19, 3L);
        bxbVar.d.get(17).k.add(new p2j("secondary_custom_target_power_low", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(17).k.get(3).b(19, 4L);
        bxbVar.e(new w97("secondary_custom_target_value_high", 22, 134, 1.0d, 0.0d, "", false, profile$Type2));
        bxbVar.d.get(18).k.add(new p2j("secondary_custom_target_speed_high", 134, 1000.0d, 0.0d, "m/s"));
        bxbVar.d.get(18).k.get(0).b(19, 0L);
        bxbVar.d.get(18).k.add(new p2j("secondary_custom_target_heart_rate_high", 134, 1.0d, 0.0d, "% or bpm"));
        bxbVar.d.get(18).k.get(1).b(19, 1L);
        bxbVar.d.get(18).k.add(new p2j("secondary_custom_target_cadence_high", 134, 1.0d, 0.0d, "rpm"));
        bxbVar.d.get(18).k.get(2).b(19, 3L);
        bxbVar.d.get(18).k.add(new p2j("secondary_custom_target_power_high", 134, 1.0d, 0.0d, "% or watts"));
        bxbVar.d.get(18).k.get(3).b(19, 4L);
    }

    public e2m(bxb bxbVar) {
        super(bxbVar);
    }
}
