package com.oplus.aiunit.vision;

import androidx.exifinterface.media.ExifInterface;
import com.heytap.health.protocol.fitness.FitnessProto$FitnessCmdId;
import com.heytap.health.protocol.userinfo.UserInfoProto$UserInfoCmdId;
import com.heytap.health.watch.watchface.proto.Proto$SyncEventMessage;
import com.heytap.store.base.core.http.HttpUtils;
import com.heytap.store.base.core.util.deeplink.DeepLinkInterpreter;
import com.lifesense.plugin.ble.data.tracker.ATDataProfile;
import com.oplus.deviceui.BatteryView;
import com.oplus.mydevices.sdk.Constants;
import com.oplus.smartenginehelper.entity.TextEntity;
import io.protostuff.MapSchema;

/* JADX INFO: loaded from: classes11.dex */
public final class fpe {
    static {
        mdb.Commands.put("newcommand", new dpe(0, 2, 2));
        mdb.Commands.put("renewcommand", new dpe(1, 2, 2));
        mdb.Commands.put("rule", new dpe(2, 2, 1));
        mdb.Commands.put("hspace", new dpe(3, 1));
        mdb.Commands.put("vspace", new dpe(4, 1));
        mdb.Commands.put("llap", new dpe(5, 1));
        mdb.Commands.put("rlap", new dpe(6, 1));
        mdb.Commands.put("clap", new dpe(7, 1));
        mdb.Commands.put("mathllap", new dpe(8, 1));
        mdb.Commands.put("mathrlap", new dpe(9, 1));
        mdb.Commands.put("mathclap", new dpe(10, 1));
        mdb.Commands.put("includegraphics", new dpe(11, 1, 1));
        mdb.Commands.put("cfrac", new dpe(12, 2, 1));
        mdb.Commands.put("frac", new dpe(13, 2));
        mdb.Commands.put("sfrac", new dpe(14, 2));
        mdb.Commands.put("genfrac", new dpe(15, 6));
        mdb.Commands.put("over", new dpe(16, 0));
        mdb.Commands.put("overwithdelims", new dpe(17, 2));
        mdb.Commands.put("atop", new dpe(18, 0));
        mdb.Commands.put("atopwithdelims", new dpe(19, 2));
        mdb.Commands.put("choose", new dpe(20, 0));
        mdb.Commands.put("underscore", new dpe(21, 0));
        mdb.Commands.put("mbox", new dpe(22, 1));
        mdb.Commands.put("text", new dpe(23, 1));
        mdb.Commands.put("intertext", new dpe(24, 1));
        mdb.Commands.put("binom", new dpe(25, 2));
        mdb.Commands.put("mathbf", new dpe(26, 1));
        mdb.Commands.put("bf", new dpe(27, 0));
        mdb.Commands.put("mathbb", new dpe(28, 1));
        mdb.Commands.put("mathcal", new dpe(29, 1));
        mdb.Commands.put("cal", new dpe(30, 1));
        mdb.Commands.put("mathit", new dpe(31, 1));
        mdb.Commands.put("it", new dpe(32, 0));
        mdb.Commands.put("mathrm", new dpe(33, 1));
        mdb.Commands.put("rm", new dpe(34, 0));
        mdb.Commands.put("mathscr", new dpe(35, 1));
        mdb.Commands.put("mathsf", new dpe(36, 1));
        mdb.Commands.put("sf", new dpe(37, 0));
        mdb.Commands.put("mathtt", new dpe(38, 1));
        mdb.Commands.put("tt", new dpe(39, 0));
        mdb.Commands.put("mathfrak", new dpe(40, 1));
        mdb.Commands.put("mathds", new dpe(41, 1));
        mdb.Commands.put("frak", new dpe(42, 1));
        mdb.Commands.put("Bbb", new dpe(43, 1));
        mdb.Commands.put("oldstylenums", new dpe(44, 1));
        mdb.Commands.put(TextEntity.TYPEFACE_STYLE_BOLD, new dpe(45, 1));
        mdb.Commands.put("^", new dpe(46, 1));
        mdb.Commands.put("'", new dpe(47, 1));
        mdb.Commands.put("\"", new dpe(48, 1));
        mdb.Commands.put("`", new dpe(49, 1));
        mdb.Commands.put(HttpUtils.EQUAL_SIGN, new dpe(50, 1));
        mdb.Commands.put(".", new dpe(51, 1));
        mdb.Commands.put("~", new dpe(52, 1));
        mdb.Commands.put("u", new dpe(53, 1));
        mdb.Commands.put("v", new dpe(54, 1));
        mdb.Commands.put("H", new dpe(55, 1));
        mdb.Commands.put("r", new dpe(56, 1));
        mdb.Commands.put("U", new dpe(57, 1));
        mdb.Commands.put(ExifInterface.GPS_DIRECTION_TRUE, new dpe(58, 1));
        mdb.Commands.put("t", new dpe(59, 1));
        mdb.Commands.put("accent", new dpe(60, 2));
        mdb.Commands.put("grkaccent", new dpe(61, 2));
        mdb.Commands.put("hat", new dpe(62, 1));
        mdb.Commands.put("widehat", new dpe(63, 1));
        mdb.Commands.put("tilde", new dpe(64, 1));
        mdb.Commands.put("acute", new dpe(65, 1));
        mdb.Commands.put("grave", new dpe(66, 1));
        mdb.Commands.put("ddot", new dpe(67, 1));
        mdb.Commands.put("cyrddot", new dpe(68, 1));
        mdb.Commands.put("mathring", new dpe(69, 1));
        mdb.Commands.put("bar", new dpe(70, 1));
        mdb.Commands.put("breve", new dpe(71, 1));
        mdb.Commands.put("check", new dpe(72, 1));
        mdb.Commands.put("vec", new dpe(73, 1));
        mdb.Commands.put("dot", new dpe(74, 1));
        mdb.Commands.put("widetilde", new dpe(75, 1));
        mdb.Commands.put("nbsp", new dpe(76, 0));
        mdb.Commands.put("smallmatrix@@env", new dpe(77, 1));
        mdb.Commands.put("matrix@@env", new dpe(78, 1));
        mdb.Commands.put("overrightarrow", new dpe(79, 1));
        mdb.Commands.put("overleftarrow", new dpe(80, 1));
        mdb.Commands.put("overleftrightarrow", new dpe(81, 1));
        mdb.Commands.put("underrightarrow", new dpe(82, 1));
        mdb.Commands.put("underleftarrow", new dpe(83, 1));
        mdb.Commands.put("underleftrightarrow", new dpe(84, 1));
        mdb.Commands.put("xleftarrow", new dpe(85, 1, 1));
        mdb.Commands.put("xrightarrow", new dpe(86, 1, 1));
        mdb.Commands.put("underbrace", new dpe(87, 1));
        mdb.Commands.put("overbrace", new dpe(88, 1));
        mdb.Commands.put("underbrack", new dpe(89, 1));
        mdb.Commands.put("overbrack", new dpe(90, 1));
        mdb.Commands.put("underparen", new dpe(91, 1));
        mdb.Commands.put("overparen", new dpe(92, 1));
        mdb.Commands.put("sqrt", new dpe(93, 1, 1));
        mdb.Commands.put("sqrtsign", new dpe(94, 1));
        mdb.Commands.put("overline", new dpe(95, 1));
        mdb.Commands.put("underline", new dpe(96, 1));
        mdb.Commands.put("mathop", new dpe(97, 1));
        mdb.Commands.put("mathpunct", new dpe(98, 1));
        mdb.Commands.put("mathord", new dpe(99, 1));
        mdb.Commands.put("mathrel", new dpe(100, 1));
        mdb.Commands.put("mathinner", new dpe(101, 1));
        mdb.Commands.put("mathbin", new dpe(102, 1));
        mdb.Commands.put("mathopen", new dpe(103, 1));
        mdb.Commands.put("mathclose", new dpe(104, 1));
        mdb.Commands.put("joinrel", new dpe(105, 0));
        mdb.Commands.put("smash", new dpe(106, 1, 1));
        mdb.Commands.put("vdots", new dpe(107, 0));
        mdb.Commands.put("ddots", new dpe(108, 0));
        mdb.Commands.put("iddots", new dpe(109, 0));
        mdb.Commands.put("nolimits", new dpe(110, 0));
        mdb.Commands.put("limits", new dpe(111, 0));
        mdb.Commands.put("normal", new dpe(112, 0));
        mdb.Commands.put("(", new dpe(113, 0));
        mdb.Commands.put("[", new dpe(114, 0));
        mdb.Commands.put(y04.TIME_STYLE_LEFT_DIR_NAME, new dpe(115, 1));
        mdb.Commands.put(TextEntity.ELLIPSIZE_MIDDLE, new dpe(116, 1));
        mdb.Commands.put("cr", new dpe(117, 0));
        mdb.Commands.put("multicolumn", new dpe(118, 3));
        mdb.Commands.put("hdotsfor", new dpe(119, 1, 1));
        mdb.Commands.put("array@@env", new dpe(120, 2));
        mdb.Commands.put("align@@env", new dpe(121, 2));
        mdb.Commands.put("aligned@@env", new dpe(122, 2));
        mdb.Commands.put("flalign@@env", new dpe(123, 2));
        mdb.Commands.put("alignat@@env", new dpe(124, 2));
        mdb.Commands.put("alignedat@@env", new dpe(125, 2));
        mdb.Commands.put("multline@@env", new dpe(126, 2));
        mdb.Commands.put("gather@@env", new dpe(127, 2));
        mdb.Commands.put("gathered@@env", new dpe(128, 2));
        mdb.Commands.put("shoveright", new dpe(129, 1));
        mdb.Commands.put("shoveleft", new dpe(130, 1));
        mdb.Commands.put("\\", new dpe(131, 0));
        mdb.Commands.put("newenvironment", new dpe(132, 3));
        mdb.Commands.put("renewenvironment", new dpe(133, 3));
        mdb.Commands.put("makeatletter", new dpe(134, 0));
        mdb.Commands.put("makeatother", new dpe(135, 0));
        mdb.Commands.put("fbox", new dpe(136, 1));
        mdb.Commands.put("boxed", new dpe(137, 1));
        mdb.Commands.put("stackrel", new dpe(ATDataProfile.CMD_BLOOD_OXYGEN_RECORD, 2, 1));
        mdb.Commands.put("stackbin", new dpe(139, 2, 1));
        mdb.Commands.put("accentset", new dpe(140, 2));
        mdb.Commands.put("underaccent", new dpe(141, 2));
        mdb.Commands.put("undertilde", new dpe(142, 1));
        mdb.Commands.put("overset", new dpe(143, 2));
        mdb.Commands.put("Braket", new dpe(144, 1));
        mdb.Commands.put("Set", new dpe(145, 1));
        mdb.Commands.put("underset", new dpe(146, 2));
        mdb.Commands.put("boldsymbol", new dpe(147, 1));
        mdb.Commands.put("LaTeX", new dpe(148, 0));
        mdb.Commands.put("GeoGebra", new dpe(149, 0));
        mdb.Commands.put("big", new dpe(150, 1));
        mdb.Commands.put("Big", new dpe(151, 1));
        mdb.Commands.put("bigg", new dpe(152, 1));
        mdb.Commands.put("Bigg", new dpe(153, 1));
        mdb.Commands.put("bigl", new dpe(154, 1));
        mdb.Commands.put("Bigl", new dpe(com.garmin.fit.i.O2ToxicityFieldNum, 1));
        mdb.Commands.put("biggl", new dpe(156, 1));
        mdb.Commands.put("Biggl", new dpe(com.garmin.fit.e.TotalFractionalDescentFieldNum, 1));
        mdb.Commands.put("bigr", new dpe(158, 1));
        mdb.Commands.put("Bigr", new dpe(159, 1));
        mdb.Commands.put("biggr", new dpe(160, 1));
        mdb.Commands.put("Biggr", new dpe(161, 1));
        mdb.Commands.put("displaystyle", new dpe(162, 0));
        mdb.Commands.put("textstyle", new dpe(163, 0));
        mdb.Commands.put("scriptstyle", new dpe(164, 0));
        mdb.Commands.put("scriptscriptstyle", new dpe(165, 0));
        mdb.Commands.put("sideset", new dpe(166, 3));
        mdb.Commands.put("prescript", new dpe(167, 3));
        mdb.Commands.put("rotatebox", new dpe(168, 2, 1));
        mdb.Commands.put("reflectbox", new dpe(169, 1));
        mdb.Commands.put("scalebox", new dpe(170, 2, 2));
        mdb.Commands.put("resizebox", new dpe(171, 3));
        mdb.Commands.put("raisebox", new dpe(172, 2, 2));
        mdb.Commands.put("shadowbox", new dpe(173, 1));
        mdb.Commands.put("ovalbox", new dpe(174, 1));
        mdb.Commands.put("doublebox", new dpe(175, 1));
        mdb.Commands.put("phantom", new dpe(176, 1));
        mdb.Commands.put("hphantom", new dpe(177, 1));
        mdb.Commands.put("vphantom", new dpe(178, 1));
        mdb.Commands.put("sp@breve", new dpe(179, 0));
        mdb.Commands.put("sp@hat", new dpe(180, 0));
        mdb.Commands.put("definecolor", new dpe(181, 3));
        mdb.Commands.put("textcolor", new dpe(182, 2));
        mdb.Commands.put("fgcolor", new dpe(183, 2));
        mdb.Commands.put(DeepLinkInterpreter.KEY_ACTION_BG_COLOR, new dpe(184, 2));
        mdb.Commands.put("colorbox", new dpe(185, 2));
        mdb.Commands.put("fcolorbox", new dpe(186, 3));
        mdb.Commands.put("c", new dpe(187, 1));
        mdb.Commands.put("IJ", new dpe(188, 0));
        mdb.Commands.put("ij", new dpe(FitnessProto$FitnessCmdId.CMD_MCU_BREATHE_RATE_VALUE, 0));
        mdb.Commands.put("TStroke", new dpe(190, 0));
        mdb.Commands.put("tStroke", new dpe(FitnessProto$FitnessCmdId.CMD_MCU_AUTO_PAUSE_SPORT_VALUE, 0));
        mdb.Commands.put("Lcaron", new dpe(192, 0));
        mdb.Commands.put("tcaron", new dpe(193, 0));
        mdb.Commands.put("lcaron", new dpe(194, 0));
        mdb.Commands.put(MapSchema.FIELD_NAME_KEY, new dpe(195, 1));
        mdb.Commands.put("cong", new dpe(FitnessProto$FitnessCmdId.CMD_MCU_BUTTON_TO_PAUSE_OR_RESUME_VALUE, 0));
        mdb.Commands.put("doteq", new dpe(197, 0));
        mdb.Commands.put("jlmDynamic", new dpe(198, 1, 1));
        mdb.Commands.put("jlmExternalFont", new dpe(199, 1));
        mdb.Commands.put("jlmText", new dpe(200, 1));
        mdb.Commands.put("jlmTextit", new dpe(201, 1));
        mdb.Commands.put("jlmTextbf", new dpe(202, 1));
        mdb.Commands.put("jlmTextitbf", new dpe(203, 1));
        mdb.Commands.put("DeclareMathSizes", new dpe(204, 4));
        mdb.Commands.put("magnification", new dpe(205, 1));
        mdb.Commands.put("hline", new dpe(206, 0));
        mdb.Commands.put("tiny", new dpe(207, 0));
        mdb.Commands.put("scriptsize", new dpe(208, 0));
        mdb.Commands.put("footnotesize", new dpe(209, 0));
        mdb.Commands.put(BatteryView.STYLE_SMALL, new dpe(210, 0));
        mdb.Commands.put("normalsize", new dpe(211, 0));
        mdb.Commands.put("large", new dpe(212, 0));
        mdb.Commands.put("Large", new dpe(213, 0));
        mdb.Commands.put("LARGE", new dpe(214, 0));
        mdb.Commands.put("huge", new dpe(215, 0));
        mdb.Commands.put("Huge", new dpe(216, 0));
        mdb.Commands.put("jlatexmathcumsup", new dpe(217, 1));
        mdb.Commands.put("jlatexmathcumsub", new dpe(218, 1));
        mdb.Commands.put("hstrok", new dpe(219, 0));
        mdb.Commands.put("Hstrok", new dpe(220, 0));
        mdb.Commands.put("dstrok", new dpe(221, 0));
        mdb.Commands.put("Dstrok", new dpe(222, 0));
        mdb.Commands.put("dotminus", new dpe(223, 0));
        mdb.Commands.put("ratio", new dpe(oei.TAI_CHI, 0));
        mdb.Commands.put("smallfrowneq", new dpe(225, 0));
        mdb.Commands.put("geoprop", new dpe(226, 0));
        mdb.Commands.put("minuscolon", new dpe(227, 0));
        mdb.Commands.put("minuscoloncolon", new dpe(228, 0));
        mdb.Commands.put("simcolon", new dpe(229, 0));
        mdb.Commands.put("simcoloncolon", new dpe(230, 0));
        mdb.Commands.put("approxcolon", new dpe(yo3.FILE_SEND_FAIL, 0));
        mdb.Commands.put("approxcoloncolon", new dpe(232, 0));
        mdb.Commands.put("coloncolon", new dpe(233, 0));
        mdb.Commands.put("equalscolon", new dpe(234, 0));
        mdb.Commands.put("equalscoloncolon", new dpe(235, 0));
        mdb.Commands.put("colonminus", new dpe(FitnessProto$FitnessCmdId.CMD_SUNLIGHT_DETAIL_VALUE, 0));
        mdb.Commands.put("coloncolonminus", new dpe(FitnessProto$FitnessCmdId.CMD_SUNLIGHT_STAT_VALUE, 0));
        mdb.Commands.put("colonequals", new dpe(238, 0));
        mdb.Commands.put("coloncolonequals", new dpe(239, 0));
        mdb.Commands.put("colonsim", new dpe(240, 0));
        mdb.Commands.put("coloncolonsim", new dpe(241, 0));
        mdb.Commands.put("colonapprox", new dpe(242, 0));
        mdb.Commands.put("coloncolonapprox", new dpe(243, 0));
        mdb.Commands.put("kern", new dpe(Proto$SyncEventMessage.OUTFIT_WF_VERSION_FIELD_NUMBER, 1));
        mdb.Commands.put("char", new dpe(UserInfoProto$UserInfoCmdId.CID_RECEIVER_USER_INFO_FROM_DEVICE_VALUE, 1));
        mdb.Commands.put("roman", new dpe(246, 1));
        mdb.Commands.put("Roman", new dpe(247, 1));
        mdb.Commands.put("textcircled", new dpe(248, 1));
        mdb.Commands.put("textsc", new dpe(249, 1));
        mdb.Commands.put("sc", new dpe(250, 0));
        mdb.Commands.put(",", new dpe(Proto$SyncEventMessage.VIDEO_WF_VERSION_FIELD_NUMBER, 0));
        mdb.Commands.put(":", new dpe(252, 0));
        mdb.Commands.put(";", new dpe(253, 0));
        mdb.Commands.put("thinspace", new dpe(254, 0));
        mdb.Commands.put("medspace", new dpe(255, 0));
        mdb.Commands.put("thickspace", new dpe(256, 0));
        mdb.Commands.put("!", new dpe(257, 0));
        mdb.Commands.put("negthinspace", new dpe(258, 0));
        mdb.Commands.put("negmedspace", new dpe(259, 0));
        mdb.Commands.put("negthickspace", new dpe(Constants.LINKAGE_SET_ACTIVE, 0));
        mdb.Commands.put("quad", new dpe(Constants.LINKAGE_MANUAL_SET_ACTIVE, 0));
        mdb.Commands.put("surd", new dpe(ixb.DIVE_ALARM, 0));
        mdb.Commands.put("iint", new dpe(263, 0));
        mdb.Commands.put("iiint", new dpe(ixb.EXERCISE_TITLE, 0));
        mdb.Commands.put("iiiint", new dpe(265, 0));
        mdb.Commands.put("idotsint", new dpe(266, 0));
        mdb.Commands.put("int", new dpe(267, 0));
        mdb.Commands.put("oint", new dpe(268, 0));
        mdb.Commands.put("lmoustache", new dpe(ixb.SPO2_DATA, 0));
        mdb.Commands.put("rmoustache", new dpe(270, 0));
        mdb.Commands.put("-", new dpe(271, 0));
        mdb.Commands.put("jlmXML", new dpe(272, 1));
        mdb.Commands.put("above", new dpe(com.heytap.store.base.core.state.Constants.QR_REQUEST_CODE, 0));
        mdb.Commands.put("abovewithdelims", new dpe(274, 2));
        mdb.Commands.put("st", new dpe(ixb.SLEEP_LEVEL, 1));
        mdb.Commands.put("fcscore", new dpe(276, 1));
        mdb.Commands.put("mathnormal", new dpe(277, 1));
        mdb.Commands.put("qquad", new dpe(278, 0));
        mdb.Commands.put("longdiv", new dpe(279, 2));
        mdb.Commands.put("questeq", new dpe(280, 0));
        mdb.Commands.put("bangle", new dpe(281, 0));
        mdb.Commands.put("brace", new dpe(282, 0));
        mdb.Commands.put("brack", new dpe(283, 0));
    }
}
