package com.oplus.aiunit.vision;

/* JADX INFO: loaded from: classes11.dex */
public interface h1e {
    public static final n1 RC2_CBC;
    public static final n1 bagtypes;
    public static final n1 canNotDecryptAny;
    public static final n1 certBag;
    public static final n1 certTypes;
    public static final n1 crlBag;
    public static final n1 crlTypes;
    public static final n1 data;
    public static final n1 des_EDE3_CBC;
    public static final n1 dhKeyAgreement;
    public static final n1 digestAlgorithm;
    public static final n1 digestedData;
    public static final n1 encryptedData;
    public static final n1 encryptionAlgorithm;
    public static final n1 envelopedData;
    public static final n1 id_PBES2;
    public static final n1 id_PBKDF2;
    public static final n1 id_RSAES_OAEP;
    public static final n1 id_RSASSA_PSS;
    public static final n1 id_aa;
    public static final n1 id_aa_asymmDecryptKeyID;
    public static final n1 id_aa_cmsAlgorithmProtect;
    public static final n1 id_aa_commitmentType;
    public static final n1 id_aa_communityIdentifiers;
    public static final n1 id_aa_contentHint;
    public static final n1 id_aa_contentIdentifier;
    public static final n1 id_aa_contentReference;
    public static final n1 id_aa_decryptKeyID;
    public static final n1 id_aa_encrypKeyPref;
    public static final n1 id_aa_ets_archiveTimestamp;
    public static final n1 id_aa_ets_certCRLTimestamp;
    public static final n1 id_aa_ets_certValues;
    public static final n1 id_aa_ets_certificateRefs;
    public static final n1 id_aa_ets_commitmentType;
    public static final n1 id_aa_ets_contentTimestamp;
    public static final n1 id_aa_ets_escTimeStamp;
    public static final n1 id_aa_ets_otherSigCert;
    public static final n1 id_aa_ets_revocationRefs;
    public static final n1 id_aa_ets_revocationValues;
    public static final n1 id_aa_ets_sigPolicyId;
    public static final n1 id_aa_ets_signerAttr;
    public static final n1 id_aa_ets_signerLocation;
    public static final n1 id_aa_implCompressAlgs;
    public static final n1 id_aa_implCryptoAlgs;
    public static final n1 id_aa_msgSigDigest;
    public static final n1 id_aa_otherSigCert;
    public static final n1 id_aa_receiptRequest;
    public static final n1 id_aa_sigPolicyId;
    public static final n1 id_aa_signatureTimeStampToken;
    public static final n1 id_aa_signerLocation;
    public static final n1 id_aa_signingCertificate;
    public static final n1 id_aa_signingCertificateV2;
    public static final n1 id_alg;
    public static final n1 id_alg_CMS3DESwrap;
    public static final n1 id_alg_CMSRC2wrap;
    public static final n1 id_alg_ESDH;
    public static final n1 id_alg_PWRI_KEK;
    public static final n1 id_alg_SSDH;
    public static final n1 id_ct;
    public static final n1 id_ct_TSTInfo;
    public static final n1 id_ct_authData;
    public static final n1 id_ct_authEnvelopedData;
    public static final n1 id_ct_compressedData;
    public static final n1 id_ct_timestampedData;
    public static final n1 id_cti;
    public static final n1 id_cti_ets_proofOfApproval;
    public static final n1 id_cti_ets_proofOfCreation;
    public static final n1 id_cti_ets_proofOfDelivery;
    public static final n1 id_cti_ets_proofOfOrigin;
    public static final n1 id_cti_ets_proofOfReceipt;
    public static final n1 id_cti_ets_proofOfSender;
    public static final n1 id_hmacWithSHA1;
    public static final n1 id_hmacWithSHA224;
    public static final n1 id_hmacWithSHA256;
    public static final n1 id_hmacWithSHA384;
    public static final n1 id_hmacWithSHA512;
    public static final n1 id_mgf1;
    public static final n1 id_pSpecified;
    public static final n1 id_rsa_KEM;
    public static final n1 id_smime;
    public static final String id_spq = "1.2.840.113549.1.9.16.5";
    public static final n1 id_spq_ets_unotice;
    public static final n1 id_spq_ets_uri;
    public static final n1 keyBag;
    public static final n1 md2;
    public static final n1 md2WithRSAEncryption;
    public static final n1 md4;
    public static final n1 md4WithRSAEncryption;
    public static final n1 md5;
    public static final n1 md5WithRSAEncryption;
    public static final n1 pbeWithMD2AndDES_CBC;
    public static final n1 pbeWithMD2AndRC2_CBC;
    public static final n1 pbeWithMD5AndDES_CBC;
    public static final n1 pbeWithMD5AndRC2_CBC;
    public static final n1 pbeWithSHA1AndDES_CBC;
    public static final n1 pbeWithSHA1AndRC2_CBC;
    public static final n1 pbeWithSHAAnd128BitRC2_CBC;
    public static final n1 pbeWithSHAAnd128BitRC4;
    public static final n1 pbeWithSHAAnd2_KeyTripleDES_CBC;
    public static final n1 pbeWithSHAAnd3_KeyTripleDES_CBC;
    public static final n1 pbeWithSHAAnd40BitRC2_CBC;
    public static final n1 pbeWithSHAAnd40BitRC4;
    public static final n1 pbewithSHAAnd40BitRC2_CBC;
    public static final n1 pkcs8ShroudedKeyBag;
    public static final n1 pkcs_1;
    public static final n1 pkcs_12;
    public static final n1 pkcs_12PbeIds;
    public static final n1 pkcs_3;
    public static final n1 pkcs_5;
    public static final n1 pkcs_7;
    public static final n1 pkcs_9;
    public static final n1 pkcs_9_at_challengePassword;
    public static final n1 pkcs_9_at_contentType;
    public static final n1 pkcs_9_at_counterSignature;
    public static final n1 pkcs_9_at_emailAddress;
    public static final n1 pkcs_9_at_extendedCertificateAttributes;
    public static final n1 pkcs_9_at_extensionRequest;
    public static final n1 pkcs_9_at_friendlyName;
    public static final n1 pkcs_9_at_localKeyId;
    public static final n1 pkcs_9_at_messageDigest;
    public static final n1 pkcs_9_at_signingDescription;
    public static final n1 pkcs_9_at_signingTime;
    public static final n1 pkcs_9_at_smimeCapabilities;
    public static final n1 pkcs_9_at_unstructuredAddress;
    public static final n1 pkcs_9_at_unstructuredName;
    public static final n1 preferSignedData;
    public static final n1 rc4;
    public static final n1 rsaEncryption;
    public static final n1 sMIMECapabilitiesVersions;
    public static final n1 safeContentsBag;
    public static final n1 sdsiCertificate;
    public static final n1 secretBag;
    public static final n1 sha1WithRSAEncryption;
    public static final n1 sha224WithRSAEncryption;
    public static final n1 sha256WithRSAEncryption;
    public static final n1 sha384WithRSAEncryption;
    public static final n1 sha512WithRSAEncryption;
    public static final n1 sha512_224WithRSAEncryption;
    public static final n1 sha512_256WithRSAEncryption;
    public static final n1 signedAndEnvelopedData;
    public static final n1 signedData;
    public static final n1 srsaOAEPEncryptionSET;
    public static final n1 x509Certificate;
    public static final n1 x509Crl;
    public static final n1 x509certType;

    static {
        n1 n1Var = new n1("1.2.840.113549.1.1");
        pkcs_1 = n1Var;
        rsaEncryption = n1Var.m("1");
        md2WithRSAEncryption = n1Var.m("2");
        md4WithRSAEncryption = n1Var.m("3");
        md5WithRSAEncryption = n1Var.m("4");
        sha1WithRSAEncryption = n1Var.m("5");
        srsaOAEPEncryptionSET = n1Var.m("6");
        id_RSAES_OAEP = n1Var.m("7");
        id_mgf1 = n1Var.m(s04.VIA_SHARE_TYPE_PUBLISHVIDEO);
        id_pSpecified = n1Var.m("9");
        id_RSASSA_PSS = n1Var.m("10");
        sha256WithRSAEncryption = n1Var.m("11");
        sha384WithRSAEncryption = n1Var.m("12");
        sha512WithRSAEncryption = n1Var.m("13");
        sha224WithRSAEncryption = n1Var.m("14");
        sha512_224WithRSAEncryption = n1Var.m("15");
        sha512_256WithRSAEncryption = n1Var.m(s04.VIA_REPORT_TYPE_START_WAP);
        n1 n1Var2 = new n1("1.2.840.113549.1.3");
        pkcs_3 = n1Var2;
        dhKeyAgreement = n1Var2.m("1");
        n1 n1Var3 = new n1("1.2.840.113549.1.5");
        pkcs_5 = n1Var3;
        pbeWithMD2AndDES_CBC = n1Var3.m("1");
        pbeWithMD2AndRC2_CBC = n1Var3.m("4");
        pbeWithMD5AndDES_CBC = n1Var3.m("3");
        pbeWithMD5AndRC2_CBC = n1Var3.m("6");
        pbeWithSHA1AndDES_CBC = n1Var3.m("10");
        pbeWithSHA1AndRC2_CBC = n1Var3.m("11");
        id_PBES2 = n1Var3.m("13");
        id_PBKDF2 = n1Var3.m("12");
        n1 n1Var4 = new n1("1.2.840.113549.3");
        encryptionAlgorithm = n1Var4;
        des_EDE3_CBC = n1Var4.m("7");
        RC2_CBC = n1Var4.m("2");
        rc4 = n1Var4.m("4");
        n1 n1Var5 = new n1("1.2.840.113549.2");
        digestAlgorithm = n1Var5;
        md2 = n1Var5.m("2");
        md4 = n1Var5.m("4");
        md5 = n1Var5.m("5");
        id_hmacWithSHA1 = n1Var5.m("7").t();
        id_hmacWithSHA224 = n1Var5.m(s04.VIA_SHARE_TYPE_PUBLISHVIDEO).t();
        id_hmacWithSHA256 = n1Var5.m("9").t();
        id_hmacWithSHA384 = n1Var5.m("10").t();
        id_hmacWithSHA512 = n1Var5.m("11").t();
        pkcs_7 = new n1("1.2.840.113549.1.7").t();
        data = new n1("1.2.840.113549.1.7.1").t();
        signedData = new n1("1.2.840.113549.1.7.2").t();
        envelopedData = new n1("1.2.840.113549.1.7.3").t();
        signedAndEnvelopedData = new n1("1.2.840.113549.1.7.4").t();
        digestedData = new n1("1.2.840.113549.1.7.5").t();
        encryptedData = new n1("1.2.840.113549.1.7.6").t();
        n1 n1Var6 = new n1("1.2.840.113549.1.9");
        pkcs_9 = n1Var6;
        pkcs_9_at_emailAddress = n1Var6.m("1").t();
        pkcs_9_at_unstructuredName = n1Var6.m("2").t();
        pkcs_9_at_contentType = n1Var6.m("3").t();
        pkcs_9_at_messageDigest = n1Var6.m("4").t();
        pkcs_9_at_signingTime = n1Var6.m("5").t();
        pkcs_9_at_counterSignature = n1Var6.m("6").t();
        pkcs_9_at_challengePassword = n1Var6.m("7").t();
        pkcs_9_at_unstructuredAddress = n1Var6.m(s04.VIA_SHARE_TYPE_PUBLISHVIDEO).t();
        pkcs_9_at_extendedCertificateAttributes = n1Var6.m("9").t();
        pkcs_9_at_signingDescription = n1Var6.m("13").t();
        pkcs_9_at_extensionRequest = n1Var6.m("14").t();
        pkcs_9_at_smimeCapabilities = n1Var6.m("15").t();
        n1 n1VarT = n1Var6.m(s04.VIA_REPORT_TYPE_START_WAP).t();
        id_smime = n1VarT;
        pkcs_9_at_friendlyName = n1Var6.m("20").t();
        pkcs_9_at_localKeyId = n1Var6.m(s04.VIA_REPORT_TYPE_QQFAVORITES).t();
        x509certType = n1Var6.m("22.1");
        n1 n1VarM = n1Var6.m(s04.VIA_REPORT_TYPE_DATALINE);
        certTypes = n1VarM;
        x509Certificate = n1VarM.m("1").t();
        sdsiCertificate = n1VarM.m("2").t();
        n1 n1VarM2 = n1Var6.m(s04.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        crlTypes = n1VarM2;
        x509Crl = n1VarM2.m("1").t();
        id_aa_cmsAlgorithmProtect = n1Var6.m(j70.RUNNING_COURSE_SWITCH).t();
        preferSignedData = n1Var6.m("15.1");
        canNotDecryptAny = n1Var6.m("15.2");
        sMIMECapabilitiesVersions = n1Var6.m("15.3");
        n1 n1Var7 = new n1("1.2.840.113549.1.9.16.1");
        id_ct = n1Var7;
        id_ct_authData = n1Var7.m("2");
        id_ct_TSTInfo = n1Var7.m("4");
        id_ct_compressedData = n1Var7.m("9");
        id_ct_authEnvelopedData = n1Var7.m(s04.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        id_ct_timestampedData = n1Var7.m(j70.KEEP_TAB_SWITCH);
        n1 n1VarM3 = n1VarT.m("3");
        id_alg = n1VarM3;
        id_alg_PWRI_KEK = n1VarM3.m("9");
        id_rsa_KEM = n1VarM3.m("14");
        n1 n1Var8 = new n1("1.2.840.113549.1.9.16.6");
        id_cti = n1Var8;
        id_cti_ets_proofOfOrigin = n1Var8.m("1");
        id_cti_ets_proofOfReceipt = n1Var8.m("2");
        id_cti_ets_proofOfDelivery = n1Var8.m("3");
        id_cti_ets_proofOfSender = n1Var8.m("4");
        id_cti_ets_proofOfApproval = n1Var8.m("5");
        id_cti_ets_proofOfCreation = n1Var8.m("6");
        n1 n1Var9 = new n1("1.2.840.113549.1.9.16.2");
        id_aa = n1Var9;
        id_aa_receiptRequest = n1Var9.m("1");
        id_aa_contentHint = n1Var9.m("4");
        id_aa_msgSigDigest = n1Var9.m("5");
        id_aa_contentReference = n1Var9.m("10");
        id_aa_encrypKeyPref = n1Var9.m("11");
        id_aa_signingCertificate = n1Var9.m("12");
        id_aa_signingCertificateV2 = n1Var9.m("47");
        id_aa_contentIdentifier = n1Var9.m("7");
        id_aa_signatureTimeStampToken = n1Var9.m("14");
        n1 n1VarM4 = n1Var9.m("15");
        id_aa_ets_sigPolicyId = n1VarM4;
        n1 n1VarM5 = n1Var9.m(s04.VIA_REPORT_TYPE_START_WAP);
        id_aa_ets_commitmentType = n1VarM5;
        n1 n1VarM6 = n1Var9.m("17");
        id_aa_ets_signerLocation = n1VarM6;
        id_aa_ets_signerAttr = n1Var9.m("18");
        n1 n1VarM7 = n1Var9.m("19");
        id_aa_ets_otherSigCert = n1VarM7;
        id_aa_ets_contentTimestamp = n1Var9.m("20");
        id_aa_ets_certificateRefs = n1Var9.m(s04.VIA_REPORT_TYPE_QQFAVORITES);
        id_aa_ets_revocationRefs = n1Var9.m(s04.VIA_REPORT_TYPE_DATALINE);
        id_aa_ets_certValues = n1Var9.m(s04.VIA_REPORT_TYPE_SHARE_TO_TROOPBAR);
        id_aa_ets_revocationValues = n1Var9.m("24");
        id_aa_ets_escTimeStamp = n1Var9.m(s04.VIA_REPORT_TYPE_CHAT_AUDIO);
        id_aa_ets_certCRLTimestamp = n1Var9.m(s04.VIA_REPORT_TYPE_CHAT_VIDEO);
        id_aa_ets_archiveTimestamp = n1Var9.m("27");
        id_aa_decryptKeyID = n1Var9.m("37");
        id_aa_implCryptoAlgs = n1Var9.m("38");
        id_aa_asymmDecryptKeyID = n1Var9.m("54");
        id_aa_implCompressAlgs = n1Var9.m(j70.COACH_INFO);
        id_aa_communityIdentifiers = n1Var9.m("40");
        id_aa_sigPolicyId = n1VarM4;
        id_aa_commitmentType = n1VarM5;
        id_aa_signerLocation = n1VarM6;
        id_aa_otherSigCert = n1VarM7;
        id_spq_ets_uri = new n1("1.2.840.113549.1.9.16.5.1");
        id_spq_ets_unotice = new n1("1.2.840.113549.1.9.16.5.2");
        n1 n1Var10 = new n1("1.2.840.113549.1.12");
        pkcs_12 = n1Var10;
        n1 n1VarM8 = n1Var10.m("10.1");
        bagtypes = n1VarM8;
        keyBag = n1VarM8.m("1");
        pkcs8ShroudedKeyBag = n1VarM8.m("2");
        certBag = n1VarM8.m("3");
        crlBag = n1VarM8.m("4");
        secretBag = n1VarM8.m("5");
        safeContentsBag = n1VarM8.m("6");
        n1 n1VarM9 = n1Var10.m("1");
        pkcs_12PbeIds = n1VarM9;
        pbeWithSHAAnd128BitRC4 = n1VarM9.m("1");
        pbeWithSHAAnd40BitRC4 = n1VarM9.m("2");
        pbeWithSHAAnd3_KeyTripleDES_CBC = n1VarM9.m("3");
        pbeWithSHAAnd2_KeyTripleDES_CBC = n1VarM9.m("4");
        pbeWithSHAAnd128BitRC2_CBC = n1VarM9.m("5");
        pbeWithSHAAnd40BitRC2_CBC = n1VarM9.m("6");
        pbewithSHAAnd40BitRC2_CBC = n1VarM9.m("6");
        id_alg_CMS3DESwrap = new n1("1.2.840.113549.1.9.16.3.6");
        id_alg_CMSRC2wrap = new n1("1.2.840.113549.1.9.16.3.7");
        id_alg_ESDH = new n1("1.2.840.113549.1.9.16.3.5");
        id_alg_SSDH = new n1("1.2.840.113549.1.9.16.3.10");
    }
}
