package com.oplus.aiunit.vision;

import com.garmin.fit.Fit;
import com.heytap.databaseengine.apiv2.health.HeytapHealthParams;
import java.util.HashMap;
import java.util.Map;

/* JADX INFO: loaded from: classes13.dex */
public class ixb {
    public static final int AAD_ACCEL_FEATURES = 289;
    public static final int ACCELEROMETER_DATA = 165;
    public static final int ACTIVITY = 34;
    public static final int ANT_CHANNEL_ID = 82;
    public static final int ANT_RX = 80;
    public static final int ANT_TX = 81;
    public static final int AVIATION_ATTITUDE = 178;
    public static final int BAROMETER_DATA = 209;
    public static final int BEAT_INTERVALS = 290;
    public static final int BIKE_PROFILE = 6;
    public static final int BLOOD_PRESSURE = 51;
    public static final int CADENCE_ZONE = 131;
    public static final int CAMERA_EVENT = 161;
    public static final int CAPABILITIES = 1;
    public static final int CHRONO_SHOT_DATA = 388;
    public static final int CHRONO_SHOT_SESSION = 387;
    public static final int CLIMB_PRO = 317;
    public static final int CONNECTIVITY = 127;
    public static final int COURSE = 31;
    public static final int COURSE_POINT = 32;
    public static final int DEVELOPER_DATA_ID = 207;
    public static final int DEVICE_AUX_BATTERY_INFO = 375;
    public static final int DEVICE_INFO = 23;
    public static final int DEVICE_SETTINGS = 2;
    public static final int DIVE_ALARM = 262;
    public static final int DIVE_APNEA_ALARM = 393;
    public static final int DIVE_GAS = 259;
    public static final int DIVE_SETTINGS = 258;
    public static final int DIVE_SUMMARY = 268;
    public static final int EVENT = 21;
    public static final int EXD_DATA_CONCEPT_CONFIGURATION = 202;
    public static final int EXD_DATA_FIELD_CONFIGURATION = 201;
    public static final int EXD_SCREEN_CONFIGURATION = 200;
    public static final int EXERCISE_TITLE = 264;
    public static final int FIELD_CAPABILITIES = 39;
    public static final int FIELD_DESCRIPTION = 206;
    public static final int FILE_CAPABILITIES = 37;
    public static final int FILE_CREATOR = 49;
    public static final int FILE_ID = 0;
    public static final int GOAL = 15;
    public static final int GPS_METADATA = 160;
    public static final int GYROSCOPE_DATA = 164;
    public static final int HR = 132;
    public static final int HRM_PROFILE = 4;
    public static final int HRV = 78;
    public static final int HRV_STATUS_SUMMARY = 370;
    public static final int HRV_VALUE = 371;
    public static final int HR_ZONE = 8;
    public static final int HSA_ACCELEROMETER_DATA = 302;
    public static final int HSA_BODY_BATTERY_DATA = 314;
    public static final int HSA_CONFIGURATION_DATA = 389;
    public static final int HSA_EVENT = 315;
    public static final int HSA_GYROSCOPE_DATA = 376;
    public static final int HSA_HEART_RATE_DATA = 308;
    public static final int HSA_RESPIRATION_DATA = 307;
    public static final int HSA_SPO2_DATA = 305;
    public static final int HSA_STEP_DATA = 304;
    public static final int HSA_STRESS_DATA = 306;
    public static final int HSA_WRIST_TEMPERATURE_DATA = 409;
    public static final int INVALID = Fit.UINT16_INVALID.intValue();
    public static final int JUMP = 285;
    public static final int LAP = 19;
    public static final int LENGTH = 101;
    public static final int MAGNETOMETER_DATA = 208;
    public static final int MAX_MET_DATA = 229;
    public static final int MEMO_GLOB = 145;
    public static final int MESG_CAPABILITIES = 38;
    public static final int MET_ZONE = 10;
    public static final int MFG_RANGE_MAX = 65534;
    public static final int MFG_RANGE_MIN = 65280;
    public static final int MONITORING = 55;
    public static final int MONITORING_HR_DATA = 211;
    public static final int MONITORING_INFO = 103;
    public static final int NMEA_SENTENCE = 177;
    public static final int OBDII_DATA = 174;
    public static final int OHR_SETTINGS = 188;
    public static final int ONE_D_SENSOR_CALIBRATION = 210;
    public static final int PAD = 105;
    public static final int POWER_ZONE = 9;
    public static final int RAW_BBI = 372;
    public static final int RECORD = 20;
    public static final int RESPIRATION_RATE = 297;
    public static final int SCHEDULE = 28;
    public static final int SDM_PROFILE = 5;
    public static final int SEGMENT_FILE = 151;
    public static final int SEGMENT_ID = 148;
    public static final int SEGMENT_LAP = 142;
    public static final int SEGMENT_LEADERBOARD_ENTRY = 149;
    public static final int SEGMENT_POINT = 150;
    public static final int SESSION = 18;
    public static final int SET = 225;
    public static final int SKIN_TEMP_OVERNIGHT = 398;
    public static final int SLAVE_DEVICE = 106;
    public static final int SLEEP_ASSESSMENT = 346;
    public static final int SLEEP_LEVEL = 275;
    public static final int SOFTWARE = 35;
    public static final int SPEED_ZONE = 53;
    public static final int SPLIT = 312;
    public static final int SPLIT_SUMMARY = 313;
    public static final int SPO2_DATA = 269;
    public static final int SPORT = 12;
    public static final int STRESS_LEVEL = 227;
    public static final int TANK_SUMMARY = 323;
    public static final int TANK_UPDATE = 319;
    public static final int THREE_D_SENSOR_CALIBRATION = 167;
    public static final int TIMESTAMP_CORRELATION = 162;
    public static final int TIME_IN_ZONE = 216;
    public static final int TOTALS = 33;
    public static final int TRAINING_FILE = 72;
    public static final int USER_PROFILE = 3;
    public static final int VIDEO = 184;
    public static final int VIDEO_CLIP = 187;
    public static final int VIDEO_DESCRIPTION = 186;
    public static final int VIDEO_FRAME = 169;
    public static final int VIDEO_TITLE = 185;
    public static final int WATCHFACE_SETTINGS = 159;
    public static final int WEATHER_ALERT = 129;
    public static final int WEATHER_CONDITIONS = 128;
    public static final int WEIGHT_SCALE = 30;
    public static final int WORKOUT = 26;
    public static final int WORKOUT_SESSION = 158;
    public static final int WORKOUT_STEP = 27;
    public static final int ZONES_TARGET = 7;
    public static final Map<Integer, String> a;

    static {
        HashMap map = new HashMap();
        a = map;
        map.put(0, "FILE_ID");
        map.put(1, "CAPABILITIES");
        map.put(2, "DEVICE_SETTINGS");
        map.put(3, "USER_PROFILE");
        map.put(4, "HRM_PROFILE");
        map.put(5, "SDM_PROFILE");
        map.put(6, "BIKE_PROFILE");
        map.put(7, "ZONES_TARGET");
        map.put(8, "HR_ZONE");
        map.put(9, "POWER_ZONE");
        map.put(10, "MET_ZONE");
        map.put(12, HeytapHealthParams.SPORT);
        map.put(15, "GOAL");
        map.put(18, "SESSION");
        map.put(19, "LAP");
        map.put(20, "RECORD");
        map.put(21, "EVENT");
        map.put(23, "DEVICE_INFO");
        map.put(26, "WORKOUT");
        map.put(27, "WORKOUT_STEP");
        map.put(28, "SCHEDULE");
        map.put(30, "WEIGHT_SCALE");
        map.put(31, "COURSE");
        map.put(32, "COURSE_POINT");
        map.put(33, "TOTALS");
        map.put(34, "ACTIVITY");
        map.put(35, "SOFTWARE");
        map.put(37, "FILE_CAPABILITIES");
        map.put(38, "MESG_CAPABILITIES");
        map.put(39, "FIELD_CAPABILITIES");
        map.put(49, "FILE_CREATOR");
        map.put(51, "BLOOD_PRESSURE");
        map.put(53, "SPEED_ZONE");
        map.put(55, "MONITORING");
        map.put(72, "TRAINING_FILE");
        map.put(78, "HRV");
        map.put(80, "ANT_RX");
        map.put(81, "ANT_TX");
        map.put(82, "ANT_CHANNEL_ID");
        map.put(101, "LENGTH");
        map.put(103, "MONITORING_INFO");
        map.put(105, "PAD");
        map.put(106, "SLAVE_DEVICE");
        map.put(127, "CONNECTIVITY");
        map.put(128, "WEATHER_CONDITIONS");
        map.put(129, "WEATHER_ALERT");
        map.put(131, "CADENCE_ZONE");
        map.put(132, "HR");
        map.put(142, "SEGMENT_LAP");
        map.put(145, "MEMO_GLOB");
        map.put(148, "SEGMENT_ID");
        map.put(149, "SEGMENT_LEADERBOARD_ENTRY");
        map.put(150, "SEGMENT_POINT");
        map.put(151, "SEGMENT_FILE");
        map.put(158, "WORKOUT_SESSION");
        map.put(159, "WATCHFACE_SETTINGS");
        map.put(160, "GPS_METADATA");
        map.put(161, "CAMERA_EVENT");
        map.put(162, "TIMESTAMP_CORRELATION");
        map.put(164, "GYROSCOPE_DATA");
        map.put(165, "ACCELEROMETER_DATA");
        map.put(167, "THREE_D_SENSOR_CALIBRATION");
        map.put(169, "VIDEO_FRAME");
        map.put(174, "OBDII_DATA");
        map.put(177, "NMEA_SENTENCE");
        map.put(178, "AVIATION_ATTITUDE");
        map.put(184, "VIDEO");
        map.put(185, "VIDEO_TITLE");
        map.put(186, "VIDEO_DESCRIPTION");
        map.put(187, "VIDEO_CLIP");
        map.put(188, "OHR_SETTINGS");
        map.put(200, "EXD_SCREEN_CONFIGURATION");
        map.put(201, "EXD_DATA_FIELD_CONFIGURATION");
        map.put(202, "EXD_DATA_CONCEPT_CONFIGURATION");
        map.put(206, "FIELD_DESCRIPTION");
        map.put(207, "DEVELOPER_DATA_ID");
        map.put(208, "MAGNETOMETER_DATA");
        map.put(209, "BAROMETER_DATA");
        map.put(210, "ONE_D_SENSOR_CALIBRATION");
        map.put(211, "MONITORING_HR_DATA");
        map.put(216, "TIME_IN_ZONE");
        map.put(225, "SET");
        map.put(227, "STRESS_LEVEL");
        map.put(229, "MAX_MET_DATA");
        map.put(258, "DIVE_SETTINGS");
        map.put(259, "DIVE_GAS");
        map.put(Integer.valueOf(DIVE_ALARM), "DIVE_ALARM");
        map.put(Integer.valueOf(EXERCISE_TITLE), "EXERCISE_TITLE");
        map.put(268, "DIVE_SUMMARY");
        map.put(Integer.valueOf(SPO2_DATA), "SPO2_DATA");
        map.put(Integer.valueOf(SLEEP_LEVEL), "SLEEP_LEVEL");
        map.put(Integer.valueOf(JUMP), "JUMP");
        map.put(Integer.valueOf(AAD_ACCEL_FEATURES), "AAD_ACCEL_FEATURES");
        map.put(290, "BEAT_INTERVALS");
        map.put(Integer.valueOf(RESPIRATION_RATE), "RESPIRATION_RATE");
        map.put(302, "HSA_ACCELEROMETER_DATA");
        map.put(304, "HSA_STEP_DATA");
        map.put(305, "HSA_SPO2_DATA");
        map.put(306, "HSA_STRESS_DATA");
        map.put(307, "HSA_RESPIRATION_DATA");
        map.put(308, "HSA_HEART_RATE_DATA");
        map.put(312, "SPLIT");
        map.put(313, "SPLIT_SUMMARY");
        map.put(314, "HSA_BODY_BATTERY_DATA");
        map.put(315, "HSA_EVENT");
        map.put(317, "CLIMB_PRO");
        map.put(Integer.valueOf(TANK_UPDATE), "TANK_UPDATE");
        map.put(Integer.valueOf(TANK_SUMMARY), "TANK_SUMMARY");
        map.put(Integer.valueOf(SLEEP_ASSESSMENT), "SLEEP_ASSESSMENT");
        map.put(Integer.valueOf(HRV_STATUS_SUMMARY), "HRV_STATUS_SUMMARY");
        map.put(Integer.valueOf(HRV_VALUE), "HRV_VALUE");
        map.put(Integer.valueOf(RAW_BBI), "RAW_BBI");
        map.put(Integer.valueOf(DEVICE_AUX_BATTERY_INFO), "DEVICE_AUX_BATTERY_INFO");
        map.put(Integer.valueOf(HSA_GYROSCOPE_DATA), "HSA_GYROSCOPE_DATA");
        map.put(Integer.valueOf(CHRONO_SHOT_SESSION), "CHRONO_SHOT_SESSION");
        map.put(Integer.valueOf(CHRONO_SHOT_DATA), "CHRONO_SHOT_DATA");
        map.put(Integer.valueOf(HSA_CONFIGURATION_DATA), "HSA_CONFIGURATION_DATA");
        map.put(Integer.valueOf(DIVE_APNEA_ALARM), "DIVE_APNEA_ALARM");
        map.put(Integer.valueOf(SKIN_TEMP_OVERNIGHT), "SKIN_TEMP_OVERNIGHT");
        map.put(409, "HSA_WRIST_TEMPERATURE_DATA");
        map.put(65280, "MFG_RANGE_MIN");
        map.put(65534, "MFG_RANGE_MAX");
    }
}
