package com.oplus.aiunit.vision;

import androidx.exifinterface.media.ExifInterface;
import com.heytap.log.formatter.LogFieldKey;
import com.oplus.deepthinker.sdk.app.aidl.eventfountain.TriggerEvent;
import io.netty.util.internal.StringUtil;
import io.protostuff.MapSchema;
import java.util.Hashtable;

/* JADX INFO: loaded from: classes11.dex */
public class kp0 extends z6 {
    public static final n1 BUSINESS_CATEGORY;
    public static final n1 C;
    public static final n1 CN;
    public static final n1 COUNTRY_OF_CITIZENSHIP;
    public static final n1 COUNTRY_OF_RESIDENCE;
    public static final n1 DATE_OF_BIRTH;
    public static final n1 DC;
    public static final n1 DMD_NAME;
    public static final n1 DN_QUALIFIER;
    public static final n1 E;
    public static final n1 EmailAddress;
    public static final n1 GENDER;
    public static final n1 GENERATION;
    public static final n1 GIVENNAME;
    public static final n1 INITIALS;
    public static final y4m INSTANCE;
    public static final n1 L;
    public static final n1 NAME;
    public static final n1 NAME_AT_BIRTH;
    public static final n1 O;
    public static final n1 ORGANIZATION_IDENTIFIER;
    public static final n1 OU;
    public static final n1 PLACE_OF_BIRTH;
    public static final n1 POSTAL_ADDRESS;
    public static final n1 POSTAL_CODE;
    public static final n1 PSEUDONYM;
    public static final n1 SERIALNUMBER;
    public static final n1 SN;
    public static final n1 ST;
    public static final n1 STREET;
    public static final n1 SURNAME;
    public static final n1 T;
    public static final n1 TELEPHONE_NUMBER;
    public static final n1 UID;
    public static final n1 UNIQUE_IDENTIFIER;
    public static final n1 UnstructuredAddress;
    public static final n1 UnstructuredName;
    public static final Hashtable d;

    /* JADX INFO: renamed from: e, reason: collision with root package name */
    public static final Hashtable f13367e;
    public final Hashtable b = z6.e(d);
    public final Hashtable a = z6.e(f13367e);

    static {
        n1 n1VarT = new n1("2.5.4.6").t();
        C = n1VarT;
        n1 n1VarT2 = new n1("2.5.4.10").t();
        O = n1VarT2;
        n1 n1VarT3 = new n1("2.5.4.11").t();
        OU = n1VarT3;
        n1 n1VarT4 = new n1("2.5.4.12").t();
        T = n1VarT4;
        n1 n1VarT5 = new n1("2.5.4.3").t();
        CN = n1VarT5;
        n1 n1VarT6 = new n1("2.5.4.5").t();
        SN = n1VarT6;
        n1 n1VarT7 = new n1("2.5.4.9").t();
        STREET = n1VarT7;
        SERIALNUMBER = n1VarT6;
        n1 n1VarT8 = new n1("2.5.4.7").t();
        L = n1VarT8;
        n1 n1VarT9 = new n1("2.5.4.8").t();
        ST = n1VarT9;
        n1 n1VarT10 = new n1("2.5.4.4").t();
        SURNAME = n1VarT10;
        n1 n1VarT11 = new n1("2.5.4.42").t();
        GIVENNAME = n1VarT11;
        n1 n1VarT12 = new n1("2.5.4.43").t();
        INITIALS = n1VarT12;
        n1 n1VarT13 = new n1("2.5.4.44").t();
        GENERATION = n1VarT13;
        n1 n1VarT14 = new n1("2.5.4.45").t();
        UNIQUE_IDENTIFIER = n1VarT14;
        n1 n1VarT15 = new n1("2.5.4.15").t();
        BUSINESS_CATEGORY = n1VarT15;
        n1 n1VarT16 = new n1("2.5.4.17").t();
        POSTAL_CODE = n1VarT16;
        n1 n1VarT17 = new n1("2.5.4.46").t();
        DN_QUALIFIER = n1VarT17;
        n1 n1VarT18 = new n1("2.5.4.65").t();
        PSEUDONYM = n1VarT18;
        n1 n1VarT19 = new n1("1.3.6.1.5.5.7.9.1").t();
        DATE_OF_BIRTH = n1VarT19;
        n1 n1VarT20 = new n1("1.3.6.1.5.5.7.9.2").t();
        PLACE_OF_BIRTH = n1VarT20;
        n1 n1VarT21 = new n1("1.3.6.1.5.5.7.9.3").t();
        GENDER = n1VarT21;
        n1 n1VarT22 = new n1("1.3.6.1.5.5.7.9.4").t();
        COUNTRY_OF_CITIZENSHIP = n1VarT22;
        n1 n1VarT23 = new n1("1.3.6.1.5.5.7.9.5").t();
        COUNTRY_OF_RESIDENCE = n1VarT23;
        n1 n1VarT24 = new n1("1.3.36.8.3.14").t();
        NAME_AT_BIRTH = n1VarT24;
        n1 n1VarT25 = new n1("2.5.4.16").t();
        POSTAL_ADDRESS = n1VarT25;
        DMD_NAME = new n1("2.5.4.54").t();
        n1 n1Var = b5m.id_at_telephoneNumber;
        TELEPHONE_NUMBER = n1Var;
        n1 n1Var2 = b5m.id_at_name;
        NAME = n1Var2;
        n1 n1Var3 = b5m.id_at_organizationIdentifier;
        ORGANIZATION_IDENTIFIER = n1Var3;
        n1 n1Var4 = h1e.pkcs_9_at_emailAddress;
        EmailAddress = n1Var4;
        n1 n1Var5 = h1e.pkcs_9_at_unstructuredName;
        UnstructuredName = n1Var5;
        n1 n1Var6 = h1e.pkcs_9_at_unstructuredAddress;
        UnstructuredAddress = n1Var6;
        E = n1Var4;
        n1 n1Var7 = new n1("0.9.2342.19200300.100.1.25");
        DC = n1Var7;
        n1 n1Var8 = new n1("0.9.2342.19200300.100.1.1");
        UID = n1Var8;
        Hashtable hashtable = new Hashtable();
        d = hashtable;
        Hashtable hashtable2 = new Hashtable();
        f13367e = hashtable2;
        hashtable.put(n1VarT, "C");
        hashtable.put(n1VarT2, "O");
        hashtable.put(n1VarT4, ExifInterface.GPS_DIRECTION_TRUE);
        hashtable.put(n1VarT3, "OU");
        hashtable.put(n1VarT5, "CN");
        hashtable.put(n1VarT8, "L");
        hashtable.put(n1VarT9, "ST");
        hashtable.put(n1VarT6, "SERIALNUMBER");
        hashtable.put(n1Var4, ExifInterface.LONGITUDE_EAST);
        hashtable.put(n1Var7, "DC");
        hashtable.put(n1Var8, "UID");
        hashtable.put(n1VarT7, "STREET");
        hashtable.put(n1VarT10, "SURNAME");
        hashtable.put(n1VarT11, "GIVENNAME");
        hashtable.put(n1VarT12, "INITIALS");
        hashtable.put(n1VarT13, "GENERATION");
        hashtable.put(n1Var6, "unstructuredAddress");
        hashtable.put(n1Var5, "unstructuredName");
        hashtable.put(n1VarT14, "UniqueIdentifier");
        hashtable.put(n1VarT17, "DN");
        hashtable.put(n1VarT18, "Pseudonym");
        hashtable.put(n1VarT25, "PostalAddress");
        hashtable.put(n1VarT24, "NameAtBirth");
        hashtable.put(n1VarT22, "CountryOfCitizenship");
        hashtable.put(n1VarT23, "CountryOfResidence");
        hashtable.put(n1VarT21, "Gender");
        hashtable.put(n1VarT20, "PlaceOfBirth");
        hashtable.put(n1VarT19, "DateOfBirth");
        hashtable.put(n1VarT16, "PostalCode");
        hashtable.put(n1VarT15, "BusinessCategory");
        hashtable.put(n1Var, "TelephoneNumber");
        hashtable.put(n1Var2, "Name");
        hashtable.put(n1Var3, "organizationIdentifier");
        hashtable2.put("c", n1VarT);
        hashtable2.put("o", n1VarT2);
        hashtable2.put("t", n1VarT4);
        hashtable2.put("ou", n1VarT3);
        hashtable2.put("cn", n1VarT5);
        hashtable2.put(LogFieldKey.LEVEL_KEY, n1VarT8);
        hashtable2.put("st", n1VarT9);
        hashtable2.put(dj8.KEY_SN, n1VarT6);
        hashtable2.put("serialnumber", n1VarT6);
        hashtable2.put("street", n1VarT7);
        hashtable2.put("emailaddress", n1Var4);
        hashtable2.put("dc", n1Var7);
        hashtable2.put(MapSchema.FIELD_NAME_ENTRY, n1Var4);
        hashtable2.put(TriggerEvent.EXTRA_UID, n1Var8);
        hashtable2.put("surname", n1VarT10);
        hashtable2.put("givenname", n1VarT11);
        hashtable2.put("initials", n1VarT12);
        hashtable2.put("generation", n1VarT13);
        hashtable2.put("unstructuredaddress", n1Var6);
        hashtable2.put("unstructuredname", n1Var5);
        hashtable2.put("uniqueidentifier", n1VarT14);
        hashtable2.put("dn", n1VarT17);
        hashtable2.put("pseudonym", n1VarT18);
        hashtable2.put("postaladdress", n1VarT25);
        hashtable2.put("nameofbirth", n1VarT24);
        hashtable2.put("countryofcitizenship", n1VarT22);
        hashtable2.put("countryofresidence", n1VarT23);
        hashtable2.put("gender", n1VarT21);
        hashtable2.put("placeofbirth", n1VarT20);
        hashtable2.put("dateofbirth", n1VarT19);
        hashtable2.put("postalcode", n1VarT16);
        hashtable2.put("businesscategory", n1VarT15);
        hashtable2.put("telephonenumber", n1Var);
        hashtable2.put("name", n1Var2);
        hashtable2.put("organizationidentifier", n1Var3);
        INSTANCE = new kp0();
    }

    @Override // com.oplus.aiunit.vision.y4m
    public String a(x4m x4mVar) {
        StringBuffer stringBuffer = new StringBuffer();
        boolean z = true;
        for (u8f u8fVar : x4mVar.i()) {
            if (z) {
                z = false;
            } else {
                stringBuffer.append(StringUtil.COMMA);
            }
            up9.a(stringBuffer, u8fVar, this.b);
        }
        return stringBuffer.toString();
    }
}
