package com.oplus.aiunit.vision;

import androidx.autofill.HintConstants;
import com.heytap.log.formatter.LogFieldKey;
import com.oplus.deepthinker.sdk.app.aidl.eventfountain.TriggerEvent;
import com.platform.usercenter.account.mba.MbaConstant;
import io.netty.util.internal.StringUtil;
import java.util.Hashtable;
import org.hapjs.card.api.debug.CardDebugController;

/* JADX INFO: loaded from: classes11.dex */
public class v8f extends z6 {
    public static final y4m INSTANCE;
    public static final n1 businessCategory;

    /* JADX INFO: renamed from: c, reason: collision with root package name */
    public static final n1 f17750c;
    public static final n1 cn;
    public static final Hashtable d;
    public static final n1 dc;
    public static final n1 description;
    public static final n1 destinationIndicator;
    public static final n1 distinguishedName;
    public static final n1 dnQualifier;

    /* JADX INFO: renamed from: e, reason: collision with root package name */
    public static final Hashtable f17751e;
    public static final n1 enhancedSearchGuide;
    public static final n1 facsimileTelephoneNumber;
    public static final n1 generationQualifier;
    public static final n1 givenName;
    public static final n1 houseIdentifier;
    public static final n1 initials;
    public static final n1 internationalISDNNumber;

    /* JADX INFO: renamed from: l, reason: collision with root package name */
    public static final n1 f17752l;
    public static final n1 member;
    public static final n1 name;
    public static final n1 o;
    public static final n1 ou;
    public static final n1 owner;
    public static final n1 physicalDeliveryOfficeName;
    public static final n1 postOfficeBox;
    public static final n1 postalAddress;
    public static final n1 postalCode;
    public static final n1 preferredDeliveryMethod;
    public static final n1 registeredAddress;
    public static final n1 roleOccupant;
    public static final n1 searchGuide;
    public static final n1 seeAlso;
    public static final n1 serialNumber;
    public static final n1 sn;
    public static final n1 st;
    public static final n1 street;
    public static final n1 telephoneNumber;
    public static final n1 teletexTerminalIdentifier;
    public static final n1 telexNumber;
    public static final n1 title;
    public static final n1 uid;
    public static final n1 uniqueMember;
    public static final n1 userPassword;
    public static final n1 x121Address;
    public static final n1 x500UniqueIdentifier;
    public final Hashtable b = z6.e(d);
    public final Hashtable a = z6.e(f17751e);

    static {
        n1 n1VarT = new n1("2.5.4.15").t();
        businessCategory = n1VarT;
        n1 n1VarT2 = new n1("2.5.4.6").t();
        f17750c = n1VarT2;
        n1 n1VarT3 = new n1("2.5.4.3").t();
        cn = n1VarT3;
        n1 n1VarT4 = new n1("0.9.2342.19200300.100.1.25").t();
        dc = n1VarT4;
        n1 n1VarT5 = new n1("2.5.4.13").t();
        description = n1VarT5;
        n1 n1VarT6 = new n1("2.5.4.27").t();
        destinationIndicator = n1VarT6;
        n1 n1VarT7 = new n1("2.5.4.49").t();
        distinguishedName = n1VarT7;
        n1 n1VarT8 = new n1("2.5.4.46").t();
        dnQualifier = n1VarT8;
        n1 n1VarT9 = new n1("2.5.4.47").t();
        enhancedSearchGuide = n1VarT9;
        n1 n1VarT10 = new n1("2.5.4.23").t();
        facsimileTelephoneNumber = n1VarT10;
        n1 n1VarT11 = new n1("2.5.4.44").t();
        generationQualifier = n1VarT11;
        n1 n1VarT12 = new n1("2.5.4.42").t();
        givenName = n1VarT12;
        n1 n1VarT13 = new n1("2.5.4.51").t();
        houseIdentifier = n1VarT13;
        n1 n1VarT14 = new n1("2.5.4.43").t();
        initials = n1VarT14;
        n1 n1VarT15 = new n1("2.5.4.25").t();
        internationalISDNNumber = n1VarT15;
        n1 n1VarT16 = new n1("2.5.4.7").t();
        f17752l = n1VarT16;
        n1 n1VarT17 = new n1("2.5.4.31").t();
        member = n1VarT17;
        n1 n1VarT18 = new n1("2.5.4.41").t();
        name = n1VarT18;
        n1 n1VarT19 = new n1("2.5.4.10").t();
        o = n1VarT19;
        n1 n1VarT20 = new n1("2.5.4.11").t();
        ou = n1VarT20;
        n1 n1VarT21 = new n1("2.5.4.32").t();
        owner = n1VarT21;
        n1 n1VarT22 = new n1("2.5.4.19").t();
        physicalDeliveryOfficeName = n1VarT22;
        n1 n1VarT23 = new n1("2.5.4.16").t();
        postalAddress = n1VarT23;
        n1 n1VarT24 = new n1("2.5.4.17").t();
        postalCode = n1VarT24;
        n1 n1VarT25 = new n1("2.5.4.18").t();
        postOfficeBox = n1VarT25;
        n1 n1VarT26 = new n1("2.5.4.28").t();
        preferredDeliveryMethod = n1VarT26;
        n1 n1VarT27 = new n1("2.5.4.26").t();
        registeredAddress = n1VarT27;
        n1 n1VarT28 = new n1("2.5.4.33").t();
        roleOccupant = n1VarT28;
        n1 n1VarT29 = new n1("2.5.4.14").t();
        searchGuide = n1VarT29;
        n1 n1VarT30 = new n1("2.5.4.34").t();
        seeAlso = n1VarT30;
        n1 n1VarT31 = new n1("2.5.4.5").t();
        serialNumber = n1VarT31;
        n1 n1VarT32 = new n1("2.5.4.4").t();
        sn = n1VarT32;
        n1 n1VarT33 = new n1("2.5.4.8").t();
        st = n1VarT33;
        n1 n1VarT34 = new n1("2.5.4.9").t();
        street = n1VarT34;
        n1 n1VarT35 = new n1("2.5.4.20").t();
        telephoneNumber = n1VarT35;
        n1 n1VarT36 = new n1("2.5.4.22").t();
        teletexTerminalIdentifier = n1VarT36;
        n1 n1VarT37 = new n1("2.5.4.21").t();
        telexNumber = n1VarT37;
        n1 n1VarT38 = new n1("2.5.4.12").t();
        title = n1VarT38;
        n1 n1VarT39 = new n1("0.9.2342.19200300.100.1.1").t();
        uid = n1VarT39;
        n1 n1VarT40 = new n1("2.5.4.50").t();
        uniqueMember = n1VarT40;
        n1 n1VarT41 = new n1("2.5.4.35").t();
        userPassword = n1VarT41;
        n1 n1VarT42 = new n1("2.5.4.24").t();
        x121Address = n1VarT42;
        n1 n1VarT43 = new n1("2.5.4.45").t();
        x500UniqueIdentifier = n1VarT43;
        Hashtable hashtable = new Hashtable();
        d = hashtable;
        Hashtable hashtable2 = new Hashtable();
        f17751e = hashtable2;
        hashtable.put(n1VarT, "businessCategory");
        hashtable.put(n1VarT2, "c");
        hashtable.put(n1VarT3, "cn");
        hashtable.put(n1VarT4, "dc");
        hashtable.put(n1VarT5, iim.a.f);
        hashtable.put(n1VarT6, "destinationIndicator");
        hashtable.put(n1VarT7, "distinguishedName");
        hashtable.put(n1VarT8, "dnQualifier");
        hashtable.put(n1VarT9, "enhancedSearchGuide");
        hashtable.put(n1VarT10, "facsimileTelephoneNumber");
        hashtable.put(n1VarT11, "generationQualifier");
        hashtable.put(n1VarT12, "givenName");
        hashtable.put(n1VarT13, "houseIdentifier");
        hashtable.put(n1VarT14, "initials");
        hashtable.put(n1VarT15, "internationalISDNNumber");
        hashtable.put(n1VarT16, LogFieldKey.LEVEL_KEY);
        hashtable.put(n1VarT17, MbaConstant.RECOVERY_DEFAULT_PKG);
        hashtable.put(n1VarT18, "name");
        hashtable.put(n1VarT19, "o");
        hashtable.put(n1VarT20, "ou");
        hashtable.put(n1VarT21, "owner");
        hashtable.put(n1VarT22, "physicalDeliveryOfficeName");
        hashtable.put(n1VarT23, HintConstants.AUTOFILL_HINT_POSTAL_ADDRESS);
        hashtable.put(n1VarT24, HintConstants.AUTOFILL_HINT_POSTAL_CODE);
        hashtable.put(n1VarT25, "postOfficeBox");
        hashtable.put(n1VarT26, "preferredDeliveryMethod");
        hashtable.put(n1VarT27, "registeredAddress");
        hashtable.put(n1VarT28, "roleOccupant");
        hashtable.put(n1VarT29, "searchGuide");
        hashtable.put(n1VarT30, "seeAlso");
        hashtable.put(n1VarT31, CardDebugController.EXTRA_SERIAL_NUMBER);
        hashtable.put(n1VarT32, dj8.KEY_SN);
        hashtable.put(n1VarT33, "st");
        hashtable.put(n1VarT34, "street");
        hashtable.put(n1VarT35, "telephoneNumber");
        hashtable.put(n1VarT36, "teletexTerminalIdentifier");
        hashtable.put(n1VarT37, "telexNumber");
        hashtable.put(n1VarT38, "title");
        hashtable.put(n1VarT39, TriggerEvent.EXTRA_UID);
        hashtable.put(n1VarT40, "uniqueMember");
        hashtable.put(n1VarT41, "userPassword");
        hashtable.put(n1VarT42, "x121Address");
        hashtable.put(n1VarT43, "x500UniqueIdentifier");
        hashtable2.put("businesscategory", n1VarT);
        hashtable2.put("c", n1VarT2);
        hashtable2.put("cn", n1VarT3);
        hashtable2.put("dc", n1VarT4);
        hashtable2.put(iim.a.f, n1VarT5);
        hashtable2.put("destinationindicator", n1VarT6);
        hashtable2.put("distinguishedname", n1VarT7);
        hashtable2.put("dnqualifier", n1VarT8);
        hashtable2.put("enhancedsearchguide", n1VarT9);
        hashtable2.put("facsimiletelephonenumber", n1VarT10);
        hashtable2.put("generationqualifier", n1VarT11);
        hashtable2.put("givenname", n1VarT12);
        hashtable2.put("houseidentifier", n1VarT13);
        hashtable2.put("initials", n1VarT14);
        hashtable2.put("internationalisdnnumber", n1VarT15);
        hashtable2.put(LogFieldKey.LEVEL_KEY, n1VarT16);
        hashtable2.put(MbaConstant.RECOVERY_DEFAULT_PKG, n1VarT17);
        hashtable2.put("name", n1VarT18);
        hashtable2.put("o", n1VarT19);
        hashtable2.put("ou", n1VarT20);
        hashtable2.put("owner", n1VarT21);
        hashtable2.put("physicaldeliveryofficename", n1VarT22);
        hashtable2.put("postaladdress", n1VarT23);
        hashtable2.put("postalcode", n1VarT24);
        hashtable2.put("postofficebox", n1VarT25);
        hashtable2.put("preferreddeliverymethod", n1VarT26);
        hashtable2.put("registeredaddress", n1VarT27);
        hashtable2.put("roleoccupant", n1VarT28);
        hashtable2.put("searchguide", n1VarT29);
        hashtable2.put("seealso", n1VarT30);
        hashtable2.put("serialnumber", n1VarT31);
        hashtable2.put(dj8.KEY_SN, n1VarT32);
        hashtable2.put("st", n1VarT33);
        hashtable2.put("street", n1VarT34);
        hashtable2.put("telephonenumber", n1VarT35);
        hashtable2.put("teletexterminalidentifier", n1VarT36);
        hashtable2.put("telexnumber", n1VarT37);
        hashtable2.put("title", n1VarT38);
        hashtable2.put(TriggerEvent.EXTRA_UID, n1VarT39);
        hashtable2.put("uniquemember", n1VarT40);
        hashtable2.put("userpassword", n1VarT41);
        hashtable2.put("x121address", n1VarT42);
        hashtable2.put("x500uniqueidentifier", n1VarT43);
        INSTANCE = new v8f();
    }

    @Override // com.oplus.aiunit.vision.y4m
    public String a(x4m x4mVar) {
        StringBuffer stringBuffer = new StringBuffer();
        u8f[] u8fVarArrI = x4mVar.i();
        boolean z = true;
        for (int length = u8fVarArrI.length - 1; length >= 0; length--) {
            if (z) {
                z = false;
            } else {
                stringBuffer.append(StringUtil.COMMA);
            }
            up9.a(stringBuffer, u8fVarArrI[length], this.b);
        }
        return stringBuffer.toString();
    }
}
