package com.alibaba.android.arouter.routes;

import com.alibaba.android.arouter.facade.enums.RouteType;
import com.alibaba.android.arouter.facade.model.RouteMeta;
import com.alibaba.android.arouter.facade.template.IRouteGroup;
import com.heytap.health.watchface.WatchFaceApi;
import com.heytap.health.watchface.adaptation.colorconnect.client.MessageReceiveClient;
import com.heytap.health.watchface.adaptation.colorconnect.client.TransportReceiveClient;
import com.heytap.health.watchface.business.creation.category.album.AlbumEditActivity;
import com.heytap.health.watchface.business.creation.category.album.AlbumHomeActivity;
import com.heytap.health.watchface.business.creation.category.classic.ClassicCustomActivity;
import com.heytap.health.watchface.business.creation.category.classic.ClassicSeriesActivity;
import com.heytap.health.watchface.business.creation.category.flexible.DofHomeActivity;
import com.heytap.health.watchface.business.creation.category.flexible.DofTemplateActivity;
import com.heytap.health.watchface.business.creation.category.flexible.FlexibleHomeActivity;
import com.heytap.health.watchface.business.creation.category.flexible.FlexibleManagerActivity;
import com.heytap.health.watchface.business.creation.category.livephoto.LivePhotoHomeActivity;
import com.heytap.health.watchface.business.creation.category.livephoto.LivePhotoStartActivity;
import com.heytap.health.watchface.business.creation.category.omoji.OmojiCustomActivity;
import com.heytap.health.watchface.business.creation.category.omoji.OmojiEditActivity;
import com.heytap.health.watchface.business.creation.category.outfits.OutfitEditActivity;
import com.heytap.health.watchface.business.creation.category.outfits.OutfitsCameraActivity;
import com.heytap.health.watchface.business.creation.category.paint.PaintCreationActivity;
import com.heytap.health.watchface.business.creation.category.video.VideoCustomActivity;
import com.heytap.health.watchface.business.creation.category.wallpaper.WallpaperCustomActivity;
import com.heytap.health.watchface.business.legacy.creation.album.helper.CommunityImagePickerServiceImpl;
import com.heytap.health.watchface.business.legacy.creation.outfits.OutfitsWatchFaceCustomCameraActivity;
import com.heytap.health.watchface.business.legacy.find.FindActivity;
import com.heytap.health.watchface.business.legacy.main.EditWatchFacesActivity;
import com.heytap.health.watchface.business.legacy.main.WatchFaceOverViewActivity;
import com.heytap.health.watchface.business.legacy.online.WatchFaceOnlineActivity;
import com.heytap.health.watchface.business.manager.EditWatchFace2Activity;
import com.heytap.health.watchface.business.manager.StyleChangeActivity;
import com.heytap.health.watchface.business.manager.WatchFaceCenterActivity;
import com.heytap.health.watchface.business.manager.WatchFaceHomeActivity;
import com.heytap.health.watchface.business.manager.WfSearchActivity;
import com.heytap.health.watchface.business.mine.BuyListActivity;
import com.heytap.health.watchface.business.mine.CouponListActivity;
import com.heytap.health.watchface.business.mine.WatchFaceMyActivity;
import com.heytap.health.watchface.business.store.WatchFaceStoreDetailActivity;
import com.heytap.health.watchface.business.store.WatchFaceStoreHomeActivity;
import com.heytap.health.watchface.business.store.router.breeno.BreenoRouterActivity;
import com.heytap.health.watchface.business.store.router.integrate.InternalRouteActivity;
import com.heytap.health.watchface.business.store.router.push.PushNewWatchFaceActivity;
import com.heytap.health.watchface.business.store.router.themestore.ThemeStoreRouterActivity;
import com.heytap.health.watchface.provider.home.WatchFacePreviewService;
import com.heytap.store.platform.htrouter.compiler.utils.Consts;
import java.util.Map;
import org.jetbrains.annotations.Nullable;
import p010kotlin.Metadata;
import p010kotlin.jvm.internal.Intrinsics;

/* JADX INFO: loaded from: classes12.dex */
@Metadata(d1 = {"\u0000\u001e\n\u0000\n\u0002\u0018\u0002\n\u0002\b\u0002\n\u0002\u0010\u0002\n\u0000\n\u0002\u0010%\n\u0002\u0010\u000e\n\u0002\u0018\u0002\n\u0000\u0018\u00002\u00020\u0001B\u0005¢\u0006\u0002\u0010\u0002J\u001e\u0010\u0003\u001a\u00020\u00042\u0014\u0010\u0005\u001a\u0010\u0012\u0004\u0012\u00020\u0007\u0012\u0004\u0012\u00020\b\u0018\u00010\u0006H\u0016¨\u0006\t"}, d2 = {"com/alibaba/android/arouter/routes/ARouter$$Group$$watch_face", "Lcom/alibaba/android/arouter/facade/template/IRouteGroup;", "()V", Consts.METHOD_LOAD_INTO, "", "atlas", "", "", "Lcom/alibaba/android/arouter/facade/model/RouteMeta;", "watchface_impl_release"}, k = 1, mv = {1, 8, 0}, xi = 48)
public final class ARouter$$Group$$watch_face implements IRouteGroup {
    @Override // com.alibaba.android.arouter.facade.template.IRouteGroup
    public void loadInto(@Nullable Map<String, RouteMeta> atlas) {
        if (atlas == null) {
            return;
        }
        RouteType routeType = RouteType.ACTIVITY;
        RouteMeta routeMetaBuild = RouteMeta.build(routeType, BreenoRouterActivity.class, "/watch_face/breenorouteractivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/BreenoRouterActivity", routeMetaBuild);
        RouteType routeType2 = RouteType.PROVIDER;
        RouteMeta routeMetaBuild2 = RouteMeta.build(routeType2, CommunityImagePickerServiceImpl.class, "/watch_face/imagepickerservice", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild2, "build(RouteType.PROVIDER…   null, -1, -2147483648)");
        atlas.put("/watch_face/ImagePickerService", routeMetaBuild2);
        RouteMeta routeMetaBuild3 = RouteMeta.build(routeType2, MessageReceiveClient.class, "/watch_face/messagereceiveclient", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild3, "build(RouteType.PROVIDER…   null, -1, -2147483648)");
        atlas.put("/watch_face/MessageReceiveClient", routeMetaBuild3);
        RouteMeta routeMetaBuild4 = RouteMeta.build(routeType, ThemeStoreRouterActivity.class, "/watch_face/themestorerouteractivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild4, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/ThemeStoreRouterActivity", routeMetaBuild4);
        RouteMeta routeMetaBuild5 = RouteMeta.build(routeType2, TransportReceiveClient.class, "/watch_face/transportreceiveclient", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild5, "build(RouteType.PROVIDER…   null, -1, -2147483648)");
        atlas.put("/watch_face/TransportReceiveClient", routeMetaBuild5);
        RouteMeta routeMetaBuild6 = RouteMeta.build(routeType, OutfitEditActivity.class, "/watch_face/edit/outfiteditactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild6, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/edit/OutfitEditActivity", routeMetaBuild6);
        RouteMeta routeMetaBuild7 = RouteMeta.build(routeType2, WatchFacePreviewService.class, "/watch_face/getcurrentpreview", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild7, "build(RouteType.PROVIDER…   null, -1, -2147483648)");
        atlas.put(WatchFaceApi.SERVICE_WATCH_FACE_OUT_API, routeMetaBuild7);
        RouteMeta routeMetaBuild8 = RouteMeta.build(routeType, AlbumHomeActivity.class, "/watch_face/main/albumhomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild8, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/AlbumHomeActivity", routeMetaBuild8);
        RouteMeta routeMetaBuild9 = RouteMeta.build(routeType, BuyListActivity.class, "/watch_face/main/buylistactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild9, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/BuyListActivity", routeMetaBuild9);
        RouteMeta routeMetaBuild10 = RouteMeta.build(routeType, ClassicCustomActivity.class, "/watch_face/main/classiccustomactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild10, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/ClassicCustomActivity", routeMetaBuild10);
        RouteMeta routeMetaBuild11 = RouteMeta.build(routeType, ClassicSeriesActivity.class, "/watch_face/main/classicseriesactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild11, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/ClassicSeriesActivity", routeMetaBuild11);
        RouteMeta routeMetaBuild12 = RouteMeta.build(routeType, CouponListActivity.class, "/watch_face/main/counponlistactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild12, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/CounponListActivity", routeMetaBuild12);
        RouteMeta routeMetaBuild13 = RouteMeta.build(routeType, DofHomeActivity.class, "/watch_face/main/dofhomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild13, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/DOFHomeActivity", routeMetaBuild13);
        RouteMeta routeMetaBuild14 = RouteMeta.build(routeType, DofTemplateActivity.class, "/watch_face/main/doftemplateactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild14, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/DOFTemplateActivity", routeMetaBuild14);
        RouteMeta routeMetaBuild15 = RouteMeta.build(routeType, FlexibleHomeActivity.class, "/watch_face/main/flexiblehomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild15, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/FlexibleHomeActivity", routeMetaBuild15);
        RouteMeta routeMetaBuild16 = RouteMeta.build(routeType, FlexibleManagerActivity.class, "/watch_face/main/flexiblemanageractivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild16, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/FlexibleManagerActivity", routeMetaBuild16);
        RouteMeta routeMetaBuild17 = RouteMeta.build(routeType, LivePhotoHomeActivity.class, "/watch_face/main/livephotohomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild17, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/LivePhotoHomeActivity", routeMetaBuild17);
        RouteMeta routeMetaBuild18 = RouteMeta.build(routeType, LivePhotoStartActivity.class, "/watch_face/main/livephotostarthomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild18, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/LivePhotoStartHomeActivity", routeMetaBuild18);
        RouteMeta routeMetaBuild19 = RouteMeta.build(routeType, OmojiEditActivity.class, "/watch_face/main/omojieditactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild19, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/OmojiEditActivity", routeMetaBuild19);
        RouteMeta routeMetaBuild20 = RouteMeta.build(routeType, OutfitsCameraActivity.class, "/watch_face/main/outfitswatchfacecustomcamera2activity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild20, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/OutfitsWatchFaceCustomCamera2Activity", routeMetaBuild20);
        RouteMeta routeMetaBuild21 = RouteMeta.build(routeType, PaintCreationActivity.class, "/watch_face/main/paintcreationactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild21, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/PaintCreationActivity", routeMetaBuild21);
        RouteMeta routeMetaBuild22 = RouteMeta.build(routeType, StyleChangeActivity.class, "/watch_face/main/stylechangeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild22, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/StyleChangeActivity", routeMetaBuild22);
        RouteMeta routeMetaBuild23 = RouteMeta.build(routeType, VideoCustomActivity.class, "/watch_face/main/videocustomactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild23, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/VideoCustomActivity", routeMetaBuild23);
        RouteMeta routeMetaBuild24 = RouteMeta.build(routeType, WallpaperCustomActivity.class, "/watch_face/main/wallpapercustomactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild24, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WallpaperCustomActivity", routeMetaBuild24);
        RouteMeta routeMetaBuild25 = RouteMeta.build(routeType, WatchFaceHomeActivity.class, "/watch_face/main/watchfacehomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild25, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceHomeActivity", routeMetaBuild25);
        RouteMeta routeMetaBuild26 = RouteMeta.build(routeType, WatchFaceMyActivity.class, "/watch_face/main/watchfacemyactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild26, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceMyActivity", routeMetaBuild26);
        RouteMeta routeMetaBuild27 = RouteMeta.build(routeType, WatchFaceCenterActivity.class, "/watch_face/main/watchfacemycenteractivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild27, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceMyCenterActivity", routeMetaBuild27);
        RouteMeta routeMetaBuild28 = RouteMeta.build(routeType, WatchFaceOnlineActivity.class, "/watch_face/main/watchfaceonlineactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild28, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceOnlineActivity", routeMetaBuild28);
        RouteMeta routeMetaBuild29 = RouteMeta.build(routeType, WatchFaceOverViewActivity.class, "/watch_face/main/watchfaceoverviewactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild29, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceOverViewActivity", routeMetaBuild29);
        RouteMeta routeMetaBuild30 = RouteMeta.build(routeType, InternalRouteActivity.class, "/watch_face/main/watchfacerouteactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild30, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceRouteActivity", routeMetaBuild30);
        RouteMeta routeMetaBuild31 = RouteMeta.build(routeType, WatchFaceStoreDetailActivity.class, "/watch_face/main/watchfacestoredetailactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild31, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceStoreDetailActivity", routeMetaBuild31);
        RouteMeta routeMetaBuild32 = RouteMeta.build(routeType, WatchFaceStoreHomeActivity.class, "/watch_face/main/watchfacestorehomeactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild32, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/WatchFaceStoreHomeActivity", routeMetaBuild32);
        RouteMeta routeMetaBuild33 = RouteMeta.build(routeType, WfSearchActivity.class, "/watch_face/main/wfsearchactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild33, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/WfSearchActivity", routeMetaBuild33);
        RouteMeta routeMetaBuild34 = RouteMeta.build(routeType, AlbumEditActivity.class, "/watch_face/main/edit/albumeditactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild34, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/edit/AlbumEditActivity", routeMetaBuild34);
        RouteMeta routeMetaBuild35 = RouteMeta.build(routeType, EditWatchFacesActivity.class, "/watch_face/main/edit/editwatchpanelactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild35, "build(RouteType.ACTIVITY…\", null, -1, -2147483648)");
        atlas.put("/watch_face/main/edit/EditWatchPanelActivity", routeMetaBuild35);
        RouteMeta routeMetaBuild36 = RouteMeta.build(routeType, FindActivity.class, "/watch_face/main/find/findpanelsactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild36, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/main/find/FindPanelsActivity", routeMetaBuild36);
        RouteMeta routeMetaBuild37 = RouteMeta.build(routeType, PushNewWatchFaceActivity.class, "/watch_face/new", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild37, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/new", routeMetaBuild37);
        RouteMeta routeMetaBuild38 = RouteMeta.build(routeType, OmojiCustomActivity.class, "/watch_face/omoji/omojicustomactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild38, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/omoji/OmojiCustomActivity", routeMetaBuild38);
        RouteMeta routeMetaBuild39 = RouteMeta.build(routeType, OutfitsWatchFaceCustomCameraActivity.class, "/watch_face/outfits/outfitswatchfacecustomcameraactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild39, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/outfits/OutfitsWatchFaceCustomCameraActivity", routeMetaBuild39);
        RouteMeta routeMetaBuild40 = RouteMeta.build(routeType, EditWatchFace2Activity.class, "/watch_face/v1/main/edit/watchfaceeditwatchpanelactivity", "watch_face", null, -1, Integer.MIN_VALUE);
        Intrinsics.checkNotNullExpressionValue(routeMetaBuild40, "build(RouteType.ACTIVITY…   null, -1, -2147483648)");
        atlas.put("/watch_face/v1/main/edit/WatchFaceEditWatchPanelActivity", routeMetaBuild40);
    }
}
