package com.heytap.health.base;

import com.heytap.health.R;

/* JADX INFO: loaded from: classes15.dex */
public final class R$styleable {
    public static final int lib_base_BounceScrollView_flingAnimationOnly = 0;
    public static final int lib_base_CircleProgressBar_lib_base_current_progress = 0;
    public static final int lib_base_CircleProgressBar_lib_base_inside_color = 1;
    public static final int lib_base_CircleProgressBar_lib_base_max_progress = 2;
    public static final int lib_base_CircleProgressBar_lib_base_outside_color = 3;
    public static final int lib_base_CircleProgressBar_lib_base_outside_radius = 4;
    public static final int lib_base_CircleProgressBar_lib_base_progress_width = 5;
    public static final int lib_base_CircularSeekBar_lib_base_circle_color = 0;
    public static final int lib_base_CircularSeekBar_lib_base_circle_fill = 1;
    public static final int lib_base_CircularSeekBar_lib_base_circle_progress_color = 2;
    public static final int lib_base_CircularSeekBar_lib_base_circle_stroke_width = 3;
    public static final int lib_base_CircularSeekBar_lib_base_circle_x_radius = 4;
    public static final int lib_base_CircularSeekBar_lib_base_circle_y_radius = 5;
    public static final int lib_base_CircularSeekBar_lib_base_end_angle = 6;
    public static final int lib_base_CircularSeekBar_lib_base_lock_enabled = 7;
    public static final int lib_base_CircularSeekBar_lib_base_maintain_equal_circle = 8;
    public static final int lib_base_CircularSeekBar_lib_base_max = 9;
    public static final int lib_base_CircularSeekBar_lib_base_move_outside_circle = 10;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_alpha_ontouch = 11;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_color = 12;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_halo_border_width = 13;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_halo_color = 14;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_halo_color_ontouch = 15;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_halo_width = 16;
    public static final int lib_base_CircularSeekBar_lib_base_pointer_radius = 17;
    public static final int lib_base_CircularSeekBar_lib_base_progress = 18;
    public static final int lib_base_CircularSeekBar_lib_base_start_angle = 19;
    public static final int lib_base_CircularSeekBar_lib_base_use_custom_radii = 20;
    public static final int lib_base_CommonScrollTopLineView_lib_base_bind_view = 0;
    public static final int lib_base_CommonScrollTopLineView_lib_base_recycler_view_over_scroll = 1;
    public static final int lib_base_DevicePageLayout_lib_base_exception_type = 0;
    public static final int lib_base_FlowLayout_horizontalSpacing = 0;
    public static final int lib_base_FlowLayout_ifAccordantTop = 1;
    public static final int lib_base_FlowLayout_ifCentre = 2;
    public static final int lib_base_FlowLayout_ifFillLayout = 3;
    public static final int lib_base_FlowLayout_maxChileEachLine = 4;
    public static final int lib_base_FlowLayout_maxLinesCount = 5;
    public static final int lib_base_FlowLayout_needExpend = 6;
    public static final int lib_base_FlowLayout_sequence = 7;
    public static final int lib_base_FlowLayout_verticalSpacing = 8;
    public static final int lib_base_GradientProgressBar_lib_base_indicator_bottom_text_center = 0;
    public static final int lib_base_GradientProgressBar_lib_base_indicator_bottom_text_color = 1;
    public static final int lib_base_GradientProgressBar_lib_base_indicator_bottom_text_left = 2;
    public static final int lib_base_GradientProgressBar_lib_base_indicator_bottom_text_right = 3;
    public static final int lib_base_GradientProgressBar_lib_base_indicator_bottom_text_size = 4;
    public static final int lib_base_GradientProgressBar_lib_base_max_progress_value = 5;
    public static final int lib_base_GradientProgressBar_lib_base_min_progress_value = 6;
    public static final int lib_base_GradientProgressBar_lib_base_progress_height = 7;
    public static final int lib_base_GradientProgressBar_lib_base_progress_value = 8;
    public static final int lib_base_HealthSegmentButtonLayout_linkViewPager = 0;
    public static final int lib_base_MedalShadowViewTheme_shadow = 0;
    public static final int lib_base_RoundedImageView_lib_base_riv_border_color = 0;
    public static final int lib_base_RoundedImageView_lib_base_riv_border_width = 1;
    public static final int lib_base_RoundedImageView_lib_base_riv_corner_radius = 2;
    public static final int lib_base_RoundedImageView_lib_base_riv_corner_radius_bottom_left = 3;
    public static final int lib_base_RoundedImageView_lib_base_riv_corner_radius_bottom_right = 4;
    public static final int lib_base_RoundedImageView_lib_base_riv_corner_radius_top_left = 5;
    public static final int lib_base_RoundedImageView_lib_base_riv_corner_radius_top_right = 6;
    public static final int lib_base_RoundedImageView_lib_base_riv_inner_border = 7;
    public static final int lib_base_RoundedImageView_lib_base_riv_mutate_background = 8;
    public static final int lib_base_RoundedImageView_lib_base_riv_oval = 9;
    public static final int lib_base_RoundedImageView_lib_base_riv_tile_mode = 10;
    public static final int lib_base_RoundedImageView_lib_base_riv_tile_mode_x = 11;
    public static final int lib_base_RoundedImageView_lib_base_riv_tile_mode_y = 12;
    public static final int lib_base_TextProgressBtn_progressbtn_background_color = 0;
    public static final int lib_base_TextProgressBtn_progressbtn_background_second_color = 1;
    public static final int lib_base_TextProgressBtn_progressbtn_enable_gradient = 2;
    public static final int lib_base_TextProgressBtn_progressbtn_enable_press = 3;
    public static final int lib_base_TextProgressBtn_progressbtn_radius = 4;
    public static final int lib_base_TextProgressBtn_progressbtn_text_color = 5;
    public static final int lib_base_TextProgressBtn_progressbtn_text_covercolor = 6;
    public static final int lib_base_TextProgressBtn_progressbtn_text_size = 7;
    public static final int lib_base_ViewPagerTabLayout_bindViewPager = 0;
    public static final int lib_base_ViewPagerTabLayout_contentBackground = 1;
    public static final int lib_base_ViewPagerTabLayout_sliderHeight = 2;
    public static final int lib_base_ViewPagerTabLayout_sliderSrc = 3;
    public static final int lib_base_ViewPagerTabLayout_sliderWidth = 4;
    public static final int lib_base_ViewPagerTabLayout_tabTextColor = 5;
    public static final int lib_base_ViewPagerTabLayout_tabTextFontFamily = 6;
    public static final int lib_base_ViewPagerTabLayout_tabTextSize = 7;
    public static final int lib_base_calendarDayBg_isCurDay = 0;
    public static final int lib_base_calendarDayBg_isFutureDay = 1;
    public static final int lib_base_calendarDayBg_isPastDay = 2;
    public static final int lib_base_press_anim_animAfterPause = 0;
    public static final int[] lib_base_BounceScrollView = {R.attr.flingAnimationOnly};
    public static final int[] lib_base_CircleProgressBar = {R.attr.lib_base_current_progress, R.attr.lib_base_inside_color, R.attr.lib_base_max_progress, R.attr.lib_base_outside_color, R.attr.lib_base_outside_radius, R.attr.lib_base_progress_width};
    public static final int[] lib_base_CircularSeekBar = {R.attr.lib_base_circle_color, R.attr.lib_base_circle_fill, R.attr.lib_base_circle_progress_color, R.attr.lib_base_circle_stroke_width, R.attr.lib_base_circle_x_radius, R.attr.lib_base_circle_y_radius, R.attr.lib_base_end_angle, R.attr.lib_base_lock_enabled, R.attr.lib_base_maintain_equal_circle, R.attr.lib_base_max, R.attr.lib_base_move_outside_circle, R.attr.lib_base_pointer_alpha_ontouch, R.attr.lib_base_pointer_color, R.attr.lib_base_pointer_halo_border_width, R.attr.lib_base_pointer_halo_color, R.attr.lib_base_pointer_halo_color_ontouch, R.attr.lib_base_pointer_halo_width, R.attr.lib_base_pointer_radius, R.attr.lib_base_progress, R.attr.lib_base_start_angle, R.attr.lib_base_use_custom_radii};
    public static final int[] lib_base_CommonScrollTopLineView = {R.attr.lib_base_bind_view, R.attr.lib_base_recycler_view_over_scroll};
    public static final int[] lib_base_DevicePageLayout = {R.attr.lib_base_exception_type};
    public static final int[] lib_base_FlowLayout = {R.attr.horizontalSpacing, R.attr.ifAccordantTop, R.attr.ifCentre, R.attr.ifFillLayout, R.attr.maxChileEachLine, R.attr.maxLinesCount, R.attr.needExpend, R.attr.sequence, R.attr.verticalSpacing};
    public static final int[] lib_base_GradientProgressBar = {R.attr.lib_base_indicator_bottom_text_center, R.attr.lib_base_indicator_bottom_text_color, R.attr.lib_base_indicator_bottom_text_left, R.attr.lib_base_indicator_bottom_text_right, R.attr.lib_base_indicator_bottom_text_size, R.attr.lib_base_max_progress_value, R.attr.lib_base_min_progress_value, R.attr.lib_base_progress_height, R.attr.lib_base_progress_value};
    public static final int[] lib_base_HealthSegmentButtonLayout = {R.attr.linkViewPager};
    public static final int[] lib_base_MedalShadowViewTheme = {R.attr.shadow};
    public static final int[] lib_base_RoundedImageView = {R.attr.lib_base_riv_border_color, R.attr.lib_base_riv_border_width, R.attr.lib_base_riv_corner_radius, R.attr.lib_base_riv_corner_radius_bottom_left, R.attr.lib_base_riv_corner_radius_bottom_right, R.attr.lib_base_riv_corner_radius_top_left, R.attr.lib_base_riv_corner_radius_top_right, R.attr.lib_base_riv_inner_border, R.attr.lib_base_riv_mutate_background, R.attr.lib_base_riv_oval, R.attr.lib_base_riv_tile_mode, R.attr.lib_base_riv_tile_mode_x, R.attr.lib_base_riv_tile_mode_y};
    public static final int[] lib_base_TextProgressBtn = {R.attr.progressbtn_background_color, R.attr.progressbtn_background_second_color, R.attr.progressbtn_enable_gradient, R.attr.progressbtn_enable_press, R.attr.progressbtn_radius, R.attr.progressbtn_text_color, R.attr.progressbtn_text_covercolor, R.attr.progressbtn_text_size};
    public static final int[] lib_base_ViewPagerTabLayout = {R.attr.bindViewPager, R.attr.contentBackground, R.attr.sliderHeight, R.attr.sliderSrc, R.attr.sliderWidth, R.attr.tabTextColor, R.attr.tabTextFontFamily, R.attr.tabTextSize};
    public static final int[] lib_base_calendarDayBg = {R.attr.isCurDay, R.attr.isFutureDay, R.attr.isPastDay};
    public static final int[] lib_base_press_anim = {R.attr.animAfterPause};

    private R$styleable() {
    }
}
