import com.android.tools.smali.dexlib2.DexFileFactory;import com.android.tools.smali.dexlib2.iface.*;import com.android.tools.smali.dexlib2.iface.value.*;import org.objectweb.asm.*;import java.util.*;import java.nio.file.*;import java.nio.charset.StandardCharsets;import java.io.*;import java.util.jar.*;
public class ApiJar {
 static String name(String t){return t.substring(1,t.length()-1);}static String desc(Method m){StringBuilder b=new StringBuilder("(");for(CharSequence p:m.getParameterTypes())b.append(p);return b.append(")").append(m.getReturnType()).toString();}
 static Object constant(EncodedValue v){if(v instanceof IntEncodedValue)return ((IntEncodedValue)v).getValue();if(v instanceof BooleanEncodedValue)return ((BooleanEncodedValue)v).getValue()?1:0;if(v instanceof StringEncodedValue)return ((StringEncodedValue)v).getValue();if(v instanceof LongEncodedValue)return ((LongEncodedValue)v).getValue();if(v instanceof FloatEncodedValue)return ((FloatEncodedValue)v).getValue();if(v instanceof DoubleEncodedValue)return ((DoubleEncodedValue)v).getValue();return null;}
 static byte[] make(ClassDef c,boolean compat){ClassWriter w=new ClassWriter(ClassWriter.COMPUTE_MAXS);String owner=name(c.getType());w.visit(52,c.getAccessFlags()&0xffff,owner,null,c.getSuperclass()==null?null:name(c.getSuperclass()),c.getInterfaces().stream().map(ApiJar::name).toArray(String[]::new));
  for(Field f:c.getFields())w.visitField(f.getAccessFlags()&0xffff,f.getName(),f.getType(),null,constant(f.getInitialValue())).visitEnd();
  for(Method m:c.getMethods()){int flags=m.getAccessFlags()&0xffff;MethodVisitor v=w.visitMethod(flags,m.getName(),desc(m),null,null);if((flags&(Opcodes.ACC_ABSTRACT|Opcodes.ACC_NATIVE))==0){v.visitCode();String ret=m.getReturnType();if(m.getName().equals("<init>")){v.visitVarInsn(Opcodes.ALOAD,0);v.visitMethodInsn(Opcodes.INVOKESPECIAL,name(c.getSuperclass()),"<init>","()V",false);v.visitInsn(Opcodes.RETURN);}else if(compat&&ret.equals("Lcom/heytap/health/base/track/a$b;")){v.visitTypeInsn(Opcodes.NEW,"com/heytap/health/base/track/a$b");v.visitInsn(Opcodes.DUP);v.visitInsn(Opcodes.ACONST_NULL);v.visitMethodInsn(Opcodes.INVOKESPECIAL,"com/heytap/health/base/track/a$b","<init>","(Ljava/lang/Object;)V",false);v.visitInsn(Opcodes.ARETURN);}else if(ret.equals("V"))v.visitInsn(Opcodes.RETURN);else if(ret.startsWith("L")||ret.startsWith("[")){v.visitInsn(Opcodes.ACONST_NULL);v.visitInsn(Opcodes.ARETURN);}else if(ret.equals("J")){v.visitInsn(Opcodes.LCONST_0);v.visitInsn(Opcodes.LRETURN);}else if(ret.equals("D")){v.visitInsn(Opcodes.DCONST_0);v.visitInsn(Opcodes.DRETURN);}else if(ret.equals("F")){v.visitInsn(Opcodes.FCONST_0);v.visitInsn(Opcodes.FRETURN);}else{v.visitInsn(Opcodes.ICONST_0);v.visitInsn(Opcodes.IRETURN);}v.visitMaxs(0,0);}v.visitEnd();}w.visitEnd();return w.toByteArray();}
 public static void main(String[] args)throws Exception{
  Set<String> select=new HashSet<>(Files.readAllLines(Paths.get(args[1]),StandardCharsets.UTF_8));var container=DexFileFactory.loadDexContainer(new File(args[0]),com.android.tools.smali.dexlib2.Opcodes.getDefault());
  try(JarOutputStream api=new JarOutputStream(new FileOutputStream(args[2]));JarOutputStream compat=new JarOutputStream(new FileOutputStream(args[3]))){int n=0;for(String dex:container.getDexEntryNames())for(ClassDef c:container.getEntry(dex).getDexFile().getClasses()){boolean override=c.getType().equals("Lcom/oplus/aiunit/vision/m8b;")||(c.getType().equals("Lcom/heytap/health/base/track/a;")||c.getType().equals("Lcom/heytap/health/base/track/a$b;"));if(!select.contains(c.getType())&&!override)continue;JarEntry e=new JarEntry(name(c.getType())+".class");api.putNextEntry(e);api.write(make(c,false));api.closeEntry();n++;if(override){compat.putNextEntry(new JarEntry(e.getName()));compat.write(make(c,true));compat.closeEntry();}}System.out.println("API classes "+n);}
 }
}
