package com.example.opponotificationrelay;
import android.app.Activity;import android.os.Bundle;import android.content.Context;import android.view.View;import android.widget.*;
import com.github.mikephil.charting.data.*;import com.heytap.health.core.widget.charts.HealthTimeXLineChart;import com.heytap.health.core.widget.charts.GluCombineChart;import com.heytap.health.core.widget.charts.data.TimeUnit;import com.heytap.health.healthbase.view.HealthProgressBarView3;
import java.time.*;import java.time.temporal.ChronoUnit;import java.util.*;
/** Local records bound to the original health charts. */
public final class AdditionalHealthActivity extends OfficialUiActivity implements HealthDataManager.Listener {
 private OfficialComposeOwner composeOwner;
 private int kind=8,mode,visible=30;private LocalDate date=LocalDate.now();private HealthMetricsData data;private TextView status;private ScrollView scroll;
 private String title(){return kind==8?"体重":kind==9?"血糖":"睡眠呼吸暂停";}
 @Override public void onUiCreate(Bundle saved){super.onUiCreate(saved);composeOwner=new OfficialComposeOwner(this);kind=getIntent().getIntExtra("vital",8);if(kind<8||kind>10)kind=8;try{date=LocalDate.parse(saved!=null?saved.getString("date"):getIntent().getStringExtra("date"));}catch(Exception ignored){}if(saved!=null)mode=saved.getInt("mode");build(false);}
 @Override protected void onUiStart(){super.onUiStart();HealthDataManager.get(this).add(this);request();}
 @Override protected void onUiResume(){super.onUiResume();composeOwner.state("RESUMED");}
 @Override protected void onUiPause(){composeOwner.state("STARTED");super.onUiPause();}
 @Override protected void onUiDestroy(){composeOwner.state("DESTROYED");super.onUiDestroy();}
 @Override protected void onUiStop(){composeOwner.state("CREATED");HealthDataManager.get(this).remove(this);data=null;super.onUiStop();}
 @Override protected void onUiSaveInstanceState(Bundle saved){saved.putString("date",date.toString());saved.putInt("mode",mode);super.onUiSaveInstanceState(saved);}
 private void request(){HealthDataManager.get(this).request(new HealthMetricsData.Period(date,mode),date,false);if(kind==9&&mode==0)HealthDataManager.get(this).request(date,true,false);}
 private void change(LocalDate day,int selectedMode){if(day.isBefore(LocalDate.of(2019,1,1)))return;date=day.isAfter(LocalDate.now())?LocalDate.now():day;mode=selectedMode;visible=30;build(false);request();}
 @Override public void changed(HealthMetricsData value,String message,boolean busy){if(data!=value){data=value;build(true);}status.setText(message);status.setVisibility(message.isEmpty()?View.GONE:View.VISIBLE);}
 boolean has(HealthMetricsData.Day d){return kind==8?d.weightGrams>0:kind==9?d.glucoseMean>0||d.glucoseLatest>0:d.apneaLevel>=-1;}
 private float metric(HealthMetricsData.Day d){return kind==8?d.weightGrams/1000f:kind==9?(d.glucoseMean>0?d.glucoseMean:d.glucoseLatest)/1000f:d.apneaLevel;}
 private String number(float value){return String.format(Locale.CHINA,"%.1f",value);}
 private String unit(){return kind==8?"公斤":kind==9?"mmol/L":"";}
 private String record(Context ui,HealthMetricsData.Day d){if(kind==10)return AdditionalCardUi.apnea(ui,d.apneaLevel)+(d.apneaAhi>=0?" · AHI "+String.format(Locale.CHINA,"%.2f",d.apneaAhi/1000f):"");return number(metric(d))+" "+unit()+(kind==9&&d.glucoseMin>0&&d.glucoseMax>0?" · 范围 "+number(d.glucoseMin/1000f)+"–"+number(d.glucoseMax/1000f):"");}
 private void build(boolean keep){int y=keep&&scroll!=null?scroll.getScrollY():0;Context ui=OfficialUiResources.wrap(this);HealthMetricsData.Period p=new HealthMetricsData.Period(date,mode);List<HealthMetricsData.Day> days=new ArrayList<>();if(data!=null)for(HealthMetricsData.Day d:data.days.subMap(p.start,true,p.end,true).values())if(has(d)&&(kind!=9||mode==0||d.glucoseMean>0))days.add(d);
  LinearLayout root=HealthUi.vertical(this);root.setBackgroundColor(0xff1a1a1a);HealthUi.header(this,root,title(),null);HealthUi.segments(this,root,mode,m->change(date,m));LinearLayout calendar=HealthUi.vertical(this);HealthUi.padding(calendar,18,0,18,0);HealthUi.dateRow(this,calendar,p.label(),p.end.isBefore(LocalDate.now()),()->change(p.previous().start,mode),()->change(p.next(),mode),()->HealthUi.pick(this,date,d->change(d,mode)));root.addView(calendar);
  scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=HealthUi.vertical(this);scroll.addView(body);LinearLayout top=HealthUi.vertical(this);HealthUi.padding(top,18,4,18,16);HealthMetricsData.Day selected=data==null?null:data.find(date);String summary="—";
  if(!days.isEmpty()){if(kind==10)summary=mode==0?AdditionalCardUi.apnea(ui,days.get(0).apneaLevel):days.size()+" 天";else if(kind==8)summary=number(metric(days.get(days.size()-1)));else {float sum=0;for(HealthMetricsData.Day d:days)sum+=metric(d);summary=number(sum/days.size());if(mode==0&&selected!=null&&selected.glucoseLatest>0)summary=number(selected.glucoseLatest/1000f);}}
  top.addView(HealthUi.text(this,kind==8?"最近体重":kind==9?(mode==0&&selected!=null&&selected.glucoseLatest>0?"最近血糖":"每日均值的平均值"):mode==0?"记录结果":"有记录天数",16,HealthUi.MUTED));top.addView(HealthUi.value(this,summary,unit(),kind==10?30:42));
  if(mode==0&&selected!=null&&has(selected)){if(kind==8)top.addView(HealthUi.text(this,HealthMetricsData.timeLabel(selected.weightTime),16,HealthUi.MUTED));if(kind==9&&selected.glucoseTime>0)top.addView(HealthUi.text(this,HealthMetricsData.timeLabel(selected.glucoseTime),16,HealthUi.MUTED));if(kind==10){if(selected.apneaAhi>=0)top.addView(HealthUi.text(this,"AHI "+String.format(Locale.CHINA,"%.2f",selected.apneaAhi/1000f),16,HealthUi.MUTED));HealthProgressBarView3 bar=new HealthProgressBarView3(ui);AdditionalCardUi.apneaBar(ui,bar,selected.apneaLevel);top.addView(bar,new LinearLayout.LayoutParams(-1,HealthUi.dp(this,48)));}}body.addView(top);
  if(kind==9&&mode==0){GluCombineChart chart=new GluCombineChart(ui);AdditionalCardUi.glucose(chart,data,date,false);OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{com.heytap.health.core.widget.charts.data.TimeStampedData q=(com.heytap.health.core.widget.charts.data.TimeStampedData)entry.getData();return heading?HealthMetricsData.timeLabel(q.getTimestamp()):number(q.getY())+" mmol/L";});chart.setContentDescription("血糖记录图");body.addView(chart,new LinearLayout.LayoutParams(-1,HealthUi.dp(this,260)));}
  else if(mode!=0&&kind==9){body.addView(OfficialGlucoseChart.create(this,data,p),new LinearLayout.LayoutParams(-1,HealthUi.dp(this,260)));}
  else if(mode!=0&&kind==8){OfficialWeightChart.add(this,body,data,p);}
  DetailDataCards.additional(this,body,data,p,kind);
  DetailKnowledge.add(this,body,kind,data);LinearLayout records=HealthUi.vertical(this);HealthUi.padding(records,18,22,18,24);records.addView(HealthUi.text(this,mode==0?"当天记录":kind==8?"每日最后一次记录":kind==9?"每日均值":"每日记录",19,HealthUi.TEXT));List<String> labels=new ArrayList<>();List<LocalDate> dates=new ArrayList<>();
  if(mode==0&&data!=null&&kind==8){for(Map.Entry<Long,Integer> q:data.weights.subMap(HealthMetricsData.time(date),true,HealthMetricsData.time(date.plusDays(1)),false).descendingMap().entrySet())labels.add(HealthMetricsData.timeLabel(q.getKey())+"    "+number(q.getValue()/1000f)+" 公斤");}
  else if(mode==0&&data!=null&&kind==9){List<HealthMetricsData.Glucose> points=data.glucose(date);for(int i=points.size()-1;i>=0;i--){HealthMetricsData.Glucose q=points.get(i);labels.add(HealthMetricsData.timeLabel(q.time)+"    "+number(q.milli/1000f)+" mmol/L");}if(labels.isEmpty()&&selected!=null&&selected.glucoseMean>0)labels.add("当日汇总    "+record(ui,selected));}
  else for(int i=days.size()-1;i>=0;i--){HealthMetricsData.Day d=days.get(i);labels.add(d.date+"    "+record(ui,d));dates.add(d.date);}
  if(labels.isEmpty())records.addView(HealthUi.text(this,"暂无记录",17,HealthUi.MUTED));for(int i=0;i<Math.min(visible,labels.size());i++){String label=labels.get(i);TextView row=HealthUi.text(this,label,16,HealthUi.TEXT);HealthUi.padding(row,0,16,0,16);if(mode!=0){LocalDate day=dates.get(i);row.setContentDescription(label+"，查看当天记录");row.setOnClickListener(v->change(day,0));}records.addView(row);}if(labels.size()>visible){Button more=new Button(this);more.setText("查看更多记录");more.setOnClickListener(v->{visible+=30;build(true);});records.addView(more);}
  status=HealthUi.text(this,"",12,HealthUi.MUTED);status.setVisibility(View.GONE);records.addView(status);body.addView(records);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);DeviceStyle.insets(this,root);if(y>0)scroll.post(()->scroll.scrollTo(0,y));
 }
}
