package com.example.opponotificationrelay;
import android.app.Activity;import android.widget.*;import java.time.*;import java.util.*;
final class DetailDataCards {
 static LinearLayout card(Activity a,LinearLayout body,String title){LinearLayout outer=HealthUi.vertical(a);HealthUi.padding(outer,18,12,18,0);LinearLayout card=HealthUi.card(a,0xff292929);card.addView(HealthUi.text(a,title,19,HealthUi.TEXT));HealthUi.addCard(outer,card);body.addView(outer);return card;}
 static void row(Activity a,LinearLayout card,String title,String value){TextView v=HealthUi.text(a,title+"    "+value,16,HealthUi.TEXT);HealthUi.padding(v,0,18,0,6);card.addView(v);}
 static String decimal(float value){return String.format(Locale.CHINA,"%.1f",value);}
 static void wellness(Activity a,LinearLayout body,HealthMetricsData data,HealthMetricsData.Period p,int kind){if(kind==6){LinearLayout card=card(a,body,"放松统计");int count=0,seconds=0,breath=0,meditation=0,bc=0,mc=0;if(data!=null)for(HealthMetricsData.Relax q:data.relax.subMap(HealthMetricsData.time(p.start),true,HealthMetricsData.time(p.end.plusDays(1)),false).values()){count++;seconds+=q.seconds;if(q.type==1){breath+=q.seconds;bc++;}else if(q.type==2){meditation+=q.seconds;mc++;}}row(a,card,"累计次数",count==0?"—":count+" 次");row(a,card,"累计时长",count==0?"—":seconds/60+" 分钟");row(a,card,"呼吸",bc==0?"—":breath/60+" 分钟 · "+bc+" 次");row(a,card,"冥想",mc==0?"—":meditation/60+" 分钟 · "+mc+" 次");}
  else if(kind==7&&p.mode!=0){LinearLayout card=card(a,body,"日照分析");int count=0,sum=0,achieved=0;if(data!=null)for(HealthMetricsData.Day d:data.days.subMap(p.start,true,p.end,true).values())if(d.sunshineMinutes>=0){count++;sum+=d.sunshineMinutes;if(d.sunshineTarget>0&&d.sunshineMinutes>=d.sunshineTarget)achieved++;}row(a,card,"日均日照",count==0?"—":decimal(sum/(float)count)+" 分钟");row(a,card,"达标天数",count==0?"—":achieved+" 天");}
  else if(kind==5&&p.mode!=0){LinearLayout card=card(a,body,"状态分析");int count=0,sum=0,low=101,high=0;if(data!=null)for(HealthMetricsData.Day d:data.days.subMap(p.start,true,p.end,true).values())if(d.mentalAverage>0){count++;sum+=d.mentalAverage;low=Math.min(low,d.mentalAverage);high=Math.max(high,d.mentalAverage);}row(a,card,"平均身心状态",count==0?"—":Integer.toString(sum/count));row(a,card,"每日均值范围",count==0?"—":low+"–"+high);}
 }
 static void additional(Activity a,LinearLayout body,HealthMetricsData data,HealthMetricsData.Period p,int kind){LinearLayout card=card(a,body,"数据详情");List<HealthMetricsData.Day> days=data==null?Collections.emptyList():new ArrayList<>(data.days.subMap(p.start,true,p.end,true).values());if(kind==9){int low=0,high=0,count=0;long sum=0;for(HealthMetricsData.Day d:days){if(d.glucoseMin>0){low=low==0?d.glucoseMin:Math.min(low,d.glucoseMin);high=Math.max(high,d.glucoseMax);}if(d.glucoseMean>0){sum+=d.glucoseMean;count++;}}row(a,card,"最低血糖",low==0?"—":decimal(low/1000f)+" mmol/L");row(a,card,"最高血糖",high==0?"—":decimal(high/1000f)+" mmol/L");row(a,card,p.mode==0?"平均血糖":"每日均值的平均值",count==0?"—":decimal(sum/(1000f*count))+" mmol/L");}
  else if(kind==8){int first=0,last=0,low=0,high=0,count=0;if(data!=null)for(int grams:data.weights.subMap(HealthMetricsData.time(p.start),true,HealthMetricsData.time(p.end.plusDays(1)),false).values()){if(count++==0)first=grams;last=grams;low=low==0?grams:Math.min(low,grams);high=Math.max(high,grams);}row(a,card,"测量次数",count==0?"—":count+" 次");row(a,card,"体重范围",count==0?"—":decimal(low/1000f)+"–"+decimal(high/1000f)+" 公斤");row(a,card,"首末变化",count<2?"—":String.format(Locale.CHINA,"%+.1f 公斤",(last-first)/1000f));}
  else{int[] counts=new int[4];int valid=0;for(HealthMetricsData.Day d:days)if(d.apneaLevel>=0&&d.apneaLevel<=3){counts[d.apneaLevel]++;valid++;}for(int i=0;i<4;i++)row(a,card,AdditionalCardUi.apnea(OfficialUiResources.wrap(a),i),valid==0?"—":counts[i]+" 天");}
 }
}
