package com.example.opponotificationrelay;
import android.app.Activity;import android.content.*;import android.net.Uri;import android.widget.*;import java.util.*;
/** Original packaged knowledge text plus actual official cached article links. */
final class DetailKnowledge {
 static String text(Context c,String name){int id=c.getResources().getIdentifier(name,"string","com.heytap.health");return id==0?"":c.getString(id);}
 static void item(Activity a,LinearLayout parent,Context ui,String titleKey,String... bodyKeys){String title=text(ui,titleKey);StringBuilder body=new StringBuilder();for(String key:bodyKeys){String s=text(ui,key);if(!s.isEmpty()){if(body.length()>0)body.append("\n\n");body.append(s);}}if(title.isEmpty()||body.length()==0)return;String content=body.toString();LinearLayout card=HealthUi.card(a,0xff292929);TextView heading=HealthUi.text(a,title+"  ›",18,HealthUi.TEXT);card.addView(heading);TextView excerpt=HealthUi.text(a,content,14,HealthUi.MUTED);excerpt.setMaxLines(3);excerpt.setEllipsize(android.text.TextUtils.TruncateAt.END);HealthUi.padding(excerpt,0,12,0,0);card.addView(excerpt);card.setContentDescription(title+"，查看知识内容");card.setOnClickListener(v->HealthUi.sheet(a,title,null,"",content));HealthUi.addCard(parent,card);}
 static void add(Activity a,LinearLayout parent,int kind,HealthMetricsData data){Context ui=OfficialUiResources.wrap(a);LinearLayout section=HealthUi.vertical(a);HealthUi.padding(section,18,12,18,24);
  if(data!=null){String pages=kind==2?"2005,2006":kind==3?"2007,2008":kind==5?"2014":kind==7?"2021":kind==8?"2011":"";Set<String> allowed=new HashSet<>(Arrays.asList(pages.split(",")));boolean titleAdded=false;long now=System.currentTimeMillis();for(HealthMetricsData.Knowledge k:data.knowledge){long start=k.start>0&&k.start<100000000000L?k.start*1000:k.start,end=k.end>0&&k.end<100000000000L?k.end*1000:k.end;if(!allowed.contains(k.page)||(start>0&&start>now)||(end>0&&end<now)||RootKnowledgeReader.safeUrl(k.url).isEmpty())continue;if(!titleAdded){TextView heading=HealthUi.text(a,"知识卡",19,HealthUi.TEXT);HealthUi.padding(heading,0,0,0,16);section.addView(heading);titleAdded=true;}LinearLayout card=HealthUi.card(a,0xff292929);card.addView(HealthUi.text(a,k.title+"  ›",18,HealthUi.TEXT));if(!k.description.isEmpty()){TextView description=HealthUi.text(a,k.description,14,HealthUi.MUTED);description.setMaxLines(3);HealthUi.padding(description,0,12,0,0);card.addView(description);}card.setOnClickListener(v->{try{a.startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(k.url)));}catch(ActivityNotFoundException e){HealthUi.sheet(a,k.title,null,"",k.description.isEmpty()?"当前没有可打开文章的浏览器":k.description);}});HealthUi.addCard(section,card);}}
  if(kind==2){item(a,section,ui,"health_sleep_stage_description_desc6","health_sleep_stage_description_desc7","health_sleep_stage_description_desc8");item(a,section,ui,"health_sleep_frg_description_title","health_sleep_stage_description_desc1","health_sleep_stage_description_desc2","health_sleep_stage_description_desc4");item(a,section,ui,"health_sleep_br_about","health_sleep_br_about_tip");}
  else if(kind==3)item(a,section,ui,"health_blood_oxygen_about_card_title","health_blood_oxygen_about_card_content");
  else if(kind==4)item(a,section,ui,"health_wrist_temperature_about","health_wrist_temperature_about_content","health_wrist_temperature_description_content1","health_wrist_temperature_description_content2","health_wrist_temperature_description_reference_only");
  else if(kind==5){item(a,section,ui,"health_hrv_about_tips","health_hrv_what_is_stress_description_v2","health_hrv_four_level_description","health_hrv_level_excellent_description_v1","health_hrv_level_good_description_v1","health_hrv_level_normal_description_v1","health_hrv_level_over_description_v1");item(a,section,ui,"health_hrv_description_what_is_hrv","health_hrv_description_hrv_des");item(a,section,ui,"health_hrv_description_hrv_combina_heart_rate","health_hrv_description_hrv_combina_heart_rate_des");}
  else if(kind==6)item(a,section,ui,"health_relax_guide_about_relax","health_relax_guide_about_relax_desc");
  else if(kind==7)for(int i=1;i<=5;i++)item(a,section,ui,"health_sunshine_knowledge_card"+i+"_title","health_sunshine_knowledge_card"+i+"_content");
  else if(kind==9)item(a,section,ui,"health_blood_glucose_standard_status","health_blood_glucose_standard_tip1","health_blood_glucose_standard_tip3");
  else if(kind==10)item(a,section,ui,"health_sleep_snore_description_desc1","health_sleep_snore_description_desc2","health_sleep_snore_description_desc20","health_sleep_snore_description_desc22");
  if(section.getChildCount()>0)parent.addView(section);
 }
}
