package com.example.opponotificationrelay;

import android.app.*;
import android.content.*;
import android.content.pm.ActivityInfo;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.util.*;

public final class HeartDetailActivity extends OfficialUiActivity implements HealthDataManager.Listener {
    private LocalDate date=LocalDate.now();private int mode;private boolean line,expanded,active;private HealthMetricsData data;
    private LinearLayout root,toolbar;private ScrollView scroll;private TextView status;private HealthMetricsData.Period period;
    private final Handler main=new Handler(Looper.getMainLooper());
    private final Runnable tick=new Runnable(){public void run(){if(!active)return;HealthDataManager.get(HeartDetailActivity.this).local();main.postDelayed(this,3000);}};
    @Override public void onUiCreate(Bundle state){super.onUiCreate(state);try{date=LocalDate.parse(state!=null?state.getString("date"):getIntent().getStringExtra("date"));}catch(Exception ignored){}mode=state!=null?state.getInt("mode"):getIntent().getIntExtra("mode",0);line=getSharedPreferences("health_ui",MODE_PRIVATE).getBoolean("heart_line",false);expanded=getIntent().getBooleanExtra("expanded",false);if(expanded)setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_LANDSCAPE);build(false);}
    @Override protected void onUiStart(){super.onUiStart();active=true;HealthDataManager.get(this).add(this);request(false);HealthSyncManager.get(this).request(false);main.post(tick);}
    @Override protected void onUiStop(){active=false;main.removeCallbacks(tick);HealthDataManager.get(this).remove(this);data=null;super.onUiStop();}
    @Override protected void onUiSaveInstanceState(Bundle out){out.putString("date",date.toString());out.putInt("mode",mode);super.onUiSaveInstanceState(out);}
    private void request(boolean force){HealthDataManager.get(this).request(period,date,force);if(line&&mode==0)HealthDataManager.get(this).request(date,true,force);}
    @Override public void changed(HealthMetricsData value,String message,boolean busy){if(value!=data){data=value;build(true);}if(status!=null){status.setText(message);status.setVisibility(message.isEmpty()?View.GONE:View.VISIBLE);}}
    private void change(LocalDate d,int m){if(d.isAfter(LocalDate.now()))d=LocalDate.now();if(d.isBefore(LocalDate.of(2019,1,1)))return;date=d;mode=m;build(false);request(false);}
    private int dp(int n){return HealthUi.dp(this,n);}
    private void build(boolean keepScroll){int old=keepScroll&&scroll!=null?scroll.getScrollY():0;period=new HealthMetricsData.Period(date,mode);root=HealthUi.vertical(this);root.setBackgroundColor(DeviceStyle.BG);toolbar=HealthUi.header(this,root,expanded?"心率 · "+period.label():"心率",this::menu);
        if(expanded){HealthChartView chart=new HealthChartView(this);chart.bind(data,period,HealthMetricsData.HEART,line,false);HealthUi.padding(chart,18,0,18,10);root.addView(chart,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);DeviceStyle.insets(this,root);return;}
        HealthUi.segments(this,root,mode,m->change(date,m));LinearLayout calendar=HealthUi.vertical(this);HealthUi.padding(calendar,18,0,18,0);HealthUi.dateRow(this,calendar,period.label(),!period.next().isAfter(LocalDate.now()),()->change(period.previous().start,mode),()->change(period.next(),mode),()->HealthUi.pick(this,date,d->change(d,mode)));root.addView(calendar);
        scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=HealthUi.vertical(this);scroll.addView(body);LinearLayout chartArea=HealthUi.vertical(this);HealthUi.padding(chartArea,18,0,18,16);
        if(mode==0){OfficialHeartDayPanel panel=new OfficialHeartDayPanel(this,data,date,line,()->startActivity(new Intent(this,HeartDetailActivity.class).putExtra("date",date.toString()).putExtra("mode",0).putExtra("expanded",true)));body.addView(panel,new LinearLayout.LayoutParams(-1,-2));}
        else {
        TextView title=HealthUi.text(this,mode==0?"全天心率":"心率范围",16,HealthUi.MUTED);chartArea.addView(title);TextView value=HealthUi.value(this,data==null?"—":HealthMetricsData.rangeText(data.range(period,HealthMetricsData.HEART)),"次/分",42);LinearLayout.LayoutParams number=new LinearLayout.LayoutParams(-1,dp(62));number.topMargin=dp(4);chartArea.addView(value,number);
        FrameLayout chartBox=new FrameLayout(this);HealthChartView chart=new HealthChartView(this);chart.bind(data,period,HealthMetricsData.HEART,line&&mode==0,false);chartBox.addView(chart,new FrameLayout.LayoutParams(-1,-1));
        if(mode==0){ImageButton expand=new ImageButton(this);expand.setImageResource(R.drawable.official_health_expand);expand.setBackgroundColor(android.graphics.Color.TRANSPARENT);expand.setContentDescription("展开心率图表");expand.setOnClickListener(v->startActivity(new Intent(this,HeartDetailActivity.class).putExtra("date",date.toString()).putExtra("mode",mode).putExtra("expanded",true)));FrameLayout.LayoutParams lp=new FrameLayout.LayoutParams(dp(40),dp(40),Gravity.TOP|Gravity.RIGHT);lp.rightMargin=dp(34);lp.topMargin=dp(13);chartBox.addView(expand,lp);}
        chartArea.addView(chartBox,new LinearLayout.LayoutParams(-1,dp(228)));body.addView(chartArea);
        }
        LinearLayout lower=HealthUi.vertical(this);lower.setBackgroundColor(0xff000000);HealthUi.padding(lower,18,24,18,24);if(mode==0)dayDetails(lower);else for(int metric=1;metric<=3;metric++)metricCard(lower,metric);
        TextView warnings=HealthUi.text(this,"安静心率预警 "+(data==null||!data.officialLoaded?"—":Integer.toString(data.warningCount(period)))+"次",16,HealthUi.TEXT);HealthUi.padding(warnings,18,18,18,18);warnings.setBackground(DeviceStyle.shape(0xff1a1a1a,14,this));warnings.setOnClickListener(v->warningDetails());lower.addView(warnings,new LinearLayout.LayoutParams(-1,-2));
        status=HealthUi.text(this,"",12,0xff888888);status.setVisibility(View.GONE);HealthUi.padding(status,0,14,0,0);lower.addView(status);body.addView(lower);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);DeviceStyle.insets(this,root);if(old>0)scroll.post(()->scroll.scrollTo(0,old));
    }
    private void dayDetails(LinearLayout parent){LinearLayout card=HealthUi.card(this,0xff1a1a1a);HealthUi.padding(card,18,0,18,0);TextView heading=HealthUi.text(this,"心率详情",17,HealthUi.TEXT);heading.setTypeface(null,1);heading.setGravity(Gravity.CENTER_VERTICAL);card.addView(heading,new LinearLayout.LayoutParams(-1,dp(47)));HealthUi.divider(card);HealthMetricsData.Day day=data==null?null:data.find(date);
        for(int i=0;i<4;i++){final int metric=i;LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);TextView label=HealthUi.text(this,HealthUi.HEART_NAMES[i],16,HealthUi.TEXT);row.addView(label,new LinearLayout.LayoutParams(0,-2,1));int n=day==null?0:day.value(i);String value=n>0?n+"次/分":"—";if(i==0&&n>0)value=HealthMetricsData.timeLabel(day.latestTime)+" | "+value;TextView number=HealthUi.text(this,value,15,HealthUi.MUTED);row.addView(number);ImageView arrow=new ImageView(this);arrow.setImageResource(R.drawable.device_back);arrow.setRotation(180);arrow.setAlpha(.35f);LinearLayout.LayoutParams ap=new LinearLayout.LayoutParams(dp(18),dp(22));ap.leftMargin=dp(10);row.addView(arrow,ap);row.setOnClickListener(v->explain(metric));card.addView(row,new LinearLayout.LayoutParams(-1,dp(62)));}HealthUi.addCard(parent,card);
    }
    private void metricCard(LinearLayout parent,int metric){LinearLayout card=HealthUi.card(this,0xff1a1a1a);TextView heading=HealthUi.text(this,HealthUi.HEART_NAMES[metric],16,HealthUi.TEXT);heading.setTypeface(null,1);heading.setOnClickListener(v->explain(metric));LinearLayout.LayoutParams hp=new LinearLayout.LayoutParams(-1,dp(31));card.addView(heading,hp);HealthUi.divider(card);
        int average=data==null?0:data.average(period.start,period.end,metric);String number=data==null?"—":metric==3?(average>0?""+average:"—"):HealthMetricsData.rangeText(data.range(period,metric));TextView value=HealthUi.text(this,number+"次/分",26,HealthUi.TEXT);value.setTypeface(null,1);HealthUi.padding(value,0,17,0,10);card.addView(value);
        HealthMetricsData.Period before=period.previous();int previous=data==null?0:data.average(before.start,before.end,metric),delta=average-previous;
        if(average>0&&previous>0){String change="日均"+HealthUi.HEART_NAMES[metric]+(delta>0?"升高 "+delta:delta<0?"下降 "+(-delta):"持平")+(delta==0?"":" 次/分  "+(delta>0?"↑":"↓"));TextView comparison=HealthUi.text(this,change,16,HealthUi.MUTED);comparison.setOnClickListener(v->HealthUi.sheet(this,"数据对比",null,"",before.label()+"："+previous+"次/分\n"+period.label()+"："+average+"次/分\n\n日均值仅计算有记录的日期。"));card.addView(comparison);}
        HealthChartView graph=new HealthChartView(this);graph.bind(data,period,metric,true,true);LinearLayout.LayoutParams gp=new LinearLayout.LayoutParams(-1,dp(160));gp.topMargin=dp(20);card.addView(graph,gp);String last=mode==1?"上周":mode==2?"上月":Integer.toString(period.start.getYear()-1)+"年",current=mode==1?"本周":mode==2?"本月":period.start.getYear()+"年";
        LinearLayout legend=new LinearLayout(this);TextView old=HealthUi.text(this,"● "+last,14,0xffaaaaaa);old.setGravity(Gravity.CENTER);TextView now=HealthUi.text(this,"● "+current,14,HealthMetricsData.RED);now.setGravity(Gravity.CENTER);legend.addView(old,new LinearLayout.LayoutParams(0,dp(35),1));legend.addView(now,new LinearLayout.LayoutParams(0,dp(35),1));card.addView(legend);HealthUi.addCard(parent,card);
    }
    private void explain(int metric){HealthMetricsData.Day d=data==null?null:data.find(date);String value=mode==0?(d!=null&&d.value(metric)>0?Integer.toString(d.value(metric)):"—"):data==null?"—":HealthMetricsData.rangeText(data.range(period,metric));HealthUi.sheet(this,HealthUi.HEART_NAMES[metric],value,"次/分",HealthUi.HEART_EXPLANATIONS[metric]);}
    private void warningDetails(){StringBuilder body=new StringBuilder();int shown=0;if(data!=null)for(HealthMetricsData.Warning w:data.warnings)if(period.contains(HealthMetricsData.date(w.start))){shown++;body.append(HealthMetricsData.shortDate(HealthMetricsData.date(w.start))).append(' ').append(HealthMetricsData.timeLabel(w.start)).append("–").append(HealthMetricsData.timeLabel(w.end)).append("\n").append(w.min).append('-').append(w.max).append("次/分\n\n");}if(data!=null&&data.warningCount(period)>shown)body.insert(0,"所选时段共 "+data.warningCount(period)+" 次，以下显示最近 "+shown+" 条。\n\n");if(body.length()==0)body.append(data!=null&&data.officialLoaded?"所选时段没有安静心率预警记录。":"尚未读取该时段的预警记录。");HealthUi.sheet(this,"安静心率预警",null,"",body.toString());}
    private void menu(){View anchor=toolbar.getChildAt(toolbar.getChildCount()-1);PopupMenu menu=new PopupMenu(this,anchor);if(mode==0)menu.getMenu().add(line?"切换为柱状图":"切换为曲线图").setOnMenuItemClickListener(item->{line=!line;getSharedPreferences("health_ui",MODE_PRIVATE).edit().putBoolean("heart_line",line).apply();build(true);request(false);return true;});menu.getMenu().add("数据说明").setOnMenuItemClickListener(item->{HealthUi.sheet(this,"数据说明",null,"",HealthUi.HEART_EXPLANATIONS[0]+"\n\n"+HealthUi.HEART_EXPLANATIONS[1]);return true;});menu.show();}
}
