package com.example.opponotificationrelay;
import android.content.Context;import com.heytap.health.core.widget.charts.GluCombineChart;import com.heytap.health.core.widget.charts.data.TimeUnit;import com.oplus.aiunit.vision.d3k;import java.time.*;import java.util.*;
final class OfficialGlucoseChart {
 static GluCombineChart create(Context context,HealthMetricsData data,HealthMetricsData.Period p){Context ui=OfficialUiResources.wrap(context);GluCombineChart chart=new GluCombineChart(ui);chart.setXAxisTimeUnit(p.mode==3?TimeUnit.ORIGINAL:TimeUnit.DAY);chart.setTimeXAxisMinimum(p.mode==3?0:HealthMetricsData.time(p.start));chart.setTimeXAxisMaximum(p.mode==3?11:HealthMetricsData.time(p.end));chart.setDrawZeroGridLine(true);chart.D(false,true);chart.setBarWidth2(p.mode==1?.47619048f:p.mode==3?.5416667f:.5f);chart.setExtraXAxisSpace(.25f);chart.p(16,12,35,26);chart.getXAxis().setLabelCount(p.mode==1?7:6,false);chart.setXAxisValueFormatter((i,v)->p.mode==3?(Math.round(v)+1)+"月":Integer.toString(HealthMetricsData.date((long)(v*86400000L)).getDayOfMonth()));chart.setYAxisValueFormatter((i,v)->String.format(Locale.CHINA,"%.1f",v));
  List<d3k> bars=new ArrayList<>();float maximum=10;for(int i=0;i<p.count();i++){LocalDate a=p.at(i),b=p.mode==3?a.plusMonths(1).minusDays(1):a;int low=0,high=0;if(data!=null)for(HealthMetricsData.Day d:data.days.subMap(a,true,b,true).values())if(d.glucoseMin>0&&d.glucoseMax>=d.glucoseMin){low=low==0?d.glucoseMin:Math.min(low,d.glucoseMin);high=Math.max(high,d.glucoseMax);}if(low>0){bars.add(new d3k(p.mode==3?i:HealthMetricsData.time(a),low/1000f,high/1000f));maximum=Math.max(maximum,high/1000f+2);}}
  chart.getAxisRight().setAxisMinimum(0);chart.getAxisRight().setAxisMaximum(maximum);chart.setYAxisRightValues(new float[]{0,maximum});if(bars.isEmpty()){chart.clear();chart.setNoDataText("暂无数据");}else chart.E(new ArrayList(),bars);
  OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{d3k q=(d3k)entry.getData();return heading?(p.mode==3?(q.a+1)+"月":HealthMetricsData.shortDate(HealthMetricsData.date(q.a))):String.format(Locale.CHINA,"%.1f–%.1f mmol/L",q.b,q.c);});chart.setContentDescription("血糖范围图，"+bars.size()+"个区间");return chart;
 }
}
