package com.example.opponotificationrelay;
import android.app.Activity;import android.content.Context;import android.view.View;import android.widget.LinearLayout;
import com.heytap.health.core.widget.charts.data.*;import com.heytap.health.hrv.ui.chart.BaseChart;import com.heytap.health.hrv.constant.HrvConstant;import com.heytap.health.relax.view.RelaxBarChart;import com.heytap.health.relax.bean.RelaxBarData;import com.heytap.health.sunshine.ui.compose.DayDetailKt;
import com.github.mikephil.charting.data.*;import com.github.mikephil.charting.interfaces.datasets.ILineDataSet;import java.time.*;import java.util.*;
final class OfficialWellnessCharts {
 static void sunshineDay(Activity a,LinearLayout body,HealthMetricsData.Day day){if(day==null||day.sunshineMinutes<0)return;OfficialMentalDetails.card(a,body,149701,c->DayDetailKt.f(day.sunshineMinutes,day.sunshineTarget,false,c,0,0));}
 static View relaxDay(Context context,HealthMetricsData data,LocalDate date){Context ui=OfficialUiResources.wrap(context);RelaxBarChart chart=new RelaxBarChart(ui);OfficialChartSupport.enumOption(chart,"setStyle","com.heytap.health.relax.view.RelaxBarChart$Style","DAY");chart.setBarWidth(.2857143f);chart.setRadius(5);chart.setXAxisMinimum(0);chart.setXAxisMaximum(8);chart.setXAxisLabelCount(9);chart.setYAxisMinimum(0);chart.setShowYAxisStartLine(true);chart.setShowYAxisEndLine(true);chart.setExtraTopOffset(54);chart.setHighlightFullBarEnabled(true);long[] breath=new long[4],meditation=new long[4];if(data!=null)for(HealthMetricsData.Relax q:data.relax(date)){int bucket=Instant.ofEpochMilli(q.time).atZone(HealthMetricsData.ZONE).getHour()/6;if(q.type==1)breath[bucket]+=q.seconds;else if(q.type==2)meditation[bucket]+=q.seconds;}List<RelaxBarData> bars=new ArrayList<>();int valid=0;for(int n=0;n<4;n++){if(breath[n]+meditation[n]>0)valid++;bars.add(new RelaxBarData(HealthMetricsData.time(date)+n*6*3600000L,meditation[n],breath[n]));}String[] labels={"0–6时","6–12时","12–18时","18–24时"};chart.setXAxisValueFormatter((n,v)->n>=0&&n<8&&n%2==1?labels[n/2]:"");if(valid==0)chart.clear();else chart.setRelaxBarData(bars);OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{RelaxBarData q=(RelaxBarData)entry.getData();int bucket=Math.max(0,Math.min(3,(int)entry.getX()/2));return heading?HealthMetricsData.shortDate(date)+" "+labels[bucket]:Math.round((q.getBreath()+q.getMeditation())/60f)+" 分钟";});chart.setContentDescription("放松日图，四个6小时时段，"+valid+"个有效时段");return chart;}
 static String label(HealthMetricsData.Period p,long stamp){return p.mode==3?(stamp+1)+"月":HealthMetricsData.shortDate(HealthMetricsData.date(stamp));}
 static View create(Context context,HealthMetricsData data,HealthMetricsData.Period p,int kind){Context ui=OfficialUiResources.wrap(context);List<TimeStampedData> points=new ArrayList<>();float maximum=30;
  for(int i=0;i<p.count();i++){LocalDate a=p.at(i),b=p.mode==3?a.plusMonths(1).minusDays(1):a;float sum=0;int n=0,state=0;boolean reached=false;if(data!=null)for(HealthMetricsData.Day d:data.days.subMap(a,true,b,true).values()){if(kind==5&&d.mentalAverage>0){sum+=d.mentalAverage;n++;state=d.mentalState;}else if(kind==7&&d.sunshineMinutes>=0){sum+=d.sunshineMinutes;n++;state=d.sunshineType;reached=d.sunshineTarget>0&&d.sunshineMinutes>=d.sunshineTarget;}}
   if(n==0)continue;float value=kind==5?sum/n:sum;TimeStampedData q=new TimeStampedData(p.mode==3?i:HealthMetricsData.time(a),value);q.setHeartRateType(kind==5&&p.mode==3?Math.min(4,Math.max(1,((int)value-1)/25+1)):state);maximum=Math.max(maximum,value+5);
   if(kind==7){String suffix=p.mode==3||reached?"":"_not_reach";q.setGradientColor(new HealthGradientColor(AdditionalCardUi.color(ui,"health_sunshine_chart_bar_bottom"+suffix),AdditionalCardUi.color(ui,"health_sunshine_chart_bar_top"+suffix)));}points.add(q);
  }
  if(kind==5){BaseChart chart=new BaseChart(ui);chart.setChartType(1);chart.setDrawZeroGridLine(false);chart.setExtraSpace(.5f);chart.setLineStrokeWidth(6);chart.setCircleStrokeRadius(2);chart.setCircleStrokeHoleRadius(3);chart.setXAxisTimeUnit(p.mode==3?TimeUnit.ORIGINAL:TimeUnit.DAY);chart.setTimeXAxisMinimum(p.mode==3?0:HealthMetricsData.time(p.start));chart.setTimeXAxisMaximum(p.mode==3?11:HealthMetricsData.time(p.end));chart.p(16,12,34,26);chart.setBaseLines(HrvConstant.INSTANCE.a());
   List<ILineDataSet> sets=new ArrayList<>();List<TimeStampedData> segment=new ArrayList<>();long previous=Long.MIN_VALUE;for(TimeStampedData q:points){long current=p.mode==3?q.getTimestamp():HealthMetricsData.date(q.getTimestamp()).toEpochDay();if(previous!=Long.MIN_VALUE&&current!=previous+1&&!segment.isEmpty()){sets.add(chart.u(segment));segment=new ArrayList<>();}segment.add(q);previous=current;}if(!segment.isEmpty())sets.add(chart.u(segment));if(sets.isEmpty())chart.clear();else{CombinedData combined=new CombinedData();combined.setData(new LineData(sets));chart.setData(combined);}chart.getXAxis().setLabelCount(p.mode==1?7:6);chart.setXAxisValueFormatter((i,v)->p.mode==3?(Math.round(v)+1)+"月":Integer.toString(HealthMetricsData.date((long)(v*86400000L)).getDayOfMonth()));OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{TimeStampedData q=(TimeStampedData)entry.getData();return heading?label(p,q.getTimestamp()):Math.round(q.getY())+" · "+WellnessUi.mentalState(q.getHeartRateType());});chart.setContentDescription("身心状态多日曲线，"+points.size()+"个有效数据点");return chart;}
  if(kind==7){com.heytap.health.sunshine.ui.chart.BaseChart chart=new com.heytap.health.sunshine.ui.chart.BaseChart(ui);chart.setChartType(1);chart.setDrawZeroGridLine(false);chart.setExtraSpace(.5f);chart.setXAxisTimeUnit(p.mode==3?TimeUnit.ORIGINAL:TimeUnit.DAY);chart.setTimeXAxisMinimum(p.mode==3?0:HealthMetricsData.time(p.start));chart.setTimeXAxisMaximum(p.mode==3?11:HealthMetricsData.time(p.end));chart.p(16,12,34,26);chart.setYAxisRightValues(new float[]{0,maximum/2,maximum});chart.getXAxis().setLabelCount(p.mode==1?7:6);chart.setXAxisValueFormatter((i,v)->p.mode==3?(Math.round(v)+1)+"月":Integer.toString(HealthMetricsData.date((long)(v*86400000L)).getDayOfMonth()));if(points.isEmpty())chart.clear();else chart.x(points,p.mode==3?.5f:.85f);OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{TimeStampedData q=(TimeStampedData)entry.getData();return heading?label(p,q.getTimestamp()):Math.round(q.getY())+" 分钟";});chart.setContentDescription("日照时长柱状图，"+points.size()+"个有效数据点");return chart;}
  RelaxBarChart chart=new RelaxBarChart(ui);OfficialChartSupport.enumOption(chart,"setStyle","com.heytap.health.relax.view.RelaxBarChart$Style",p.mode==3?"YEAR":p.mode==2?"MONTH":"WEEK");chart.setXAxisTimeUnit(p.mode==3?TimeUnit.ORIGINAL:TimeUnit.DAY);chart.setBarWidth(p.mode==3?.36630037f:.2f);chart.setRadius(5);chart.setXAxisLabelCount(p.mode==1?7:6);chart.setTimeXAxisMinimum(p.mode==3?0:TimeUnit.DAY.timeStampToUnitDouble(HealthMetricsData.time(p.start)));chart.setTimeXAxisMaximum(p.mode==3?11:TimeUnit.DAY.timeStampToUnitDouble(HealthMetricsData.time(p.end)));chart.setExtraOffsets(16,12,34,26);List<RelaxBarData> bars=new ArrayList<>();int nonempty=0;
  for(int i=0;i<p.count();i++){LocalDate a=p.at(i),b=p.mode==3?a.plusMonths(1):a.plusDays(1);long breath=0,meditation=0;if(data!=null)for(HealthMetricsData.Relax q:data.relax.subMap(HealthMetricsData.time(a),true,HealthMetricsData.time(b),false).values()){if(q.type==1)breath+=q.seconds;else if(q.type==2)meditation+=q.seconds;}if(breath+meditation>0)nonempty++;bars.add(new RelaxBarData(HealthMetricsData.time(a),meditation,breath));}
  if(nonempty==0)chart.clear();else chart.setRelaxBarData(bars);chart.setXAxisValueFormatter((i,v)->p.mode==3?(Math.round(v)+1)+"月":Integer.toString(HealthMetricsData.date((long)(v*86400000L)).getDayOfMonth()));OfficialChartSupport.configure(chart,"暂无数据",(entry,heading)->{RelaxBarData q=(RelaxBarData)entry.getData();return heading?HealthMetricsData.shortDate(HealthMetricsData.date(q.getTimestamp())):"呼吸 "+q.getBreath()/60+" 分钟 · 冥想 "+q.getMeditation()/60+" 分钟";});chart.setContentDescription("放松时长柱状图，"+nonempty+"个有效数据点");return chart;
 }
}
