package com.example.opponotificationrelay;
import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.util.*;

public final class SleepDetailActivity extends OfficialUiActivity implements HealthDataManager.Listener {
    private LocalDate date=LocalDate.now(),rollingStart;private int mode;private HealthMetricsData data;private HealthMetricsData.Period period;private ScrollView scroll;private TextView status;
    @Override public void onUiCreate(Bundle state){super.onUiCreate(state);try{date=LocalDate.parse(state==null?getIntent().getStringExtra("date"):state.getString("date"));String start=state==null?getIntent().getStringExtra("start"):state.getString("start");if(start!=null)rollingStart=LocalDate.parse(start);}catch(Exception ignored){}mode=state==null?getIntent().getIntExtra("mode",0):state.getInt("mode");build(false);}
    @Override protected void onUiStart(){super.onUiStart();HealthDataManager.get(this).add(this);HealthDataManager.get(this).request(period,date,false);HealthSyncManager.get(this).request(false);}
    @Override protected void onUiStop(){HealthDataManager.get(this).remove(this);data=null;super.onUiStop();}
    @Override protected void onUiSaveInstanceState(Bundle b){b.putString("date",date.toString());if(rollingStart!=null)b.putString("start",rollingStart.toString());b.putInt("mode",mode);super.onUiSaveInstanceState(b);}
    @Override public void changed(HealthMetricsData value,String message,boolean busy){if(value!=data){data=value;build(true);}status.setText(message);status.setVisibility(message.isEmpty()?View.GONE:View.VISIBLE);}
    private void change(LocalDate d,int m){if(d.isAfter(LocalDate.now()))d=LocalDate.now();if(d.isBefore(LocalDate.of(2019,1,1)))return;date=d;mode=m;rollingStart=null;build(false);HealthDataManager.get(this).request(period,date,false);}
    private void shift(int sign){if(rollingStart!=null){long days=java.time.temporal.ChronoUnit.DAYS.between(rollingStart,date)+1;LocalDate next=date.plusDays(sign*days);if(next.isAfter(LocalDate.now())){change(LocalDate.now(),mode);return;}rollingStart=rollingStart.plusDays(sign*days);date=next;build(false);HealthDataManager.get(this).request(period,date,false);}else change(sign<0?period.previous().start:period.next(),mode);}
    private void build(boolean keep){int y=keep&&scroll!=null?scroll.getScrollY():0;period=rollingStart==null?new HealthMetricsData.Period(date,mode):new HealthMetricsData.Period(rollingStart,date,mode);LinearLayout root=HealthUi.vertical(this);root.setBackgroundColor(0xff1a1a1a);HealthUi.header(this,root,"睡眠",()->HealthUi.sheet(this,"睡眠数据",null,"","睡眠时长、阶段与体征来自穿戴设备记录。\n\n点按时间线可查看每段睡眠；日均值仅统计有记录的日期。"));HealthUi.segments(this,root,mode,m->change(date,m));LinearLayout calendar=HealthUi.vertical(this);HealthUi.padding(calendar,18,0,18,0);HealthUi.dateRow(this,calendar,period.label(),period.end.isBefore(LocalDate.now()),()->shift(-1),()->shift(1),()->HealthUi.pick(this,date,d->change(d,mode)));root.addView(calendar);
        scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=HealthUi.vertical(this);scroll.addView(body);LinearLayout top=HealthUi.vertical(this);HealthUi.padding(top,18,8,18,15);HealthMetricsData.Day day=data==null?null:data.find(date);int[] values=SleepSummaryChart.values(data,period.start,period.end);int minutes=mode==0?(day==null?0:day.sleepMinutes):values[4];top.addView(HealthUi.text(this,mode==0?"全天睡眠":"日均睡眠时长",16,HealthUi.MUTED));TextView total=duration(minutes,36);HealthUi.padding(total,0,9,0,0);top.addView(total);
        if(mode==0){SleepTimelineView timeline=new SleepTimelineView(this);timeline.bind(data==null?Collections.emptyList():data.sleep(date));FrameLayout chartFrame=new FrameLayout(this);chartFrame.addView(timeline,new FrameLayout.LayoutParams(-1,-1));ImageButton expand=new ImageButton(this);expand.setImageResource(R.drawable.official_health_expand);expand.setContentDescription("展开睡眠时间线");expand.setBackgroundColor(android.graphics.Color.TRANSPARENT);HealthUi.padding(expand,7,7,7,7);expand.setOnClickListener(v->expand());FrameLayout.LayoutParams expandLayout=new FrameLayout.LayoutParams(HealthUi.dp(this,38),HealthUi.dp(this,38),Gravity.TOP|Gravity.END);expandLayout.topMargin=HealthUi.dp(this,13);chartFrame.addView(expand,expandLayout);top.addView(chartFrame,new LinearLayout.LayoutParams(-1,HealthUi.dp(this,205)));
            LinearLayout times=new LinearLayout(this);TextView in=HealthUi.text(this,day==null||day.sleepIn==0?"—\n入睡 —":dateText(day.sleepIn)+"\n入睡 "+HealthMetricsData.timeLabel(day.sleepIn),12,0xff777777);TextView out=HealthUi.text(this,day==null||day.sleepOut==0?"—\n醒来 —":dateText(day.sleepOut-60000)+"\n醒来 "+HealthMetricsData.timeLabel(day.sleepOut-60000),12,0xff777777);in.setLineSpacing(HealthUi.dp(this,3),1);out.setLineSpacing(HealthUi.dp(this,3),1);out.setGravity(Gravity.END);times.addView(in,new LinearLayout.LayoutParams(0,-2,1));times.addView(out,new LinearLayout.LayoutParams(0,-2,1));top.addView(times);}
        else{SleepSummaryChart chart=new SleepSummaryChart(this);chart.bind(data,period);top.addView(chart,new LinearLayout.LayoutParams(-1,HealthUi.dp(this,266)));}
        if(mode==0){LinearLayout legend=new LinearLayout(this);HealthUi.padding(legend,0,14,0,0);for(int i=0;i<4;i++){TextView item=HealthUi.text(this,"",14,HealthUi.MUTED);android.text.SpannableString legendLabel=new android.text.SpannableString("●  "+SleepTimelineView.NAMES[i]);legendLabel.setSpan(new android.text.style.ForegroundColorSpan(SleepTimelineView.COLORS[i]),0,1,33);item.setText(legendLabel);item.setGravity(Gravity.CENTER);legend.addView(item,new LinearLayout.LayoutParams(0,-2,1));}top.addView(legend);}body.addView(top);
        LinearLayout lower=HealthUi.vertical(this);lower.setBackgroundColor(0xff000000);HealthUi.padding(lower,18,18,18,24);LinearLayout quality=card("睡眠质量");int score=data==null?0:mode==0?(day==null?0:day.sleepScore):data.average(period.start,period.end,HealthMetricsData.SLEEP_SCORE);LinearLayout scoreRow=new LinearLayout(this);scoreRow.setGravity(Gravity.CENTER_VERTICAL);OfficialSleepScoreView dial=new OfficialSleepScoreView(this);dial.setData(100,score,"分","--");LinearLayout.LayoutParams dialLayout=new LinearLayout.LayoutParams(Math.round(120*OfficialUiScale.density(this)),Math.round(120*OfficialUiScale.density(this)));scoreRow.setPadding(0,Math.round(20*OfficialUiScale.density(this)),0,0);dialLayout.rightMargin=HealthUi.dp(this,18);scoreRow.addView(dial,dialLayout);TextView scoreLabel=HealthUi.text(this,score<=0?"暂无评分":(mode==0?"睡眠评分":"日均睡眠评分"),16,HealthUi.TEXT);scoreLabel.setLineSpacing(HealthUi.dp(this,9),1);scoreRow.addView(scoreLabel);quality.addView(scoreRow);HealthUi.addCard(lower,quality);
        LinearLayout stages=card("睡眠阶段");int[] stageValues=mode==0&&day!=null?new int[]{day.deep,day.light,day.rem,day.awake,day.sleepMinutes}:values;int sum=stageValues[0]+stageValues[1]+stageValues[2];int deep=sum>0?(int)Math.ceil(stageValues[0]*100.0/sum):0,rem=sum>0?(int)Math.ceil(stageValues[2]*100.0/sum):0;
        if(mode==0&&day!=null&&day.sleepIn>0){TextView range=HealthUi.text(this,"睡眠（"+HealthMetricsData.timeLabel(day.sleepIn)+"–"+HealthMetricsData.timeLabel(day.sleepOut-60000)+"  "+SleepSummaryChart.duration(day.sleepMinutes)+"）",14,HealthUi.MUTED);HealthUi.padding(range,0,20,0,0);stages.addView(range);}
        for(int i=0;i<4;i++){int percent=i==0?deep:i==2?rem:100-deep-rem;String amount=sum==0?"—":SleepSummaryChart.duration(stageValues[i])+(i<3?" | "+percent+"%":mode==0&&day!=null?" | "+day.wakes+"次":"");String assessment=sum==0?"":i==0?(percent<10?"偏少":percent<20?"较少":"正常"):i==1?(percent>(rem>0?70:90)?"偏多":percent>(rem>0?60:80)?"较多":"正常"):i==2?(percent<10?"较少":percent>30?"较多":"正常"):(stageValues[i]>40?"偏多":stageValues[i]>=20?"较多":"正常");stageRow(stages,(mode==0?"":"日均")+SleepTimelineView.NAMES[i],amount,assessment,SleepTimelineView.COLORS[i]);}HealthUi.addCard(lower,stages);
        if(mode==0){LinearLayout vitals=card("体征");vital(vitals,"睡眠呼吸率",day!=null&&day.breathLow>0?String.format(Locale.ROOT,"%.1f–%.1f 次/分",day.breathLow/10.0,day.breathHigh/10.0):"—");vital(vitals,"睡眠心率范围",day!=null&&day.sleepHrLow>0?day.sleepHrLow+"–"+day.sleepHrHigh+" 次/分":"—");vital(vitals,"睡眠基准心率",day!=null&&day.sleepHeart>0?day.sleepHeart+" 次/分":"—");vital(vitals,"睡眠HRV均值",day!=null&&day.mentalSleepHrv>0?day.mentalSleepHrv+" 毫秒":"—");vital(vitals,"平均睡眠血氧",day!=null&&day.spo2>0?day.spo2+"%":"—");String wrist="—";if(day!=null&&day.wristConfidence>0&&day.wristBase>0&&day.wristValue>0){double delta=OfficialWristChart.value(day);wrist=String.format(Locale.ROOT,"%s%.1f°C",delta>0?"+":"",delta)+(delta==0?" 与基线持平":" 较基线");}vital(vitals,"手腕温度",wrist);HealthUi.addCard(lower,vitals);}
        else if(data!=null&&(mode==1||mode==2)){HealthMetricsData.Trend trend=new HealthMetricsData.Trend(data,period.end,HealthMetricsData.SLEEP_SCORE,mode==2);LinearLayout comparison=card("睡眠评分");TextView wording=HealthUi.text(this,trend.before>0&&trend.after>0?trend.wording():"所选时段日均评分 "+(score>0?score+"分":"—"),21,HealthUi.TEXT);HealthUi.padding(wording,0,18,0,10);comparison.addView(wording);if(trend.before>0&&trend.after>0){TrendComparisonChart chart=new TrendComparisonChart(this);chart.bind(trend);comparison.addView(chart);}HealthUi.addCard(lower,comparison);}
        if(mode==0&&day!=null&&day.apneaLevel>=-1){LinearLayout apnea=card("睡眠呼吸暂停");android.content.Context ui=OfficialUiResources.wrap(this);apnea.addView(HealthUi.text(this,AdditionalCardUi.apnea(ui,day.apneaLevel),24,HealthUi.TEXT));if(day.apneaAhi>=0)apnea.addView(HealthUi.text(this,"AHI "+String.format(java.util.Locale.CHINA,"%.2f",day.apneaAhi/1000f),16,HealthUi.MUTED));com.heytap.health.healthbase.view.HealthProgressBarView3 bar=new com.heytap.health.healthbase.view.HealthProgressBarView3(ui);AdditionalCardUi.apneaBar(ui,bar,day.apneaLevel);apnea.addView(bar,new LinearLayout.LayoutParams(-1,HealthUi.dp(this,48)));apnea.setContentDescription("睡眠呼吸暂停，查看详情");apnea.setOnClickListener(v->startActivity(new android.content.Intent(this,AdditionalHealthActivity.class).putExtra("vital",10).putExtra("date",date.toString())));HealthUi.addCard(lower,apnea);}
        status=HealthUi.text(this,"",12,0xff888888);status.setVisibility(View.GONE);lower.addView(status);body.addView(lower);DetailKnowledge.add(this,body,2,data);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);DeviceStyle.insets(this,root);if(y>0)scroll.post(()->scroll.scrollTo(0,y));}
    private String dateText(long t){LocalDate d=HealthMetricsData.date(t);return d.getMonthValue()+"/"+d.getDayOfMonth();}
    private LinearLayout card(String title){LinearLayout c=HealthUi.card(this,0xff1a1a1a);TextView heading=HealthUi.text(this,title,18,HealthUi.TEXT);heading.setTypeface(null,1);HealthUi.padding(heading,0,0,0,17);c.addView(heading);HealthUi.divider(c);return c;}
    private void stageRow(LinearLayout parent,String name,String amount,String assessment,int color){LinearLayout row=new LinearLayout(this);row.setGravity(Gravity.CENTER_VERTICAL);HealthUi.padding(row,0,22,0,22);LinearLayout left=HealthUi.vertical(this);TextView title=HealthUi.text(this,"● "+name,16,color);left.addView(title);TextView value=HealthUi.text(this,amount,16,HealthUi.TEXT);HealthUi.padding(value,0,10,0,0);left.addView(value);row.addView(left,new LinearLayout.LayoutParams(0,-2,1));TextView state=HealthUi.text(this,assessment,15,assessment.equals("正常")?0xff00c28c:0xffee8a47);row.addView(state);parent.addView(row);}
    private void vital(LinearLayout parent,String title,String value){LinearLayout row=HealthUi.vertical(this);HealthUi.padding(row,0,22,0,22);row.addView(HealthUi.text(this,title,16,HealthUi.MUTED));TextView number=HealthUi.text(this,value,24,HealthUi.TEXT);HealthUi.padding(number,0,10,0,0);row.addView(number);int kind=title.equals("手腕温度")?4:title.equals("平均睡眠血氧")?3:title.equals("睡眠HRV均值")?5:title.contains("心率")?1:0;if(kind>0){row.setContentDescription(title+"，查看详情");row.setOnClickListener(v->startActivity(new android.content.Intent(this,kind==1?HeartDetailActivity.class:kind==5?WellnessDetailActivity.class:VitalsDetailActivity.class).putExtra("date",date.toString()).putExtra("vital",kind)));}parent.addView(row);}
    private TextView duration(int minutes,int size){String s=SleepSummaryChart.duration(minutes);TextView t=HealthUi.text(this,"",size,HealthUi.TEXT);android.text.SpannableString span=new android.text.SpannableString(s);for(String unit:new String[]{"小时","分钟"}){int at=s.indexOf(unit);if(at>=0)span.setSpan(new android.text.style.AbsoluteSizeSpan(16,true),at,at+unit.length(),33);}t.setText(span);return t;}
    private void expand(){startActivity(new android.content.Intent(this,SleepTimelineActivity.class).putExtra("date",date.toString()));}

}
