package com.example.opponotificationrelay;

import android.app.*;
import android.os.*;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.time.temporal.ChronoUnit;
import java.util.*;

/** Drill-down for the metrics shown by the health-trend cards. */
public final class TrendMetricActivity extends Activity implements HealthDataManager.Listener {
    private int metric=HealthMetricsData.STEPS,mode=1;private LocalDate date=LocalDate.now(),rollingStart;private HealthMetricsData data;
    private LinearLayout root,toolbar;private ScrollView scroll;private TextView status;private HealthMetricsData.Period period;
    @Override public void onCreate(Bundle state){super.onCreate(state);metric=getIntent().getIntExtra("metric",HealthMetricsData.STEPS);if(metric<4||metric>6)metric=4;
        try{date=LocalDate.parse(state!=null?state.getString("date"):getIntent().getStringExtra("date"));String start=state!=null?state.getString("start"):getIntent().getStringExtra("start");if(start!=null)rollingStart=LocalDate.parse(start);}catch(Exception ignored){}
        mode=state!=null?state.getInt("mode"):getIntent().getIntExtra("mode",getIntent().getBooleanExtra("monthly",false)?2:1);
        if(metric==6){android.content.Intent intent=new android.content.Intent(this,SleepDetailActivity.class).putExtra("date",date.toString()).putExtra("mode",mode);if(rollingStart!=null)intent.putExtra("start",rollingStart.toString());startActivity(intent);finish();return;}build(false);
    }
    @Override protected void onStart(){super.onStart();if(metric==6)return;HealthDataManager.get(this).add(this);HealthDataManager.get(this).request(date,false,false);}
    @Override protected void onStop(){HealthDataManager.get(this).remove(this);super.onStop();}
    @Override protected void onSaveInstanceState(Bundle state){state.putString("date",date.toString());if(rollingStart!=null)state.putString("start",rollingStart.toString());state.putInt("mode",mode);super.onSaveInstanceState(state);}
    @Override public void changed(HealthMetricsData value,String message,boolean busy){if(value!=data){data=value;build(true);}if(status!=null){status.setText(message);status.setVisibility(message.isEmpty()?View.GONE:View.VISIBLE);}}
    private String name(){return metric==4?"步数":metric==5?"活动消耗":"睡眠";}
    private String unit(){return metric==4?"步":metric==5?"千卡":"分";}
    private void change(LocalDate value,int m){if(value.isAfter(LocalDate.now()))value=LocalDate.now();if(value.isBefore(LocalDate.of(2019,1,1)))return;date=value;mode=m;rollingStart=null;build(false);HealthDataManager.get(this).request(date,false,false);}
    private void shift(int direction){if(rollingStart!=null){long days=ChronoUnit.DAYS.between(rollingStart,date)+1;LocalDate next=date.plusDays(days*direction);if(next.isAfter(LocalDate.now())){change(LocalDate.now(),mode);return;}rollingStart=rollingStart.plusDays(days*direction);date=next;build(false);HealthDataManager.get(this).request(date,false,false);}else change(direction<0?period.previous().start:period.next(),mode);}
    private void build(boolean keep){int old=keep&&scroll!=null?scroll.getScrollY():0;period=rollingStart==null?new HealthMetricsData.Period(date,mode):new HealthMetricsData.Period(rollingStart,date,mode);root=HealthUi.vertical(this);root.setBackgroundColor(metric==6?0xff1a1a1a:0xff3b3b3b);toolbar=HealthUi.header(this,root,name(),this::menu);HealthUi.segments(this,root,mode,m->change(date,m));LinearLayout calendar=HealthUi.vertical(this);HealthUi.padding(calendar,18,0,18,0);HealthUi.dateRow(this,calendar,mode==0?period.label():mode==1||rollingStart!=null?HealthMetricsData.rangeLabel(period.start,period.end):period.label(),period.end.isBefore(LocalDate.now()),()->shift(-1),()->shift(1),()->HealthUi.pick(this,date,d->change(d,mode)));root.addView(calendar);
        scroll=new ScrollView(this);scroll.setVerticalScrollBarEnabled(false);LinearLayout body=HealthUi.vertical(this);scroll.addView(body);LinearLayout top=HealthUi.vertical(this);HealthUi.padding(top,18,0,18,15);String label=mode==0?name():metric==4?"日均步数":metric==5?"日均消耗":"日均睡眠时长";if(metric==6&&mode==0)label="睡眠时长";top.addView(HealthUi.text(this,label,16,HealthUi.MUTED));int value=data==null?0:mode==0?data.sum(period.start,period.end,metric):data.average(period.start,period.end,metric);int[] sleep=SleepSummaryChart.values(data,period.start,period.end);TextView number=metric==6?sleepValue(sleep[4]):HealthUi.value(this,value>0?""+value:"—",unit(),42);HealthUi.padding(number,0,7,0,9);top.addView(number);TextView source=HealthUi.text(this,"数据来源于穿戴设备",15,0xff888888);if(metric!=6)top.addView(source);
        View chart;if(metric==6){SleepSummaryChart stages=new SleepSummaryChart(this);stages.bind(data,period);chart=stages;}else{HealthChartView bars=new HealthChartView(this);bars.bind(data,period,metric,false,false);chart=bars;}LinearLayout.LayoutParams chartParams=new LinearLayout.LayoutParams(-1,HealthUi.dp(this,metric==6?266:218));chartParams.topMargin=HealthUi.dp(this,15);top.addView(chart,chartParams);body.addView(top);
        LinearLayout lower=HealthUi.vertical(this);lower.setBackgroundColor(0xff000000);HealthUi.padding(lower,18,22,18,24);if(data!=null){if(metric==6)sleepQuality(lower,sleep);HealthMetricsData.Trend trend=new HealthMetricsData.Trend(data,metric==6?period.end:period.end.plusDays(1),metric,mode==2);
            if(mode==1||mode==2){LinearLayout card=HealthUi.card(this,0xff3b3b3b);TextView heading=HealthUi.text(this,trend.title(),16,HealthUi.TEXT);HealthUi.padding(heading,0,0,0,16);card.addView(heading);HealthUi.divider(card);TextView words=HealthUi.text(this,trend.before>0&&trend.after>0?trend.wording()+" "+(trend.delta()>0?"↑":trend.delta()<0?"↓":""):"所选时段记录",23,HealthUi.TEXT);HealthUi.padding(words,0,14,0,12);card.addView(words);
                String summary=HealthMetricsData.rangeLabel(period.start,period.end)+(metric==4?"共走了 "+data.sum(period.start,period.end,metric)+" 步，":metric==5?"活动消耗共 "+data.sum(period.start,period.end,metric)+" 千卡，":"")+(metric==6?"日均评分":label)+" "+value+" "+unit();TextView bodyText=HealthUi.text(this,summary,16,HealthUi.MUTED);bodyText.setLineSpacing(HealthUi.dp(this,3),1);card.addView(bodyText);
                List<HealthMetricsData.Point> points=data.metricPoints(period,metric);if(!points.isEmpty()){HealthMetricsData.Point best=Collections.max(points,(a,b)->Float.compare(a.value,b.value));String weekday=Instant.ofEpochMilli(best.time).atZone(HealthMetricsData.ZONE).getDayOfWeek().getDisplayName(java.time.format.TextStyle.FULL,Locale.CHINA).replace("星期","周");TextView peak=HealthUi.text(this,"其中"+weekday+(metric==4?"步数最多":metric==5?"消耗最多":"评分最高")+" ★",16,HealthUi.MUTED);HealthUi.padding(peak,0,8,0,4);card.addView(peak);}
                if(trend.before>0&&trend.after>0){TrendComparisonChart compare=new TrendComparisonChart(this);compare.bind(trend);card.addView(compare);}HealthUi.addCard(lower,card);
            }else {LinearLayout card=HealthUi.card(this,0xff3b3b3b);card.addView(HealthUi.text(this,"统计详情",16,HealthUi.TEXT));HealthUi.padding(card,18,18,18,18);TextView totals=HealthUi.text(this,mode==0?"当天记录："+(value>0?value+" "+unit():"暂无记录"):"记录天数："+data.validDays(period.start,period.end,metric)+" 天\n日均："+value+" "+unit(),17,HealthUi.MUTED);HealthUi.padding(totals,0,18,0,0);card.addView(totals);HealthUi.addCard(lower,card);}}
        status=HealthUi.text(this,"",12,0xff888888);status.setVisibility(View.GONE);lower.addView(status);body.addView(lower);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);DeviceStyle.insets(this,root);if(old>0)scroll.post(()->scroll.scrollTo(0,old));
    }
    private TextView sleepValue(int minutes){String text=SleepSummaryChart.duration(minutes);TextView v=HealthUi.text(this,"",42,HealthUi.TEXT);android.text.SpannableString span=new android.text.SpannableString(text);for(String unit:new String[]{"小时","分钟"}){int at=text.indexOf(unit);if(at>=0)span.setSpan(new android.text.style.AbsoluteSizeSpan(18,true),at,at+unit.length(),android.text.Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);}v.setText(span);return v;}
    private void sleepQuality(LinearLayout lower,int[] values){LinearLayout card=HealthUi.card(this,0xff1a1a1a);TextView heading=HealthUi.text(this,"睡眠质量",18,HealthUi.TEXT);heading.setTypeface(null,1);HealthUi.padding(heading,0,0,0,16);card.addView(heading);HealthUi.divider(card);String[] names={"深睡","浅睡","快速眼动","清醒"};int total=values[0]+values[1]+values[2];for(int i=0;i<4;i++){final int stage=i;int deep=total>0?(int)Math.ceil(values[0]*100.0/total):0,rem=total>0?(int)Math.ceil(values[2]*100.0/total):0;int percent=total==0?0:i==0?deep:i==2?rem:100-deep-rem;TextView t=HealthUi.text(this,(mode==0?"":"日均")+names[i]+"  "+SleepSummaryChart.duration(values[i])+(i<3&&total>0?" | "+percent+"%":""),17,HealthUi.TEXT);HealthUi.padding(t,0,22,0,22);t.setOnClickListener(v->HealthUi.sheet(this,names[stage],null,"","所选时段"+(mode==0?"":"日均")+names[stage]+"："+SleepSummaryChart.duration(values[stage])+"。\n\n数据来自穿戴设备记录的睡眠阶段。"));card.addView(t);}HealthUi.addCard(lower,card);}
    private void menu(){PopupMenu popup=new PopupMenu(this,toolbar.getChildAt(toolbar.getChildCount()-1));popup.getMenu().add("数据说明").setOnMenuItemClickListener(item->{HealthUi.sheet(this,"数据说明",null,"","日均值仅计算有记录的日期。\n\n点按图表可查看相应日期的记录；上方可切换日、周、月、年和日期。");return true;});popup.show();}
}
